DuckDuckGo.xcodeproj/project.pbxproj, DuckDuckGo.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved, LocalPackages/DataBrokerProtection/Package.swift, LocalPackages/NetworkProtectionMac/Package.swift, LocalPackages/SubscriptionUI/Package.swift, UnitTests/Common/Extensions/URLExtensionTests.swift
Task/Issue URL: https://app.asana.com/0/1204006570077678/1208002970105121/f
CC:
This pull request introduces a change on how we check for valid hostnames. The current regurlar expression had an issue where some mathematical expressions where valid hostnames.
BSK PR: https://github.com/duckduckgo/BrowserServicesKit/pull/952
1. Open the app
2. Put 16385-12228.75 in the address bar
3. This should do a search on our SERP instead of trying to open a webpage
4. Test other usual web sites URLs and check those are working.
=> Fix address bar queries when doing math expressions

DuckDuckGo/Tab/ViewModel/TabViewModel.swift
Task/Issue URL: https://app.asana.com/0/1201048563534612/1208145681456113/f
- Follow-up after https://github.com/duckduckgo/macos-browser/pull/3140
- Add a threshold for the trackers to be detected after navigation is finished and play the trackers animation afterwards to fix the animation not played if trackers are detected after the navigation is finished
1. Open tripadvisor.com, validate trackers animation is played
2. Navigate to other websites like google.com, http://permission.site, https://permission.site, then back to tripadvisor.com, validate the red dot is displayed for HTTP and the privacy dashboard info is updated accordingly on the websites
--- …
=> Fix trackers animation

.github/workflows/pr.yml, IntegrationTests/PrivacyDashboard/PrivacyDashboardIntegrationTests.swift
Task/Issue URL: https://app.asana.com/0/1203301625297703/1208174218141374/f
CC:
This PR updates the test report action to set `check_retries` to true, which will avoid reporting a failure when a test fails and then succeeds upon a retry.
2. Check that the diff matches the [action documentation](https://github.com/mikepenz/action-junit-report)
---
[Pull Request …
=> Update CI test report to avoid reporting successful retries as failures

LocalPackages/DataBrokerProtection/Sources/DataBrokerProtection/Model/PageElement.swift, LocalPackages/DataBrokerProtection/Tests/DataBrokerProtectionTests/DataBrokerOperationActionTests.swift
Task/Issue URL: https://app.asana.com/0/0/1208188892446269/f
CC:
1.
---
=> Support min/max values in the JSON for random number generation

DuckDuckGo.xcodeproj/project.pbxproj, DuckDuckGo.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved, DuckDuckGo/Application/AppConfigurationURLProvider.swift, DuckDuckGo/Common/Utilities/UserDefaultsWrapper.swift, DuckDuckGo/Configuration/ConfigurationStore.swift, LocalPackages/DataBrokerProtection/Package.swift, LocalPackages/NetworkProtectionMac/Package.swift, LocalPackages/SubscriptionUI/Package.swift, UnitTests/AppDelegate/AppConfigurationURLProviderTests.swift
Task/Issue URL: https://app.asana.com/0/1171671347221384/1208194339440141/f
CC:
**Description**: Remove all references to the obsolete FBConfig file, which has been replaced by the shared privacy config
1.
---
=> remove references to obsolete FBConfig

DuckDuckGo/Bookmarks/Model/BookmarkDragDropManager.swift, DuckDuckGo/Bookmarks/Model/BookmarkOutlineViewDataSource.swift, DuckDuckGo/Bookmarks/View/BookmarkListViewController.swift, DuckDuckGo/Bookmarks/View/BookmarkManagementDetailViewController.swift
Task/Issue URL: https://app.asana.com/0/1204006570077678/1208204239267626/f
CC:
- Fix a bug where bookmark reordering was possible during search (both in the panel and the manager)
- Fix a bug where the folder was not correctly highlighted after being tapped in the bookmarks panel
1. Start a search (either in the bookmarks manager o panel)
2. Check that you cannot reorder items
3. You should be able to drop items in a folder
—
[Pull Request …
=> Bug: Disable boomark reordering when searching

DuckDuckGo.xcodeproj/project.pbxproj, DuckDuckGo/Bookmarks/View/BookmarkListViewController.swift, DuckDuckGo/Menus/MainMenuActions.swift, UITests/BookmarkSearchTests.swift, UITests/BookmarkSortTests.swift, UITests/Common/XCUIApplicationExtension.swift
Task/Issue URL: https://app.asana.com/0/1204006570077678/1208153822177986/f
CC:
Adds UI tests for bookmarks sort:
- Test that changing sort in the panel is reflected in the Bookmarks Manager page and vice versa
- Test that manual, name ascending and name descending sorting work as expected (both in panel and manager)
- Test that selected sorting is persisted through browser restarts
1. Run the `BookmarkSortTests` class
2. Check the UI tests work.
—
[Pull Request …
=> Implement bookmarks sort UI tests

DuckDuckGo/YoutubePlayer/Onboarding/DuckPlayerOnboardingModal/DuckPlayerOnboardingModalView.swift
Task/Issue URL: https://app.asana.com/0/1204167627774280/1208215097981301/f
Remove DuckPlayer onboarding animation
Center dax logo with dialog
1. Trigger the onboarding, make sure there's no animation when moving from modal A to modal B
=> Remove DuckPlayer onboarding animation

DuckDuckGo/Application/AppDelegate.swift, DuckDuckGo/DBP/DataBrokerProtectionFeatureGatekeeper.swift, DuckDuckGo/Freemium/FreemiumDebugMenu.swift, DuckDuckGo/NavigationBar/View/NavigationBarViewController.swift, DuckDuckGo/RemoteMessaging/RemoteMessagingConfigMatcherProvider.swift, DuckDuckGo/Tab/View/BrowserTabViewController.swift, LocalPackages/DataBrokerProtection/Sources/DataBrokerProtection/Scheduler/DataBrokerProtectionAgentManager.swift, LocalPackages/DataBrokerProtection/Sources/DataBrokerProtection/Utils/DataBrokerProtectionAgentStopper.swift, LocalPackages/DataBrokerProtection/Tests/DataBrokerProtectionTests/DataBrokerProtectionAgentManagerTests.swift, LocalPackages/DataBrokerProtection/Tests/DataBrokerProtectionTests/DataBrokerProtectionAgentStopperTests.swift, LocalPackages/DataBrokerProtection/Tests/DataBrokerProtectionTests/Mocks.swift, LocalPackages/Freemium/Package.swift, LocalPackages/Freemium/Sources/Freemium/FreemiumPIRUserStateManager.swift, LocalPackages/Freemium/Tests/FreemiumTests/FreemiumPIRUserStateManagerTests.swift, UnitTests/DBP/Tests/DataBrokerProtectionFeatureGatekeeperTests.swift, UnitTests/RemoteMessaging/RemoteMessagingClientTests.swift
Task/Issue URL: https://app.asana.com/0/1201621853593513/1208197280287450/f
CC: @miasma13 
**Description**: As an outcome of [this](https://github.com/duckduckgo/macos-browser/pull/3178#discussion_r1740054714) discussion, I have refactored `FreemiumPIRUserStateManager` to remove it’s dependency on `AccountManager`. This includes the removal of the `isActiveUser` computed property. The main reason for this change is as follows:
* In the app we rely on a single instance of `AccountManager` which is used throughout the app and accessed via the “singleton” `Subscription` instance, which is a property on the app delegate. By injecting an instance of `AccountManager` into `FreemiumPIRUserStateManager`, we introduce a new possible point of error. Injecting a new instance of `AccountManager` into …
=> Freemium PIR: Refactor Freemium PIR State to Remove Dependency on AccountManager

DuckDuckGo/Freemium/PIR/FreemiumPIRFeature.swift, DuckDuckGo/NavigationBar/View/NavigationBarViewController.swift, DuckDuckGo/Tab/View/BrowserTabViewController.swift, LocalPackages/DataBrokerProtection/Tests/DataBrokerProtectionTests/DataBrokerProtectionAgentManagerTests.swift, LocalPackages/DataBrokerProtection/Tests/DataBrokerProtectionTests/DataBrokerProtectionAgentStopperTests.swift, LocalPackages/DataBrokerProtection/Tests/DataBrokerProtectionTests/Mocks.swift, UnitTests/DBP/Tests/DataBrokerProtectionFeatureGatekeeperTests.swift, UnitTests/Freemium/PIR/FreemiumPIRFeatureTests.swift, UnitTests/Menus/MoreOptionsMenuTests.swift, UnitTests/RemoteMessaging/RemoteMessagingClientTests.swift
Task/Issue URL: https://app.asana.com/0/0/1208081037247881/f
**Description**: This PR implements disabling of PIR and deletion of related data when:
1. The user had onboarded to Freemium AND
2. The feature flag is disabled
**Testing Prerequisites**
1. Make sure you are an internal user
2. Disable/Signout of Privacy Pro (Settings menu -> PP -> Remove from this device)
3. Set a breakpoint in `FreemiumPIRFeature` at line `96`
4. Make sure this [JSON Blob](https://www.jsonblob.com/1280575341952098304) has `freemium` set to `internal`. Then use the debug menu to set a custom config to [this](https://www.jsonblob.com/api/1280575341952098304), and refresh the config
**TEST 1 - Onboard to Freemium Then Disable the Feature
1. Open Freemium PIR via More Options Menu -> …
=> Freemium PIR: Disable and Delete PIR If the Freemium Feature Is Disabled

DuckDuckGo/Tab/Model/Tab.swift, DuckDuckGo/Tab/View/WebView.swift, DuckDuckGo/Tab/ViewModel/TabViewModel.swift
Task/Issue URL: https://app.asana.com/0/1207686573307971/1208100557904771/f
**Description**: Fix an issue where a cycle of same document navigations are triggered.
This is fixed by updating the zoom on navigationDidCommit rather than on tab content change.
A second step to avoid to reload shield animation on the same page is webViewDidFinishNavigationPublisher updates only when not same-document navigations.
1. go to https://www.realtor.com/realestateandhomes-search/Duluth_MN?view=map&pos=46.955704,-92.397107,46.584657,-91.833761,10.881999999999996&qdm=true and check that the dashboard is not flickering and zooming the page and zooming or viewing the maps works as expected
2. Go to a website zoom in or out then in a new tab visit the same website and check the …
=> fix zoom updated

DuckDuckGo/Common/Localizables/UserText.swift, DuckDuckGo/FeatureFlagging/Model/FeatureFlag.swift, DuckDuckGo/Localizable.xcstrings, DuckDuckGo/PhishingDetection/PhishingDetection.swift, DuckDuckGo/Preferences/View/PreferencesGeneralView.swift, DuckDuckGo/Preferences/View/PreferencesRootView.swift
Task/Issue URL: https://app.asana.com/0/1199230911884351/1208149630394246/f
Tech Design URL: https://app.asana.com/0/481882893211075/1207220724600204/f
CC:
Implement GeneralPreferencesView for Phishing Detection Error Page. Also add feature flag for enabling/disabling the preferences view.
1. Go to Settings>General
2. Check there is a Malicious Site Protection section
3. Turn it off
4. Visit privacy-test-pages.site/security/badware/phishing.html
5. Check error page is not shown
6. Turn it back on
7. Retest, ensure the error page is shown
--- …
=> Add Phishing Detection Preferences

UITests/BookmarkSortTests.swift, UITests/Common/XCUIApplicationExtension.swift
Task/Issue URL: https://app.asana.com/0/1204006570077678/1208220055565873/f
CC:
A bad merge introduced this, we should use the `newApp` instead of the terminated `app` for the test that checks state restoration.
1. Run the `testThatSortIsPersistedThroughBrowserRestarts` UI test
2. Check is passing
—
=> Fix bookmark sort UI tests failure

DuckDuckGo.xcodeproj/xcshareddata/xcschemes/DuckDuckGo Privacy Browser App Store.xcscheme, DuckDuckGo.xcodeproj/xcshareddata/xcschemes/DuckDuckGo Privacy Browser.xcscheme
With these changes Xcode can now show metadata in the console:
=> Xcode console fix

DuckDuckGo.xcodeproj/project.pbxproj, UITests/Common/UITests.swift, UITests/PinnedTabsTests.swift
Task/Issue URL: https://app.asana.com/0/1204006570077678/1205717021705370/f
CC:
Adds the following test cases for pinned tabs:
Test 1:
- Right-click on one of the tabs you want to pin
- Click "Pin tab". 
- Expected behaviour: The tab should be locked, automatically moved to the left  side of the tab bar. Pinned tabs have shorter width. The tab icon or title should be condensed. On both windows the tab should be pinned.
Test 2:
- Pin another tab
- Expected behaviour: This new pinned tab should be sitting on the right of the last pinned tab.
Test 3:
- Open new tabs in that same window
- Expected behaviour: Pinned tabs remain visible and accessible
Test 4:
- Reorder the pin tabs
- Expected behaviour: Pinned tabs can be reordered among themselves
Test 5:
- …
=> Implement pinned tabs UI tests

DuckDuckGo.xcodeproj/project.pbxproj, DuckDuckGo.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved, LocalPackages/DataBrokerProtection/Package.swift, LocalPackages/NetworkProtectionMac/Package.swift, LocalPackages/SubscriptionUI/Package.swift
Task/Issue URL: https://app.asana.com/0/1201614831475344/1208235498182984/f
CC: @tomasstrba 
Updates C-S-S version to 6.14.1 (Fixes a styling bug with the “Restart to update” button on the Release Notes special page)
1. Run locally
2. Navigate to duck://release-notes
3. Confirm that release notes show without any obvious styling issues
<!—
If this PR isn't ready to be merged for whatever reason it should be marked with the `DO NOT MERGE` label (particularly if it's a draft)
If it's pending Product Review/PFR, please add the `Pending Product Review` label.
If at any point it isn't actively being worked on/ready for review/otherwise moving forward (besides the above PR/PFR exception) strongly consider closing it (or not …
=> Bump C-S-S to 6.14.1

DuckDuckGo/NavigationBar/View/NavigationBarViewController.swift, DuckDuckGo/NetworkProtection/AppTargets/BothAppTargets/NetworkProtectionNavBarButtonModel.swift
Task/Issue URL: https://app.asana.com/0/1199230911884351/1208255115319777/f
CC:
This PR fixes an issue where the "Show VPN in browser toolbar" setting wasn't worked properly when disabled. Specifically, if you disabled this setting then opened the panel from the "..." menu, the VPN button stayed visible.
1. Sign into Privacy Pro
2. Go into the app settings, then in the VPN settings panel disable "Show VPN in browser toolbar"
3. Open the "..." the open the VPN popover from the Privacy Pro option
4. Close the panel and make sure that the VPN button disappears
5. Check that enabling the  "Show VPN in browser toolbar" setting still keeps the button around permanently
--- …
=> Fix "Show VPN in browser toolbar" setting

.github/workflows/build_notarized.yml, .github/workflows/create_variant.yml, scripts/archive.sh
Task/Issue URL: https://app.asana.com/0/1203301625297703/1205305773210819/f
Update to macos-14 to remove our dependency on the legacy macos-12 runner, while also speeding up
DMG creation by using APFS filesystem for DMG images.
Verify that [this workflow](https://github.com/duckduckgo/macos-browser/actions/runs/10772646407) has gone all green on the first run 🚀 
---
=> Use macos-14 for DMG creation and create DMG with APFS filesystem

DuckDuckGo/Menus/MainMenuActions.swift, UITests/BookmarksAndFavoritesTests.swift, UITests/Common/XCUIApplicationExtension.swift
Task/Issue URL: https://app.asana.com/0/1201037661562251/1208242072125397/f
CC:
Removes resetting the show bookmarks bar popover from the debug menu item, and when dismissing a popover we only do it if exists, if not it continues with the test.
You can test the flow locally, but it takes some time, and we also need to make sure it’s passing in the CI. I’ve run the flow in the CI, here is the link: https://github.com/duckduckgo/macos-browser/actions/runs/10816432950/job/30007600733
— …
=> Fix UI tests failing in the CI

DuckDuckGo/Tab/TabExtensions/ContentBlockingTabExtension.swift
Task/Issue URL: https://app.asana.com/0/1207340338530322/1206840081441003/f
- Fixes Email Protection not supported when loaded before `ContentScopeUserScript`
1. Activate Settings->General->Reopen all windows from last session
2. Open …->Email Protection
3. Quit
4. `rm -rf ~/Library/WebKit/com.duckduckgo.macos.browser.debug/ContentRuleLists`
5. Run; validate Email Protection loads and there‘s no "Unavailable in this browser" message
---
[Pull Request …
=> Wait for UserScripts to be loaded for email protection

.github/workflows/sync_end_to_end.yml, .github/workflows/ui_tests.yml, DuckDuckGo.xcodeproj/xcshareddata/xcschemes/Sync End-to-End UI Tests CI.xcscheme, DuckDuckGo.xcodeproj/xcshareddata/xcschemes/UI Tests CI.xcscheme
Task/Issue URL: https://app.asana.com/0/1203301625297703/1208291139197521/f
CC: @SabrinaTardio  
The notarized app is now built on the supported version of Xcode, before being copied to UI tests runners
on macOS 13 and macOS 14. Dedicated CI schemes were added for UI Tests and Sync End-to-End Tests -
they don't depend on the app and instead they expect the app to be present in the Derived Data directory.
1. Verify that [this Sync End-to-End Tests workflow](https://github.com/duckduckgo/macos-browser/actions/runs/10826492179) compiled successfully and ran tests on the review app on macOS 13.
2. Verify that [this UI Tests workflow](https://github.com/duckduckgo/macos-browser/actions/runs/10827112306) compiled successfully and ran tests on the …
=> Update UI tests workflows to always compile the app on the supported version of Xcode

DuckDuckGo.xcodeproj/project.pbxproj, DuckDuckGo/Application/AppDelegate.swift, DuckDuckGo/Freemium/DBP/FreemiumDBPFeature.swift, DuckDuckGo/Freemium/DBP/FreemiumDBPPromotionViewCoordinating.swift, DuckDuckGo/Freemium/FreemiumDebugMenu.swift, DuckDuckGo/NavigationBar/View/NavigationBarViewController.swift, DuckDuckGo/Tab/View/BrowserTabViewController.swift, LocalPackages/DataBrokerProtection/Tests/DataBrokerProtectionTests/Mocks.swift, LocalPackages/Freemium/Sources/Freemium/FreemiumDBPUserStateManager.swift, LocalPackages/Freemium/Tests/FreemiumTests/FreemiumDBPUserStateManagerTests.swift, UnitTests/Freemium/DBP/FreemiumDBPFeatureTests.swift, UnitTests/Freemium/DBP/FreemiumDBPPresenterTests.swift, UnitTests/Freemium/DBP/FreemiumDBPPromotionViewCoordinatingTests.swift, UnitTests/Menus/MoreOptionsMenuTests.swift, UnitTests/Onboarding/Mocks/MockContentBlocking.swift, UnitTests/RemoteMessaging/RemoteMessagingClientTests.swift
Task/Issue URL: https://app.asana.com/0/0/1208258950415952/f
**Description**: This PR improves upon existing behavior by doing the following:
1. Updates `FreemiumPIRFeature` to observe changes to Privacy Config and Subscription status
2. Moves the declaration of `FreemiumPIRFeature` to the `AppDelegate`, to be accessed my multiple, distinct types
3. Observes Feature Availability changes in the new tab view Promotion Coordinator (future work will likely mean other types will also observe Feature Availability changes)
**Testing Prerequisites**
1. Make sure you are an internal user
2. Disable/Signout of Privacy Pro (Settings menu -> PP -> Remove from this device)
3. Remove an Freemium DBP data (i.e profile data) - Launch the browser and remove it via the DBP Dashboard `Edit My Info` button …
=> Freemium PIR: Improve Feature Availability Checks By Observing Config & Subscription Changes

DuckDuckGo/Bookmarks/Model/BookmarkManager.swift, DuckDuckGo/Common/Extensions/StringExtension.swift, UnitTests/Bookmarks/Model/LocalBookmarkManagerTests.swift
Task/Issue URL: https://app.asana.com/0/1203972458584429/1208262956542583/f
Tech Design URL: 
CC:
**Acceptance criteria**
**AC#1**
Given a user with a bookmark with an accent, for example `café` , when searching for `cafe` we should return the bookmark with the accent.
**AC#2**
Given a user with a bookmark without an accent, for example `cafe` , when searching for `café` we should return the bookmark without the accent, ignoring the accent on the search query.
**AC#3**
Given a user with a bookmark with symbols, for example, Site • Login , when searching for site login then we should return the bookmark with the symbol
**AC#4**
Given a user with a bookmark without symbols, for example, Site Login , when searching for site • login then we should return the bookmark without the symbol …
=> Ignore accents when doing a bookmark search

DuckDuckGo/PinnedTabs/View/PinnedTabView.swift, DuckDuckGo/TabBar/View/TabBarCollectionView.swift, DuckDuckGo/TabBar/View/TabBarViewController.swift, DuckDuckGo/TabBar/View/TabBarViewItem.swift, UnitTests/TabBar/View/MockTabViewItemDelegate.swift
Task/Issue URL: https://app.asana.com/0/1201048563534612/1208209124965669/f
CC:
This update adds support for dragging strings to the new tab button and the tab bar. 
- When a string is dropped to the new tab button, it opens a new tab with a search on the dropped string.
- When a string is dropped to the current tab (both regular and pinned tabs), the tab gets replaced by a search for the dropped string.
- When a string is dropped in the tab bar. For example, at the right of the + button when there is room, it should open a new search with the dropped string.
This request came from: https://github.com/duckduckgo/macos-browser/issues/3189
https://github.com/user-attachments/assets/d507c762-066a-4022-8813-5b82747b55c0
**Verify new …
=> Support dragging strings to new tab button

DuckDuckGo/Application/AppDelegate.swift, DuckDuckGo/Tab/View/BrowserTabViewController.swift
Task/Issue URL: https://app.asana.com/0/1206488453854252/1208294167066324/f
**Description**: This PR moves the declaration of FreemiumDBPPromotionViewCoordinator to the App Delegate to enable UI state to be shared by multiple windows (ensuring the new tab page is updated as expected when state changes)
**Testing Prerequisites**
1. Make sure you are an internal user
2. Disable/Signout of Privacy Pro (Settings menu -> PP -> Remove from this device)
1. Launch the browser
2. Ensure you see a Freemium PIR promotion banner on the new tab page
3. Launch a new window
4. Click the ’Scan’ button on the new tab page in one of the windows
5. Ensure the banner is removed from the new tab page in both windows (you might need to focus the other window to force it to update …
=> Freemium PIR: Enable Multi-Window Shared UI State

DuckDuckGo/Tab/TabExtensions/ContentBlockingTabExtension.swift
Task/Issue URL: https://app.asana.com/0/1207435976391442/1208283514585319/f
Wait for UserScripts to be loaded for subscription pages
1. Activate Settings->General->Reopen all windows from last session
2. Open Privacy Pro purchase page "…" -> "Privacy Pro"
3. Quit
4. rm -rf ~/Library/WebKit/com.duckduckgo.macos.browser.debug/ContentRuleLists
5. Run; validate Privacy Pro purchase page loads successfully and it is not redirected to an empty SERP page
-
1. Search for "Privacy Pro"
2. From SERP results find one for https://duckduckgo.com/pro
3. CMD + click the result multiple times to open the result in other tabs
4. Verify that all tabs have opened Privacy Pro purchase page successfully and none was redirected to an empty SERP page
**Definition of …
=> Wait for UserScripts to be loaded for subscription pages

DuckDuckGo.xcodeproj/project.pbxproj, DuckDuckGo/Bookmarks/View/BookmarkListViewController.swift, DuckDuckGo/Bookmarks/View/BookmarkManagementDetailViewController.swift, DuckDuckGo/Bookmarks/View/BookmarkManagementSplitViewController.swift, DuckDuckGo/Common/Extensions/NSEventExtension.swift, DuckDuckGo/Common/Extensions/NSMenuItemExtension.swift, DuckDuckGo/Common/View/AppKit/KeyEquivalentView.swift, DuckDuckGo/MainWindow/MainWindow.swift
Task/Issue URL:
CC:
- Fix hotkey handling in Bookmarks manager, bookmarks popover
1. validate cmd+f beeps in empty state in both Bookmarks manager, bookmarks popover
2. validate cmd+f beeps on new tab when the address bar is not active
3. validate typing letter keys in empty state doesn‘t show search in the popover
4. validate removing last bookmark in the popover hides the search bar
5. validate Esc key deactivates search in Bookmarks Manager
6. validate cmd+f works in Bookmarks Manager
--- …
=> fix hotkey handling in Bookmarks manager, Bookmarks popover

DuckDuckGo/DBP/DataBrokerProtectionFeatureGatekeeper.swift, DuckDuckGo/Freemium/DBP/FreemiumDBPFeature.swift, DuckDuckGo/Freemium/DBP/FreemiumDBPFirstProfileSavedNotifier.swift, DuckDuckGo/Freemium/DBP/FreemiumDBPPresenter.swift, DuckDuckGo/Freemium/DBP/FreemiumDBPPromotionViewCoordinating.swift, DuckDuckGo/Freemium/FreemiumDebugMenu.swift, DuckDuckGo/NavigationBar/View/MoreOptionsMenu.swift, DuckDuckGo/NavigationBar/View/NavigationBarViewController.swift, DuckDuckGo/RemoteMessaging/RemoteMessagingConfigMatcherProvider.swift, LocalPackages/DataBrokerProtection/Sources/DataBrokerProtection/Utils/DataBrokerProtectionAgentStopper.swift, LocalPackages/DataBrokerProtection/Tests/DataBrokerProtectionTests/DataBrokerProtectionAgentManagerTests.swift, LocalPackages/DataBrokerProtection/Tests/DataBrokerProtectionTests/DataBrokerProtectionAgentStopperTests.swift, LocalPackages/DataBrokerProtection/Tests/DataBrokerProtectionTests/Mocks.swift, LocalPackages/Freemium/Sources/Freemium/FreemiumDBPUserStateManager.swift, LocalPackages/Freemium/Tests/FreemiumTests/FreemiumDBPUserStateManagerTests.swift, UnitTests/DBP/Tests/DataBrokerProtectionFeatureGatekeeperTests.swift, UnitTests/Freemium/DBP/FreemiumDBPFeatureTests.swift, UnitTests/Freemium/DBP/FreemiumDBPFirstProfileSavedNotifierTests.swift, UnitTests/Freemium/DBP/FreemiumDBPPresenterTests.swift, UnitTests/Freemium/DBP/FreemiumDBPPromotionViewCoordinatingTests.swift, UnitTests/Menus/MoreOptionsMenuTests.swift, UnitTests/RemoteMessaging/RemoteMessagingClientTests.swift
Task/Issue URL: https://app.asana.com/0/1206488453854252/1208294167066323/f
**Description**: This PR changes a previously defined `didOnboard` state value to `didActivate. This change is because:
1. We previously planned to “onboard” to Freemium in native code (e.g presenting Ts & Cs natively, accepting them, setting state etc.)
2. We changed this to occur on the frontend. Which means we don’t need to track `didOnboard` on the native side and propagate that to the FE.
3. So, we are removing the `didOnboard` state. 
4. However, we still need some way to track that the user is using Freemium
5. So, we introduce a new `didActivate` state, which is set when a user accesses Freemium DBP
**How to Review this PR:**
1. Commit 1 is removing usage of `didOnboard`
2. Commit 2 is all renaming
3. …
=> Freemium DBP: Change didOnboard State to didActivate

DuckDuckGo.xcodeproj/project.pbxproj, DuckDuckGo/Common/Extensions/NSPrintInfoExtension.swift, DuckDuckGo/Tab/Model/Tab+Dialogs.swift, DuckDuckGo/Tab/View/BrowserTabViewController.swift, DuckDuckGo/Tab/View/ModalSheetCancellable.swift, scripts/find_private_symbols.sh
Task/Issue URL: https://app.asana.com/0/0/1208315841728331/f
- Fix crash when printing from a pinned tab
1. Open a pinned tab
2. Open the pinned tab in a new window (so the same tab is open in 2 windows)
3. Print -> validate there‘s no crash and the dialog is only displayed in active window
---
=> Fix crash when printing from a pinned tab

DuckDuckGo/Statistics/ATB/StatisticsLoader.swift, UnitTests/Statistics/ATB/StatisticsLoaderTests.swift
Task/Issue URL: https://app.asana.com/0/1148564399326804/1208261063200358/f
Re-enabling the app retention ATB in order to monitor daily usage.
1. Run the app and type `atb` into the Console filter
2. Navigate to any website (except SERP)
3. Verify the Console contains the following message: `App retention ATB request succeeded`
4. Restart the app and navigate to any website
5. Verify the atb is NOT refreshed again
---
[Pull Request …
=> Re-enabling app retention ATB

DuckDuckGo/Bookmarks/View/BookmarkListViewController.swift
Task/Issue URL: https://app.asana.com/0/1204006570077678/1208262956542585/f
CC:
**Given** a user on the bookmarks panel, **when** the user starts a search and comes back to the tree view, **then** the selected, collapsed and expanded folders or bookmarks should be maintained.
https://github.com/user-attachments/assets/5ae781ab-e6c5-4e48-87e1-7eea9b267fda
1. Load a bunch of bookmarks
2. Go to the bookmarks panel, scroll to the last position and open some folders
3. Start a search, type something, and then cancel the search
4. The opened folders should be expanded, and the scroll position should be the same before the search.
— …
=> Maintain scroll position, selection and expanded/collapsed when returning from search on bookmarks panel

DuckDuckGo.xcodeproj/project.pbxproj, DuckDuckGo/NavigationBar/View/AddressBarButtonsViewController.swift, DuckDuckGo/NetworkProtection/AppTargets/BothAppTargets/ActiveDomainPublisher.swift, IntegrationTests/App/DeallocationTests.swift
Task/Issue URL: https://app.asana.com/0/1199178362774117/1208259344334049/f
- Fix MainWindowController leaking
- Fix Tab not deallocated on close
1. Open a video in a single tab; start playback, close the tab - validate video is stopped
2. Validate MainWindowController and all related View Controllers and models are deallocated on window close
---
=> Fix Tab; Window Controller not deallocated on close

DuckDuckGo/NetworkProtection/AppTargets/BothAppTargets/NetworkProtectionTunnelController.swift
Task/Issue URL: https://app.asana.com/0/414235014887631/1208331423616717/f
Fixes a retain cycle in `NetworkProtectionTunnelController`.
**Important:** This retain cycle is invisible in macOS because we only instantiate the tunnel controller once, so this isn't really very impactful.
Kudos to @brindy for coming up with this fix - I'm taking his proposed changes and applying them after verifying they work correctly.
**Privacy Pro Setup:**
1. If you don't have a VPN account yet, I recommend using the Stripe option from https://app.asana.com/0/1207603085593419/1207149361119036/f to set things up to test the VPN.
**Steps:**
1. Start the VPN and stop it a few times.
2. Show and hide the status bar VPN view.
4. Verify that you only see one instance of `NetworkProtectionTunnelController ` at all …
=> Fix retain cycle in NetworkProtectionTunnelController

DuckDuckGo/Bookmarks/Model/BookmarkDragDropManager.swift
Task/Issue URL: https://app.asana.com/0/1204006570077678/1208262956542588/f
CC:
**Acceptance criteria**
**AC#1**
Given a user on a website
When the user drags the URL in the address bar to the bookmarks bar menu or any sub-folder of it and the URL is not part of the bookmarks
Then it should add the bookmark to the dropped position
**AC#2**
Given a user on a website
When the user drags the URL in the address bar to the bookmarks bar menu or any sub-folder of it and the URL is part of the bookmarks
Then it should not add the bookmark to the dragged position
**AC#3**
Given a user on the browser
When the user drags a URL from another application to the bookmarks bar or any sub-folder of it
Then it should add the bookmark to the dropped position
**AC#4**
Given a user on the …
=> Accept dropping strings and URLs to the bookmarks bar menu

UITests/BookmarkSearchTests.swift, UITests/BookmarkSortTests.swift
Task/Issue URL: https://app.asana.com/0/1204006570077678/1208328455174895/f
CC:
This fixes the bookmark sort UI tests. I introduced some changes where I broke the tests (https://github.com/duckduckgo/macos-browser/pull/3253); luckily, the tests I helped create found the issue!
The main problem is that now we disable sort and search when we do not have bookmarks. UI tests didn’t account for that, so we tried accessing the sort button without bookmarks, which is now impossible.
I fixed the issue and added UI tests to cover the disable states of the sort button when there are no bookmarks.
Successful workflow: https://github.com/duckduckgo/macos-browser/actions/runs/10913325849
--- …
=> Fix bookmarks sort UI tests

LocalPackages/DataBrokerProtection/Sources/DataBrokerProtection/Database/DataBrokerProtectionDataManager.swift, LocalPackages/DataBrokerProtection/Tests/DataBrokerProtectionTests/DataBrokerProtectionDataManagingTests.swift
Task/Issue URL: https://app.asana.com/0/0/1208338809971749/f
**Description**: I noticed when testing that the results displayed on the new tab page banner were not correct. Then noticed original logic was incorrect, and counted mirror sites before checking if we had any extracted profiles.
1. Check updated unit test logic, and ensure it satisfies intention of change (that brokers are only counted when there are extracted profiles)
—
[Pull Request …
=> Freemium DBP: Bug - Fix Freemium Match Count Logic (Which Previously Counted Mirror Sites without Extracted Profiles)

DuckDuckGo/HomePage/View/HomePageView.swift
Task/Issue URL: https://app.asana.com/0/1201048563534612/1208350082163816/f
Fix Customize button layout so that it properly recognizes when there's not enough
space to display the title label.
1. Launch the app
2. Shrink the app window horizontally
3. Verify that 'Customize' button on NTP gets shrunk and hides the title.
---
=> Make 'Customize' button shrink for when app window is narrow

.github/workflows/publish_dmg_release.yml
Task/Issue URL: https://app.asana.com/0/1208036161861763/1208205621016469/f
The token is required for that step so that update_asana_for_release.sh script can actually access Asana.
---
=> Add missing Asana token to environment for populating tasks since last release

DuckDuckGo/Updates/ReleaseNotesParser.swift, UnitTests/Updates/ReleaseNotesParserTests.swift
Task/Issue URL: https://app.asana.com/0/1201048563534612/1208358673191631/f
Use H3 tag instead of H2
1. Run the app in Xcode
2. Go to Settings -> About and check for updates
3. Open a new tab and navigate to duck://release-notes
4. Verify that "For Privacy Pro subscribers" section is present in the release notes.
---
=> Fix regex pattern for parsing Privacy Pro release notes

DuckDuckGo.xcodeproj/project.pbxproj, DuckDuckGo/BookmarksBar/View/BookmarksBarViewController.swift, DuckDuckGo/BookmarksBar/View/BookmarksBarViewModel.swift, DuckDuckGo/BookmarksBar/View/LeftAlignedLayout.swift
Task/Issue URL: https://app.asana.com/0/0/1208262956542591/f
CC:
Left-aligns the bookmarks bar.
Before this change, bookmarks were centered until they occupied the whole bookmarks bar. Once the whole bar was occupied by bookmarks, the bookmarks bar became centered, and the overflow indicator was shown.
Now, bookmarks are aligned to the left. This aligns with other browsers and with Windows.
This also changed the spacing between bookmarks in the bar from six to two (something required here: https://app.asana.com/0/0/1208262956542589/f)
1. Add bookmarks
2. Check bookmarks are positioned to the left of the bookmarks bar when added.
— …
=> Left align the bookmarks bar

LocalPackages/DataBrokerProtection/Package.swift, LocalPackages/DataBrokerProtection/Sources/DataBrokerProtection/Operations/DataBrokerProtectionBrokerUpdater.swift, LocalPackages/DataBrokerProtection/Tests/DataBrokerProtectionTests/DataBrokerProtectionDatabaseProviderTests.swift
Task/Issue URL: https://app.asana.com/0/1203581873609357/1208362583268535/f
CC:
Not doing this makes it way too easy to accidentally use the fake brokers in prod, which windows has already fallen foul of.
1. In the DBP package, in resources, there is one json file at the top level, rename it so fake isn't in the name. I changed fake to fish.
2. In the actual json file itself, change its name to something you'll recognize
3. Go into the JSON subdirectory, and change the name of one of those to something you'll recognize (the actual name in the JSON itself)
4. Start the app
5. Go to the debug menu, under PIR force a broker update
6. In the same menu run PIR in debug mode
7. Look in the list of brokers for the ones you renamed. You …
=> Make BrokerUpdater obey file structure

DuckDuckGo/Bookmarks/View/BookmarkListPopover.swift, DuckDuckGo/Bookmarks/View/BookmarkListViewController.swift
Task/Issue URL: https://app.asana.com/0/1204006570077678/1208262956542590/f
CC:
**AC#1**
Given a user with a lot of bookmarks
When the user opens the bookmarks panel
Then, the popover will try to take as much available space either to the top or the bottom of the bookmarks popover button
**AC#1**
Given a user with some bookmarks
When the user opens the bookmarks panel
Then, the popover will be at least 420 wide and 500 taller.
⚠️ Ignore beach ball of death. The problem is related to having a lot of bookmarks.
https://github.com/user-attachments/assets/708b08ea-f867-4355-8e22-5a5cbadf1cfb
1. You can load 3k bookmarks from the asana ticket
2. Move the window around and test whether the popover takes the space either to the top or bottom …
=> Make bookmarks panel grow as screen permits

.github/workflows/pr_task_url.yml
Task/Issue URL: https://app.asana.com/0/1208036161861763/1207931637636063/f
Trigger add-task-to-project when PR marked ready for review
You can reproduce these steps by creating a copy of this branch and opening a PR to see the CI behavior.
1. This is what was shown in the CI checks when I opened this as a draft without links.
2. This is what I saw after adding a link, when I changed the status to "Ready for Review"
---
[Pull Request Documentation](https://app.asana.com/0/1202500774821704/1204012835277 …
=> Trigger add-task-to-project when PR marked ready for review

DuckDuckGo/Tab/TabExtensions/DuckPlayerTabExtension.swift
Task/Issue URL: https://app.asana.com/0/1204099484721401/1208386895411633/f
Fixes an issue causing Duckplayer videos not to show in new SERP overlays.  
Overlays use an iFrame, so the mainFrame condition was cancelling navigation for these videos when DuckPlayer was disabled
1. Make yourself internal user
2. Disable Duck Player
3. Disable Caches or use the Fire button
4. Go to https://use-devtesting18.duckduckgo.com/?q=metallica+videos and pick a video
5. Click "Watch here"
6. Confirm video plays in the overlay
7. Go to https://www.youtube.com/results?search_query=metallica
8. Pick a video
9. Confirm it plays in Youtube
=> Fix DuckPlayer overlays

DuckDuckGo/DBP/DataBrokerProtectionManager.swift, DuckDuckGo/NavigationBar/View/NavigationBarViewController.swift, DuckDuckGo/Preferences/View/PreferencesRootView.swift, DuckDuckGo/Tab/UserScripts/IdentityTheftRestorationPagesUserScript.swift, DuckDuckGo/UnifiedFeedbackForm/UnifiedFeedbackSender.swift, LocalPackages/DataBrokerProtection/Sources/DataBrokerProtection/Database/DataBrokerProtectionDataManager.swift, LocalPackages/DataBrokerProtection/Sources/DataBrokerProtection/UI/DBPUICommunicationLayer.swift, LocalPackages/DataBrokerProtection/Sources/DataBrokerProtection/UI/DBPUIWebConfiguration.swift
Task/Issue URL: https://app.asana.com/0/414235014887631/1207701941801991/f
Tech Design URL: https://app.asana.com/0/0/1208019880099277/f
CC:
Add support for new native callbacks.
Please check out `anh/09-24-set_origin_to_abuliga.duckduckgo.com_for_ship_review` instead of this branch. It contains the necessary origin to make the following steps work.
1. Point PIR's Web UI URL to `https://abuliga.duckduckgo.com/dbp`
2. Go to PPro > PIR and choose Send Feedback
3. You should see the web feedback form
4. Update Remote Config URL to `https://www.jsonblob.com/api/1269060462770511872`
5. Now reopen PIR and choose Send Feedback
6. You should see the native feedback form
7. Select Report a Problem
8. You should see PIR pre-populated in the sub-category …
=> Integrate native callback

DuckDuckGo/DataImport/Logins/CSV/CSVParser.swift, UnitTests/DataImport/CSVParserTests.swift
Task/Issue URL: https://app.asana.com/0/1202406491309510/1208116635478553/f
- Adds support for backslash-escaped quotes in CSV parser to support 1Password export
1. Save something with a quote in 1Password
2. Export all in "iCloud CSV" format
3. Import passwords -> Validate passwords are imported
4. Validate regular (e.g. Bitwarden) passwords import still works correctly
---
[Pull Request Documentation](https://app.asana.com/0/1202500774821704/120401283527748 …
=> CSV parser: add support for backslash-escaped quotes

DuckDuckGo/Tab/UserScripts/Subscription/SubscriptionPagesUseSubscriptionFeature.swift, DuckDuckGo/Tab/UserScripts/Subscription/SubscriptionPagesUserScript.swift, DuckDuckGo/Tab/View/BrowserTabViewController.swift, UnitTests/Subscription/SubscriptionPagesUseSubscriptionFeatureTests.swift
Task/Issue URL: https://app.asana.com/0/1206488453854252/1208399397658124/f
**Description**: This PR implements the sending of a new notification when a user purchases a PP Subscription after activating Freemium DBP. This notification is used to close any open DBP tabs. We close these tabs because after a purchase the DBP dashboard should be refreshed, and we will accomplish this by ensuring the tab is re-opened 
**Testing Prerequisites:**
1. Make sure you are an internal user
2. Disable/Signout of Privacy Pro (Settings menu -> PP -> Remove from this device)
3. Select Debug menu -> Freemium -> Set Experiment Cohort to Treatment
4. Set Subscription environment to staging
1. Launch browser (again)
2. Access Freemium DBP via the New Tab Page banner or the meatball …
=> Freemium DBP: Close Any Open Freemium DBP Tabs After Subscription Purchase Success

DuckDuckGo/Localizable.xcstrings, DuckDuckGo/Tab/TabExtensions/DuckPlayerTabExtension.swift, DuckDuckGo/YoutubePlayer/DuckPlayer.swift
Task/Issue URL: https://app.asana.com/0/1204167627774280/1208392875411872
CC:
Fix overlay issue when clicking on watch on youtube
1. Set duck player to always ask
2. Open a youtube video
3. Watch on Duck Player
4. Click on "Watch on youtube" from the overlay
5. Check if the youtube video plays without the overlay
---
=> Fix DuckPlayer overlay bug

DuckDuckGo.xcodeproj/project.pbxproj, DuckDuckGo.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved, LocalPackages/DataBrokerProtection/Package.swift, LocalPackages/NetworkProtectionMac/Package.swift, LocalPackages/SubscriptionUI/Package.swift
Task/Issue URL: https://app.asana.com/0/414709148257752/1208376794617030/f
Fixed in BSK.
When loading a website and some of the allowed third party requests may not be recognized as trackers but by their URL they may belong to the same entity as the website. For that cases we should mark their state as .`allowed(reason: .ownedByFirstParty)` (instead of `.allowed(reason: .otherThirdPartyRequest)`).
See parent task for testing steps.
---
[Pull Request …
=> For third party requests differentiate if they are affiliated with first party

DuckDuckGo.xcodeproj/project.pbxproj, DuckDuckGo/BookmarksBar/View/BookmarksBarViewController.swift, DuckDuckGo/BookmarksBar/View/BookmarksBarViewModel.swift, DuckDuckGo/BookmarksBar/View/HorizontallyCenteredLayout.swift
Task/Issue URL: https://app.asana.com/0/0/1208467487262658/f
CC:
This reverts commit `2ec29199d0ca76d941d6c0610ffdf38fd1041f1f`
We want to revert the left alignments bookmarks bar
1. Open the browser
2. Check the bookmarks bar menu is center-aligned.
—
=> Revert the left align the bookmarks bar feature

DuckDuckGo/Localizable.xcstrings, DuckDuckGo/SecureVault/Extensions/UserText+PasswordManager.swift
Task/Issue URL: https://app.asana.com/0/1201037661562251/1208424278203049/f
There were several localization warnings introduced during [✓ macOS - Mitigate users concerns about Password Manager security](https://app.asana.com/0/1199230911884351/1207411921782782/f)
- UserText.pmSaveCredentialsSecurityInfo and UserText.pmSaveCredentialsSecurityInfoAutolockOff have same keys which can‘t be localized and causes warning
- UserText.pmEmptyStateDefaultDescription has same key with pmEmptyStateDefaultDescriptionAutolockOff
Also there were some warnings about stale strings that are no longer in use so I removed them in the second commit.
Change to any language other than English and check:
1. The password manager empty state string (with autolock on and …
=> Fix autofill copy keys and squash warnings

DuckDuckGo.xcodeproj/project.pbxproj, DuckDuckGo/Autofill/Debug/AutofillCredentialsDebugView.swift, DuckDuckGo/Autofill/Debug/AutofillCredentialsDebugViewModel.swift, DuckDuckGo/DeviceAuthentication/DeviceAuthenticator.swift, DuckDuckGo/Menus/MainMenu.swift, DuckDuckGo/Menus/MainMenuActions.swift
Task/Issue URL: https://app.asana.com/0/1201462886803403/1207890203714430/f
CC:
New debug screen to display raw data from the credentials DB to help diagnose credential sync issues between platforms
1. Ensure you have some credentials saved
2. Via the Debug menu, go to “Autofill” -> “View all Credentials”
3. Confirm you are required to authenticate
4. Once authenticated, confirm you can view all your credential data
5. Click on column headers and confirm the sorting updates accordingly
— …
=> Adds new debug screen to view raw credentials data

scripts/appcast_manager/appcastManager.swift
Task/Issue URL: https://app.asana.com/0/1203301625297703/1208492347129471/f
This change fixes appcast diff generation for public releases, where prior to running generate_appcast
we remove the promoted version from the appcast completely, to allow Sparkle to re-add it from scratch.
The change ensures that the appcast file backup (used for generating the diff) is always created from the
original appcast file, freshly downloaded from the CDN.
1. Set up Sparkle binary tools as instructed in [this task](https://app.asana.com/0/1199230911884351/1208493161720355/f).
2. Create a file called `release-notes.txt` in the root directory of the macOS repository, containing a single line: `Bug fixes and improvements.`.
3. Call appcastManager to prepare the …
=> Back up appcast2.xml file as soon as it's downloaded by appcastManager.swift

DuckDuckGo.xcodeproj/project.pbxproj, DuckDuckGo.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved, DuckDuckGo/FeatureFlagging/Model/FeatureFlag.swift, LocalPackages/DataBrokerProtection/Package.swift, LocalPackages/NetworkProtectionMac/Package.swift, LocalPackages/SubscriptionUI/Package.swift
Task/Issue URL: https://app.asana.com/0/72649045549333/1208381891916914/f
CC:
Add userTips feature flag
1. You can add `print("USER ON? \(NSApp.delegateTyped.featureFlagger.isFeatureOn(.networkProtectionUserTips))")` to the App Delegate and check if the flag is returning as true (it should)
2. You can also change the config URL to this: https://jsonblob.com/api/1292861631544287232 which has the flag set to false and make sure that now the `isFeatureOn` function returns false
=>  Update BSK version to support userTips NetP Flag

DuckDuckGo/NetworkProtection/AppTargets/BothAppTargets/ActiveDomainPublisher.swift
Task/Issue URL: https://app.asana.com/0/1201048563534612/1208463834186044/f
For some weeks we've had reports about music playing after a browser window playing music is closed. Turns out an indirect reference to the WebView was being held through the `ActiveDomainPublisher` introduced during https://github.com/duckduckgo/macos-browser/pull/3076. I've made an attempt at fixing this, but lemme know if there's a better way.
1. Open a single browser window.
2. Go to soundcloud.com and start any music playing
3. Close the window
**4. Music should stop playing**
--- …
=> Ensure tab state is torn down on window close

.github/workflows/build_notarized.yml
Task/Issue URL: https://app.asana.com/0/1203301625297703/1208498816479865/f
This change updates build_notarized.yml so that it uploads dSYMs and DMGs to S3 test builds location
also when Asana task URL is not provided.
Verify that [this workflow](https://github.com/duckduckgo/macos-browser/actions/runs/11237833287) completed successfully, and that it contains links to the build and dSYMs posted in "Create DMG summary" on the bottom of the workflow summary page.
--- …
=> Upload DMG to S3 test builds by default

DuckDuckGo/Info.plist
Task/Issue URL: https://app.asana.com/0/1201037661562251/1206468896778225/f
Use LSMultipleInstancesProhibited Info.plist flag to prevent running multiple instances of the app,
even if the user attempts launching multiple copies of the bundle.
1. Install the review app built by [this workflow](https://github.com/duckduckgo/macos-browser/actions/runs/11054893731)
2. Copy the app bundle under a different name
3. Launch the original app
4. Try launching the copied bundle
5. Verify that instead of a second app instance being launched, the original instance gets focused and only 1 instance is running.
--- …
=> Prohibit running multiple instances of the app

DuckDuckGo/Tab/TabExtensions/ContentBlockingTabExtension.swift
Task/Issue URL: https://app.asana.com/0/1207104330327543/1208508938068402/f
1. Run the app from Xcode (or grab a review build from [here](https://staticcdn.duckduckgo.com/macos-desktop-browser/a81f9679-e41d-404d-81a6-fd4a461d82f7/testbuilds/1a36e72/duckduckgo-1.109.0.278.dmg)).
2. Subscribe to Privacy Pro.
3. Go to Main Menu -> Debug -> Tab -> Append Tabs -> 50 Tabs
4. While tabs are loading, go to meatball menu -> Privacy Pro -> Identity Theft Restoration.
5. Verify that ITR landing page loads, and you're not redirected to SERP.
--- …
=> Delay loading Identity Theft Restoration until Content Blocking rules are loaded in the tab

DuckDuckGo/Assets.xcassets/Images/Import-16D.imageset/Contents.json
Task/Issue URL: https://app.asana.com/0/1204186595873227/1208423163807230/f
**Description**: Fix import bookmarks icon in dark mode
1. Make the bookmark bar visible
2. Ensure you don’t have any bookmarks on
3. You should see the import bookmark button and related icon 
4. Check the icon is visible in both dark and light mode
<!—
If this PR isn't ready to be merged for whatever reason it should be marked with the `DO NOT MERGE` label (particularly if it's a draft)
If it's pending Product Review/PFR, please add the `Pending Product Review` label.
If at any point it isn't actively being worked on/ready for review/otherwise moving forward (besides the above PR/PFR exception) strongly consider closing it (or not opening it in the first place). If …
=> fix icon in dark mode

LocalPackages/DataBrokerProtection/Sources/DataBrokerProtection/Scheduler/DataBrokerProtectionAgentManager.swift, LocalPackages/DataBrokerProtection/Sources/DataBrokerProtection/Scheduler/DataBrokerProtectionQueueManager.swift, LocalPackages/DataBrokerProtection/Sources/DataBrokerProtection/Utils/Logger+DataBrokerProtection.swift, LocalPackages/DataBrokerProtection/Tests/DataBrokerProtectionTests/DataBrokerProtectionAgentManagerTests.swift, LocalPackages/DataBrokerProtection/Tests/DataBrokerProtectionTests/DataBrokerProtectionQueueManagerTests.swift, LocalPackages/DataBrokerProtection/Tests/DataBrokerProtectionTests/DataBrokerProtectionQueueModeTests.swift, LocalPackages/DataBrokerProtection/Tests/DataBrokerProtectionTests/Mocks.swift
Task/Issue URL: https://app.asana.com/0/1203581873609357/1208333317271878/f
CC:
Opt outs are triggered as soon as initial scan finishes.
1. If you build from Xcode 16, check out this branch instead: https://github.com/duckduckgo/macos-browser/tree/anh/always-show-webview (context: https://app.asana.com/0/414235014887631/1208502720748038/f)
2. Go through the PIR flow, ideally with a test profile with at least 2 parent brokers
3. Check console logs while attaching to `DuckDuckGo Personal Information Removal` to verify that the opt out jobs are submitted when the initial scan finishes.
4. Open Debug > PIR > DB Browser and double check the OptOutJob table. 
--- …
=> Run opt outs when profile is saved

LocalPackages/DataBrokerProtection/Sources/DataBrokerProtection/Database/DataBrokerProtectionDataManager.swift, LocalPackages/DataBrokerProtection/Sources/DataBrokerProtection/Model/DBPUICommunicationModel.swift, LocalPackages/DataBrokerProtection/Sources/DataBrokerProtection/UI/UIMapper.swift, LocalPackages/DataBrokerProtection/Tests/DataBrokerProtectionTests/DataBrokerProtectionDataManagingTests.swift
Task/Issue URL: https://app.asana.com/0/72649045549333/1208507342220062/f
**Description**: This PR fixes an issue with Freemium PIR where the results displayed on the new tab page do not match the results displayed on the dashboard
**Test Prerequisites**
1. Set yourself as an internal user via Debug menu → Set Internal User State
2. Disable/Signout of Privacy Pro via Settings menu → PP →  Remove from this device
3. Select Debug menu → Freemium -> Enroll into Experiment
4. Set the custom frontend UI URL via Debug menu → Personal Information Removal → Web UI → Set Custom URL. Enter `https://abrown.duckduckgo.com/dbp`
5. Use the custom frontend UI URL via Debug menu → Personal Information Removal → Web UI → Use Custom URL
Relaunch the browser
1. Relaunch the …
=> Extract Common Logic to DBPUIDataBrokerProfileMatch for DBP UI Scan Results

UITests/UI Tests.xctestplan
Task/Issue URL: https://app.asana.com/0/1204006570077678/1208528710258901/f
CC:
**Description**
Remove `testManualSortWorksAsExpectedOnBookmarksPanel` from the skipped test.
The https://github.com/duckduckgo/macos-browser/actions/runs/11293513680 shows that the other two tests are the one that are failing.
---
=> Re-add manual sort test to the UI test plan

DuckDuckGo.xcodeproj/project.pbxproj
Task/Issue URL: https://app.asana.com/0/1207603085593419/1208543229974056/f
The VPN proxy has been embedded a long time ago into the app and recently it was enabled for the domain exclusions feature.  Unfortunately for our App Store builds, the proxy was only included in DEBUG builds.
This was done because Apple usually rejects builds that include components that cannot be used, so we needed to keep it out of release builds until it was used.
During development this was missed as the DEBUG builds include the proxy.
1. Run the VPN using an App Store release build.
2. Check that the domain exclusion feature works.
--- …
=> Includes the VPN proxy in all builds

DuckDuckGo/SecureVault/View/PasswordManagementPopover.swift
Task/Issue URL: https://app.asana.com/0/1203822806345703/1208343732992258/f
Closing the panel while the user is editing is extremely disruptive and can lead to data loss.
Users can copy/paste things from the edit mode back to the page, and it would be very frustrating.
Do not close the management UI when in edit mode, even if the user clicks within the browser.
1. Open the Password Management UI
2. Click Add New -> {Any entry} to start editing
3. Click outside of the window / change tab / switch to a different window (etc)
4. **The  Password Management UI should not close**
5. Stop editing by clicking "Cancel" or by completing the edit flow
3. Click outside of the window / change tab / switch to a different window (etc)
4. **The Password …
=> Don't close password manager while editing

DuckDuckGo.xcodeproj/project.pbxproj, DuckDuckGo/FileDownload/Model/WebKitDownloadTask.swift, DuckDuckGo/MainWindow/MainWindowController.swift
Task/Issue URL: https://app.asana.com/0/1204006570077678/1208540299371877/f
CC:
Delete in-progress downloads from the file system when the fire window is closed.
1. Open one or some fire windows
2. Go to https://www.thinkbroadband.com/download and download the 1GB file
3. Do not wait for the file to finish download
4. Press CMD + Q
5. When the pop-up appears, tap on `Quit`
6. The `.duckload` in-progress files should be deleted.
7. Test that any completed download should not be deleted from the file system.
—
[Technical …
=> Delete files when download is cancelled and comes from fire window

LocalPackages/NetworkProtectionMac/Sources/NetworkProtectionUI/NetworkProtectionPopover.swift
Task/Issue URL: https://app.asana.com/0/0/1208550201256511/f
We're fixing two issues here:
- The VPN menu popover is not getting focus under macOS Sequoia.  This can be seen when opening the popover when the connection is already established - the toggle is grey.
- Clicking outside of the popover wasn't dismissing it properly as it had no focus to begin with.
1. Connect to the VPN
2. Once the connection is up, click on the VPN menu icon in macOS's status bar and see that the toggle is not grey.
--- …
=> VPN status menu popover not getting focus

DuckDuckGo/MainWindow/MainViewController.swift, DuckDuckGo/NavigationBar/View/AddressBarButtonsViewController.swift, DuckDuckGo/NavigationBar/View/Animations/BadgeAnimations/NavigationBarBadgeAnimator.swift, DuckDuckGo/Tab/View/BrowserTabViewController.swift, UnitTests/Onboarding/ContextualOnboarding/BrowserTabViewControllerOnboardingTests.swift
Task/Issue URL: https://app.asana.com/0/72649045549333/1207994848838038
**Prerequisites:**
go to debug menu -> set internal user
go to debug menu → reset data → reset contextual onboarding
**Scenario 1: When blocked trackers dialog is shown then privacy shield should be highlighted**
1. Navigate to [DuckDuckGo.com](https://duckduckgo.com/)
2. Follow the linear onboarding.
3. Navigate to a site with known trackers e.g. bbc.com.
4. Once the blocked trackers dialog is shown and that privacy shield animation is triggered.
**Scenario 2: When Privacy Shield pulse animating then hovering on it should remove pulse animation**
1. Navigate to a site with known trackers e.g. bbc.com.
2. Hover on the privacy shield.
3. Ensure that the pulse animation is …
=> Contextual onboarding privacy icon highlight

DuckDuckGo/RemoteMessaging/RemoteMessagingClient.swift, UnitTests/Onboarding/ContextualOnboarding/BrowserTabViewControllerOnboardingTests.swift, UnitTests/RemoteMessaging/RemoteMessagingClientTests.swift
Task/Issue URL: https://app.asana.com/0/1201621708115095/1208377696019992/f
Mock RemoteMessagingConfigFetcher so that it doesn't fire a network request during unit tests.
Mock RemoteMessagingStore so that it doesn't try to access database - the store is tested
in BSK anyway and the tests here are merely about the feature flag.
---
=> Fix RemoteMessagingClient flaky unit tests

DuckDuckGo/RemoteMessaging/RemoteMessagingClient.swift
Task/Issue URL: https://app.asana.com/0/0/1208576796369178/f
Remote Messages refreshing gets in the way of unit tests so this change is preventing it from work in unit tests environment.
---
=> Don't refresh remote messages in unit tests

DuckDuckGo/Freemium/DBP/FreemiumDBPPromotionViewCoordinator.swift, DuckDuckGo/Subscription/SubscriptionAttributionPixelHandler.swift, DuckDuckGo/Tab/UserScripts/Subscription/SubscriptionPagesUseSubscriptionFeature.swift, UnitTests/Freemium/DBP/FreemiumDBPPromotionViewCoordinatorTests.swift, UnitTests/Subscription/SubscriptionPagesUseSubscriptionFeatureTests.swift
Task/Issue URL: https://app.asana.com/0/72649045549333/1208081037247873/f
**Description**: When a user has performed a Freemium PIR scan, and then subscribed - either from the Freemium dashboard or from outside it, e.g from the Privacy Pro landing page - we will attribute the Subscription to Freemium. (i.e if the user has performed a Freemium PIR scan, and then Subscribes via any entry point, we are attributing the Subscription to Freemium)
Note: I have also improved some notification tests by using the notification expectation approach.
**Test Prerequisites**
1. Set yourself as an internal user via Debug menu → Set Internal User State
2. Disable/Signout of Privacy Pro via Settings menu → PP →  Remove from this device
4. Select Debug menu → Freemium -> Enroll into Experiment
5. Set the …
=> Freemium PIR: Subscription Attribution

LocalPackages/NetworkProtectionMac/Sources/NetworkProtectionUI/Views/TunnelControllerView/TunnelControllerViewModel.swift
Task/Issue URL: https://app.asana.com/0/1206580121312550/1208597821920525/f
Fixes a retain cycle.
Note: the testing steps can be used in `main` to see the retain cycle in action.
1. Connect the VPN
2. Open and close the in-browser status view several times
3. Go to the memory graph in Xcode and see the instances of `TunnelControllerViewModel`.  You'll notice there's one instance per click.
---
=> Fixes a retain cycle in the VPN status view

DuckDuckGo/Onboarding/ContextualOnboarding/ContextualOnboardingStateMachine.swift, UnitTests/Onboarding/ContextualOnboarding/ContextualOnboardingStateMachineTests.swift
Task/Issue URL: https://app.asana.com/0/0/1208592739186210/f
**Description**: Removes the Fire popover info sheet during the onboarding
1. Run ./clean-app.sh debug
2. go to debug menu -> set internal user
3. go to debug menu → reset data → reset contextual onboarding
4. Navigate to [DuckDuckGo.com](https://duckduckgo.com/)
5. Go through the onboarding and test that when the fire-button popover appears it does not show the explanation sheet
6. Do not use the fire button
7. Complete the onboarding
8. Click on the fire button and check the explanation sheet does appear
9. Run steps 1 to 5 again
10. use the fire button
11. Complete the onboarding
12. Click on the fire button and check the explanation sheet does not appear
<!—
If this PR isn't …
=> remove fire info sheet during onboarding

DuckDuckGo/HomePage/Model/HomePageAddressBarModel.swift, DuckDuckGo/HomePage/View/AddressBarTextFieldView.swift, DuckDuckGo/HomePage/View/HomePageViewController.swift, DuckDuckGo/MainWindow/MainViewController.swift
Task/Issue URL: https://app.asana.com/0/0/1208612667210680/f
This change changes focus on New Tab Page to always be on the top address bar,
and also disables NTP settings onboarding popover for users not in the experiment.
1. Run the app.
2. Select _Main Menu -> Debug -> Reset Data -> Reset Home Page Settings Onboarding_, open new tab and verify that you don't see a popover. Quit the app.
3. Update `DefaultNewTabPageSearchBoxExperimentCohortDecider.cohort` to just `return .experiment`
4. Update line 100 in `HomeAddressBarModel.swift` to say `isExperimentActive = true` and comment out lines 103-105.
5. Run the app
6. Verify that you've seen the popover.
7. Open a few new tab pages, verify that focus stays on the top address bar at all times
8. …
=> Updates to NTP Search Box

UITests/BookmarkSortTests.swift
Task/Issue URL: https://app.asana.com/0/1201037661562251/1208616327102876/f
CC:
Fixes ` testWhenChangingSortingInThePanelIsReflectedInTheManager` UI test. The problem is that depending on the window size, the bookmarks panel might be above the sort button in the manager, causing it not to be tappable.
This started happening in the latest internal because we added a new option (delete bookmark) on the bookmarks manager, which pushed the sort button to the right.
We should run the workflow and see if it works.
---
[Technical …
=> Fix testWhenChangingSortingInThePanelIsReflectedInTheManager UI Test

DuckDuckGo/NavigationBar/View/AddressBarTextField.swift, DuckDuckGo/Suggestions/View/SuggestionViewController.swift
Task/Issue URL: https://app.asana.com/0/1202406491309510/1208622581232760/f
- Fix suggestion window `orderOut` called twice causing suggestions breakage
1. Run the app from main branch
2. Type a phrase in the address bar
3. Select a suggestion using keyboard
4. Type another phrase in the address bar
5. Click on a suggestion
---
=> fix Suggestions not reacting to clicks after being interacted with using keyboard

LocalPackages/DataBrokerProtection/Sources/DataBrokerProtection/CCF/WebViewHandler.swift
Task/Issue URL: https://app.asana.com/0/1205591970852438/1208502720748038/f
Tech Design URL: 
CC:
Implements a workaround for scans being stuck when built against Xcode 16
1. Start PIR and use a sample profile
2. Scan should finish
---
=> Workaround for stuck scans on Xcode 16

DuckDuckGo/Onboarding/OnboardingUserScript.swift
Task/Issue URL: https://app.asana.com/0/1193060753475688/1208624804500029/f
CC:
This PR fixes a memory leak in the `OnboardingUserScript`, where it was holding onto a strong reference to the user scripts broker.
1. Smoke test onboarding
2. Open and close a bunch of tab instances, then open the Memory Graph Debugger view in Xcode and check that there aren't many instances of the relevant classes hanging around
---
[Pull Request …
=> Update OnboardingUserScript to use a weak script broker reference

fastlane/Fastfile
Task/Issue URL: https://app.asana.com/0/1205419239275955/1208635844633824/f
CC: @ayoy 
- Removes retry check for `upload_metadata` lane to remove the constant checking for `[20:00:09]: Cannot find edit app info... Retrying after 300 seconds (remaining: 0)` for app info
1. Run promotion flow
---
=> remove version retry limit for metadata upload

DuckDuckGo.xcodeproj/project.pbxproj, DuckDuckGo/Common/Extensions/XMLNodeExtension.swift, DuckDuckGo/DataImport/Bookmarks/HTML/BookmarkHTMLReader.swift
Task/Issue URL: https://app.asana.com/0/1202406491309510/1208666105063018/f
- Fix crash when importing html bookmarks file with an empty root element
1. Validate attached bookmarks HTML import doesn‘t crash but fails with error
[bookmarks empty.html.zip](https://github.com/user-attachments/files/17586007/bookmarks.empty.html.zip)
---
=> Fix crash on empty bookmarks html root element

DuckDuckGo/Common/Extensions/NSViewExtension.swift, DuckDuckGo/Common/Extensions/WKWebViewConfigurationExtensions.swift, DuckDuckGo/NavigationBar/View/AddressBarButtonsViewController.swift
Task/Issue URL: https://app.asana.com/0/1202406491309510/1208667754274335/f
- Fixes crash when permission requested with NewTab  address bar experiment caused by permission popover tried to be presented on the NewTab page address bar
1. Activate the Address Bar on the NewTab home page experiment
2. Open New Tab page
3. Open a tab with https://permission.site
4. Request camera permission -> crash
---
[Pull Request …
=> Fix crash when opening permission popover for NewTab page address bar

DuckDuckGo/DuckDuckGoAppStore.entitlements, DuckDuckGo/DuckDuckGoAppStoreCI.entitlements, DuckDuckGo/DuckDuckGoAppStoreDebug.entitlements
Task/Issue URL: https://app.asana.com/0/0/1208672609826736/f
This change removes unneeded com.apple.security.device.usb entitlement usage.
1. Run the review app from [this workflow](https://github.com/duckduckgo/macos-browser/actions/runs/11652598220).
2. Connect an external drive.
3. Verify that you can download files to the external drive and upload files from it to web forms. 
---
[Pull Request Documentation](https://app.asana.com/0/1202500774821704/120401 …
=> Remove com.apple.security.device.usb entitlement

DuckDuckGo.xcodeproj/project.pbxproj, DuckDuckGo.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved, DuckDuckGo/Statistics/GeneralPixel.swift, DuckDuckGo/Sync/SyncErrorHandler.swift, LocalPackages/DataBrokerProtection/Package.swift, LocalPackages/NetworkProtectionMac/Package.swift, LocalPackages/SubscriptionUI/Package.swift
Task/Issue URL: https://app.asana.com/0/1201493110486074/1208686320819590/f
CC:
On investigating a hard-to-reproduce issue with sync, I noticed there's a gap in error reporting when the secure storage (keychain) is not available. This adds a pixel for that case.
Just a pixel in an error case. Hard to test without altering code. But if you do want to do that:
1. Enable sync
2. Change `BSK.DDGSync.SecureStorage.account()` to throw every time
3. Go to the Settings -> Sync screen
4. You should see the `sync_secure_storage_read_error` Pixel in the debug console
--- …
=> Send pixel on sync secure storage read failure

DuckDuckGo/Common/Logger+Multiple.swift, DuckDuckGo/MainWindow/MainViewController.swift, DuckDuckGo/TabPreview/TabPreviewWindowController.swift
Task/Issue URL: https://app.asana.com/0/1148564399326804/1208347387296425/f
Stuck tab preview fixed
1. Open a new window with bunch of tabs
2. Pin one tab
3. Hover mouse cursor over the pinned tab until the preview is shown and don't move with your mouse cursor
4. Use keyboard to switch to another app (CMD + TAB)
5. Move the mouse cursor to other position on the screen
6. Use keyboard to switch back to the DuckDuckGo app
7. Verify the preview is hidden 
--- …
=> Hiding of tab previews for pinned tabs fixed

DuckDuckGo/Bookmarks/Extensions/Bookmarks+Tab.swift, DuckDuckGo/Bookmarks/Services/BookmarksContextMenu.swift
Task/Issue URL: https://app.asana.com/0/1201048563534612/1208523846260390/f
CC:
Fix add to favorites and open in new tabs action not working on the bookmark manager when selecting multiple bookmarks.
1. Open Bookmarks Manager
2. Select multiple bookmarks
3. Right tap, select `Open in New Tabs`
4. All the bookmarks should be opened in new tabs
5. Select the bookmarks again (they should not be favorites), right-tap, and select `Add to favorites`
6. The bookmarks should be added to favorites
— …
=> Fix add to favorites and open in new tabs action not working on manager

.github/workflows/tag_release.yml, Gemfile.lock, fastlane/Pluginfile
Task/Issue URL: https://app.asana.com/0/1203301625297703/1208705384164248/f
run-publish-dmg-release task needs to be created directly from the GHA workflow because we want to
address the actual workflow failure (i.e. when the dependent workflow can't run). This is impossible
to check from the fastlane action.
---
=> Restore calling run-publish-dmg-release on tag_release.yml failure

UITests/OnboardingUITests.swift, UITests/PinnedTabsTests.swift
Task/Issue URL: https://app.asana.com/0/1201037661562251/1208683961540871/f
CC:
Fixes onboarding testing failing and pinned tabs tests failing on macOS 13.
✅ https://github.com/duckduckgo/macos-browser/actions/runs/11689899520
---
=> Fix UI tests failing 

DuckDuckGo/TabBar/ViewModel/TabCollectionViewModel.swift, DuckDuckGo/Windows/View/WindowControllersManager.swift
Task/Issue URL: https://app.asana.com/0/1204167627774280/1208714110522205/f
Respect new tab order preference when using WindowManager.showTab
1. Change the Tabs settings to "Add to the right of the current tab"
2. Add a couple tabs to your tabbar 
3. Select the first tab
4. Click the ... to right menu
5. Open settings (make sure there was no settings opened before)
6. Check if settings is opened in between your tabs respecting the preference
7. Enable AI Chat shortcut
8. Select the first tab, and repeat
9. Try this with other shortcuts like "go to settings" from the appearance menu
10. Change the tab settings to "Add to the right of the current tab"
11. Repeat the steps above checking if the tab now is the last one in the tab bar
=> Respect new tab order preference

DuckDuckGo/Sync/SyncDiagnosisHelper.swift
Task/Issue URL: https://app.asana.com/0/0/1208706849695203/f
Adds an `authState` parameter to the `m_mac_sync_was_disabled_unexpectedly` pixel.
1. (just for testing) Add a line of code to easily deactivate sync in a non-typical way (e.g by calling try await syncService.deleteAccount() from updateDeviceName) so you can mimic unexpected deactivation.
2. Make sure Sync is enabled
3. Trigger the fake unexpected deactivation
4. Minimize the browser and maximise again.
5. Make sure the m_mac_sync_was_disabled_unexpectedly pixel is fired.
--- …
=> Send auth state with sync unexpectedly disabled pixel

DuckDuckGo/Common/Localizables/UserText.swift, DuckDuckGo/Localizable.xcstrings, DuckDuckGo/Permissions/View/PermissionAuthorizationViewController.swift
Task/Issue URL: https://app.asana.com/0/1201037661562251/1208705844672773/f
CC:
Updates the permission string on the location popup.
1. Go to maps.google.com, tap on the use my location button
2. Check that the new format is the following: `www.site.com website would like to use your current location.`
—
=> Update permission string for location popup

DuckDuckGo/NavigationBar/View/AddressBarTextField.swift
Task/Issue URL: https://app.asana.com/0/1201048563534612/1208714740989844/f
CC:
The problem seems to be a race condition when the selected suggestion view model is updated and the suggestion view. The solution I found was not to check the window visibility when setting the `.suggestion` value.
1. Search for amazon.com and load the site
2. Open a new tab and press `a`
3. amazon.com should be autocompleted
—
[Pull Request …
=> Do not use suggestion view controller visibility to set suggestion

.github/workflows/build_notarized.yml, .github/workflows/sync_end_to_end.yml, .github/workflows/ui_tests.yml, DuckDuckGo/Freemium/DBP/FreemiumDBPPromotionViewCoordinator.swift, DuckDuckGo/HomePage/View/HomePageView.swift, UnitTests/Freemium/DBP/FreemiumDBPPromotionViewCoordinatorTests.swift
Task/Issue URL: https://app.asana.com/0/1206488453854252/1208744771117526/f
**Description**: We prevent this pixel firing and also prevent the creation of a `viewModel` unless the Freemium feature is enabled
**Test Prerequisites**:
* Set yourself as an internal user via Debug menu → Set Internal User State
* Disable/Signout of Privacy Pro via Settings menu → PP → Remove from this device
* Select Debug menu → Freemium -> Reset all Freemium State
* Select Debug menu → Freemium -> Enroll into Experiment
1. Ensure the new tab page banner appears with Freemium enabled
2. Remove internal user state
3. Relaunch
4. Ensure the new tab page banner DOES NOT appear with Freemium enabled 
— …
=> Prevent Freemium PIR Pixel Firing for All Users

DuckDuckGo/HomePage/Model/HomePageAddressBarModel.swift, DuckDuckGo/HomePage/Model/NewTabPageSearchBoxExperiment.swift, DuckDuckGo/HomePage/View/HomePageViewController.swift, DuckDuckGo/Statistics/NewTabSearchBoxExperimentPixel.swift, UnitTests/HomePage/NewTabPageSearchBoxExperimentTests.swift
Task/Issue URL: https://app.asana.com/0/1201621853593513/1208742047745355/f
This change adds a pixel that's fired when a user is enrolled into the NTP search box experiment.
1. clear app data
2. run the app from Xcode
3. check console logs and verify that `m_mac_initial-search-day-1` has been sent with `count=0`
4. run the app again
5. check console logs and verify that the pixel isn't sent.
6. return nil in `DefaultNewTabPageSearchBoxExperimentCohortDecider.cohort`
7. clear app data
8. run the app again
9. check console logs and verify that the pixel isn't sent.
--- …
=> Add cohort assignment pixel for NTP Search Box Experiment

DuckDuckGo/Updates/UpdateController.swift, DuckDuckGo/Updates/UpdateUserDriver.swift
Task/Issue URL: https://app.asana.com/0/1201048563534612/1208746324713624/f
CC:
Fixes Install Now menu item does nothing by making sure we can resume the update process. As a bonus, this fixes an edge case where the user toggles back and forth between automatic & manual update checkboxes and that causes the upgrade process to go weird. 
1. Use this build: https://staticcdn.duckduckgo.com/macos-desktop-browser/a81f9679-e41d-404d-81a6-fd4a461d82f7/testbuilds/3447618/duckduckgo-1.114.0.305.dmg
1. Test different scenarios (automatic/manual update, trigger the update from different entry points, etc)
---
[Software …
=> Enforce stricter hasPendingUpdate check

DuckDuckGo.xcodeproj/project.pbxproj, DuckDuckGo/InfoPlist.xcstrings, DuckDuckGo/Statistics/GeneralPixel.swift, DuckDuckGo/Tab/TabExtensions/DuckPlayerTabExtension.swift, DuckDuckGo/YoutubePlayer/DuckPlayerOverlayPixels.swift, UnitTests/YoutubePlayer/DuckPlayerOverlayPixelsTests.swift
Task/Issue URL: https://app.asana.com/0/1204099484721401/1208739766555303/f
- Adds temporary Overlay usage pixels
- This uses the same approach we use on iOS: https://github.com/duckduckgo/iOS/pull/3565
Notes: 
- `duckplayer.youtube.overlay.navigation.back` is only fired when navigating directly to a video.  Further back navigation will `duckplayer.youtube.overlay.navigation.within-youtube`.  This is fine as we only want to track bounces on overlay after navigating directly to a video.
- All the pixels above include unit tests
=> DuckPlayer Overlay Pixels

DuckDuckGo/Tab/TabExtensions/DuckPlayerTabExtension.swift, DuckDuckGo/YoutubePlayer/YoutubeOverlayUserScript.swift
Task/Issue URL: https://app.asana.com/0/1204099484721401/1208754606104631/f
CC:
- Move the `m_mac_duck-player_overlay_youtube_impressions` pixel to the native layer
-  Filter console logs with `m_mac_duck-player_overlay_youtube_impressions`
- Set DuckPlayer to Ask Mode
**Confirm the pixel is fired 'once' in the following scenarios when the overlay is shown.**
**Confirm Pixel is NOT fired when**
---
[Pull Request …
=> Move FE Overlay Pixel to the Native layer

DuckDuckGo/Bookmarks/Model/BookmarkOutlineViewDataSource.swift, DuckDuckGo/Bookmarks/View/BookmarkManagementDetailViewController.swift, DuckDuckGo/Bookmarks/ViewModel/SortBookmarksViewModel.swift, UnitTests/Bookmarks/ViewModels/BookmarksSortModeTests.swift
Task/Issue URL: https://app.asana.com/0/1204006570077678/1208661547711012/f
CC:
This fixes a bug where we enabled reordering bookmarks in both the panel and the manager when sort by name was enabled.
1. Go to the bookmarks panel or manager
2. Sort by name descending or ascending
3. Try to re-order bookmarks
4. It shouldn’t let you drop bookmarks to re-order them
—
[Pull Request Documentation](https://app.asana.com/0/1202500774821704/120401283 …
=> Disable reordering when sort by name is enabled

package-lock.json, package.json
Task/Issue URL: https://app.asana.com/0/1208775332166220/1208775332166220
Autoconsent Release: https://github.com/duckduckgo/autoconsent/releases/tag/v11.4.0
Updates Autoconsent to version [v11.4.0](https://github.com/duckduckgo/autoconsent/releases/tag/v11.4.0).
See release notes [here](https://github.com/duckduckgo/autoconsent/blob/v11.4.0/CHANGELOG.md)
=> Update autoconsent to v11.4.0

DuckDuckGo/Fireproofing/Extensions/FireproofingURLExtensions.swift, DuckDuckGo/Tab/Services/WebsiteDataStore.swift, UnitTests/Tab/Services/WebsiteDataStoreTests.swift
Task/Issue URL: https://app.asana.com/0/1204167627774280/1204888209490841/f
Add DDG domain name check for fireproofing storage
1. Go to a DDG domain website like https://duck.ai/ (which will redirect you to it) open the console and add something to the localStorage. `localStorage.setItem('potatoKey', 'Potato Value');`
2. Check if it's saved by running `console.log(localStorage.getItem('potatoKey'));` in the console
3. Click the fire button
4. Go back to AI Chat and validate if the data is still there with the command from step 2
=> Add DDG domain name check for fireproofing storage

package-lock.json, package.json
Task/Issue URL: https://app.asana.com/0/1208781796802510/1208781796802510
Autoconsent Release: https://github.com/duckduckgo/autoconsent/releases/tag/v11.5.0
Updates Autoconsent to version [v11.5.0](https://github.com/duckduckgo/autoconsent/releases/tag/v11.5.0).
See release notes [here](https://github.com/duckduckgo/autoconsent/blob/v11.5.0/CHANGELOG.md)
=> Update autoconsent to v11.5.0

LocalPackages/DataBrokerProtection/Sources/DataBrokerProtection/Database/DataBrokerProtectionDatabase.swift, LocalPackages/DataBrokerProtection/Sources/DataBrokerProtection/DebugUI/DataBaseBrowser/DataBrokerDatabaseBrowserViewModel.swift, LocalPackages/DataBrokerProtection/Sources/DataBrokerProtection/Storage/DataBrokerProtectionDatabaseProvider.swift, LocalPackages/DataBrokerProtection/Sources/DataBrokerProtection/Storage/DataBrokerProtectionSecureVault.swift, LocalPackages/DataBrokerProtection/Tests/DataBrokerProtectionTests/Mocks.swift
Task/Issue URL: https://app.asana.com/0/72649045549333/1208768738130147/f
CC:
Shows OptOutAttemptDB in DB Browser
1. Check DB browser
2. You should be able to view OptOutAttemptDB contents
---
=> Display OptOutAttemptDB in DB Browser

LocalPackages/DataBrokerProtection/Sources/DataBrokerProtection/Database/DataBrokerProtectionDatabase.swift, LocalPackages/DataBrokerProtection/Sources/DataBrokerProtection/DebugUI/DataBaseBrowser/DataBrokerDatabaseBrowserViewModel.swift, LocalPackages/DataBrokerProtection/Sources/DataBrokerProtection/Operations/DataBrokerProfileQueryOperationManager.swift, LocalPackages/DataBrokerProtection/Sources/DataBrokerProtection/Storage/DataBrokerProtectionDatabaseProvider.swift, LocalPackages/DataBrokerProtection/Sources/DataBrokerProtection/Storage/DataBrokerProtectionSecureVault.swift, LocalPackages/DataBrokerProtection/Tests/DataBrokerProtectionTests/DataBrokerProfileQueryOperationManagerTests.swift, LocalPackages/DataBrokerProtection/Tests/DataBrokerProtectionTests/Mocks.swift
Task/Issue URL: https://app.asana.com/0/1205591970852438/1208761697124514/f
CC:
Workaround to deal with OptOutAttemptDB having one-to-one relationship with ExtractedProfileDB.
The idea is to let subsequent attempts overwrite the previous one. Associated pixels should've already been fired, so no data loss. This would allow the opt-out operation to finish cleanly, add the right history events, and fire the correct pixels.
This is quite time consuming to verify. You may use this branch for sped up process: https://github.com/duckduckgo/macos-browser/tree/anh/pir/resubmit-opt-outs-pr-review 
1. Go through the DBP flow
2. Move the system time forward so that DBP does another scan/opt-out passes
3. As opt-out retries are done, you …
=> addAttempt workaround

DuckDuckGo/FileDownload/Model/WebKitDownloadTask.swift, DuckDuckGo/Statistics/GeneralPixel.swift
Task/Issue URL: https://app.asana.com/0/1204006570077678/1208780258680355/f
CC:
It adds the OS version to this pixel to show where we are experiencing the download issue.
1. You can add a throw in the 323 line
2. Check the `fileDownloadCreatePresentersFailed` pixel has the `OSVersion` (it should be in the logs)
—
=> Add OS version to download fail pixel

DuckDuckGo.xcodeproj/project.pbxproj, DuckDuckGo.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved, DuckDuckGo/Autofill/ContentOverlayViewController.swift, DuckDuckGo/ContentBlocker/ScriptSourceProviding.swift, DuckDuckGo/DBP/DBPHomeViewController.swift, DuckDuckGo/Tab/TabExtensions/AutofillTabExtension.swift, DuckDuckGo/Tab/UserScripts/UserScripts.swift, DuckDuckGoDBPBackgroundAgent/DataBrokerProtectionBackgroundManager.swift, LocalPackages/DataBrokerProtection/Package.swift, LocalPackages/DataBrokerProtection/Sources/DataBrokerProtection/DebugUI/DataBrokerRunCustomJSONViewModel.swift, LocalPackages/DataBrokerProtection/Sources/DataBrokerProtection/Scheduler/DataBrokerProtectionAgentManager.swift, LocalPackages/DataBrokerProtection/Tests/DataBrokerProtectionTests/Mocks.swift, LocalPackages/FeatureFlags/Package.swift, LocalPackages/NetworkProtectionMac/Package.swift, LocalPackages/SubscriptionUI/Package.swift
Task/Issue URL: https://app.asana.com/0/0/1208773745506350/f
CC:
See the Asana task for more details - but a short version is that a recent change in C-S-S requires another UUID - I deliberately DO NOT want to re-use `sessionKey`, since that's used in other places already and it would be unclear when/where we could change this.
- name: `messageSecret` was chosen to match what android already use
- where: I placed this on ContentScopePreferences because it gets serialized as JSON into our scripts and is already used for such things
- Again, it also matches Android
**Steps to test this PR**: (👀 VIDEO below)
1. Use the debug menu to set the AI Chat -> Web Communication -> Set Custom URL
- set it to `https://bridge-example.netlify.app/ai-chat.html`
3. Now …
=> [macos] adding support for message bridge

UITests/FireWindowTests.swift
Task/Issue URL: https://app.asana.com/0/1204006570077678/1208793837278290/f
CC:
The `testCrendentialsAreAutoFilledInFireWindows` failed on [macOS 15](https://github.com/duckduckgo/macos-browser/actions/runs/11905477557/job/33176330383).
Checking the logs, the problem was that there was a slight delay when the autofill credentials email is tapped and when it is loaded into the web view text field; given that we do not wait and check immediately, it could sometimes fail. 
I’ve added an expectation, so we will now wait for the email to appear.
1. Select the UI test target
2. Run the `testCrendentialsAreAutoFilledInFireWindows` test
— …
=> Add expectation when checking email text field value

DuckDuckGo/HomePage/Model/HomePageAddressBarModel.swift
Task/Issue URL: https://app.asana.com/0/1201037661562251/1208804405760977/f
This privacy config update may update a published value so must be received on main thread.
**Steps to test**:
I did the testing myself, but if you want to repeat my testing then use this config: https://www.jsonblob.com/1305205607014195200 where `ntpSearchField` is disabled and load it in the app (using `https://www.jsonblob.com/api/1305205607014195200` as custom config URL). Then update the config to say `enabled` for `ntpSearchField` and reload the configuration. Verify that you're not getting a Main Thread Checker warning.
--- …
=> Receive privacy config updates in AddressBarModel on main thread

DuckDuckGo/Common/Localizables/UserText.swift, DuckDuckGo/FileDownload/Model/DownloadListViewModel.swift, DuckDuckGo/FileDownload/Model/FileDownloadError.swift, DuckDuckGo/FileDownload/View/DownloadsViewController.swift, DuckDuckGo/Localizable.xcstrings
Task/Issue URL: https://app.asana.com/0/1204006570077678/1208780258680374/f
CC:
**AC1** 
Given a user on macOS 14.7.1 
When the user fails to download a fail with error code 256 and type NSFileReadUnknownError
Then we show an error banner with some guidance on how to update
**AC2**
Given a user on macOS 15.0.1
When the user fails to download a fail with error code 256 and type NSFileReadUnknownError
Then we show an error banner with some guidance on how to update
**Notes:**
- For the App Store version we should show a `How To Update` button that will take the user to this page: https://support.apple.com/guide/mac-help/get-macos-updates-and-apps-mh35618/mac
For Sparkle users: We will show a `Open Settings` button that it will take them to System Settings → …
=> Show error message inside downloads popup when download fails because OS issue

DuckDuckGo/UserAgent/Model/UserAgent.swift, UnitTests/UserAgent/Model/UserAgentTests.swift
Task/Issue URL: https://app.asana.com/0/1201037661562251/1208568177174606/f
CC: @jonathanKingston 
This change updates User Agent rules as follows:
* The default UA is now DDG-branded and it's applied to all web, including duckduckgo.com.
* `defaultPolicy` privacy config item is no longer supported.
* 2 types of privacy-config-provided exceptions are supported: `webViewDefault` (using WebKit default UA) and `defaultSites` (using Safari UA).
1. Open https://duckduckgo.com and verify that you see a minimal homepage (without macOS browser download CTA as seen in Safari)
2. Open [this Kibana view](https://kibana.duckduckgo.com/app/r/s/vC4ya) and [this Kibana view](https://kibana.duckduckgo.com/app/r/s/9T8ml).
3. Search on SERP for …
=> Simplify User Agent logic and update unit tests

.github/actions/asana-get-build-variants-list/get_build_variants_list.sh
Task/Issue URL: https://app.asana.com/0/1203301625297703/1208823340768320/f
CC: @alessandroboron 
This change updates get_build_variants_list.sh to report all variants.
`origin_variants` and `variants_list` are both bash arrays and when outputting them
they need to be treated in a special way to avoid outputting only the first item.
See the linked task for steps to test.
---
[Pull Request Documentation](https://app.asana.com/0/1202500774821704/120401283527748 …
=> Fix fetching variants list

.github/actions/asana-get-build-variants-list/action.yml, .github/actions/asana-get-build-variants-list/get_build_variants_list.sh, .github/workflows/build_appstore.yml, .github/workflows/build_notarized.yml, .github/workflows/create_variant.yml, .github/workflows/create_variants.yml, .github/workflows/pir_end_to_end_tests.yml, .github/workflows/pr.yml, .github/workflows/sync_end_to_end.yml, .github/workflows/sync_end_to_end_legacy_os.yml, .github/workflows/ui_tests.yml
Task/Issue URL: https://app.asana.com/0/1199230911884351/1208823340768320/f
This change adjusts the variants script to produce batches of up to 256 variants (currently 2, hardcoded)
and passes them to a (hardcoded) 2 concurrent batch tasks in the GHA workflow.
See if [this workflow](https://github.com/duckduckgo/macos-browser/actions/runs/11981343021) works.
---
=> Create variant builds in batches

LocalPackages/BuildToolPlugins/Plugins/InputFilesChecker/InputFilesChecker.swift
Task/Issue URL: https://app.asana.com/0/1201037661562251/1208822723600157/f
Fix compilation issue for Xcode 15 due to usage of `[@retroactive](https://github.com/swiftlang/swift-evolution/blob/main/proposals/0364-retroactive-conformance-warning.md#source-compatibility)` keyword.
Silence the warning by [fully qualifying the protocol name with module name](https://github.com/swiftlang/swift-evolution/blob/main/proposals/0364-retroactive-conformance-warning.md#source-compatibility). 
1. Ensure Xcode doesn’t show a warning for `extension File: Swift.Equatable, Swift.Hashable`
--- …
=> Fix an issue that cause compilation failure

DuckDuckGo/HomePage/Model/NewTabPageSearchBoxExperiment.swift, DuckDuckGo/NavigationBar/View/AddressBarTextField.swift, UnitTests/HomePage/NewTabPageSearchBoxExperimentTests.swift
Task/Issue URL: https://app.asana.com/0/72649045549333/1208836242994116/f
If the experiment is not reporting pixels anymore (past 7-day deadline), we want to keep showing
search box to the users.
Run the following commands in the command line to make yourself enrolled in the experiment 2 weeks ago:
```
defaults write com.duckduckgo.macos.browser.debug homepage.searchbox.experiment.cohort ntp_search_box_existing_user
defaults write com.duckduckgo.macos.browser.debug homepage.searchbox.experiment.enrollment-date -date "2024-11-10 16:22:28 +0000"
defaults write com.duckduckgo.macos.browser.debug homepage.searchbox.experiment.did-run-enrollment 1
```
Then run the app from Xcode and verify that the search box is present on NTP.
**Definition of …
=> Keep showing Search Box after experiment ends

DuckDuckGo/HomePage/Model/HomePageAddressBarModel.swift
Task/Issue URL: https://app.asana.com/0/72649045549333/1208746673107049/f
This change stops assigning new users to experiment, while keeping Search Box visible for users that have previously been enrolled.
Run the following commands to make yourself enrolled into the Search Box experiment:
```
defaults write com.duckduckgo.macos.browser.debug homepage.searchbox.experiment.cohort ntp_search_box_existing_user
defaults write com.duckduckgo.macos.browser.debug homepage.searchbox.experiment.enrollment-date -date "2024-11-10 16:22:28 +0000"
defaults write com.duckduckgo.macos.browser.debug homepage.searchbox.experiment.did-run-enrollment 1
```
Run the app and confirm that you see the search box.
Then call the following to reset the experiment:
``` …
```
=> Stop assigning users to NTP Search Box Experiment cohorts

package-lock.json, package.json
Task/Issue URL: https://app.asana.com/0/1208828457680750/1208828457680750
Autoconsent Release: https://github.com/duckduckgo/autoconsent/releases/tag/v12.0.0
Updates Autoconsent to version [v12.0.0](https://github.com/duckduckgo/autoconsent/releases/tag/v12.0.0).
See release notes [here](https://github.com/duckduckgo/autoconsent/blob/v12.0.0/CHANGELOG.md)
=> Update autoconsent to v12.0.0

DuckDuckGo/Tab/TabExtensions/DuckPlayerTabExtension.swift
Task/Issue URL: https://app.asana.com/0/1203249713006009/1208836976436118/f
This change limits Duck Player navigational pixels to be sent only on main frame navigations
See [this Asana comment](https://app.asana.com/0/0/1208674332470432/1208840180285935/f) for more context of the breakage.
1. Run the app from Xcode
2. Filter logs by "PixelKit" category
3. Set DuckPlayer to "always ask" mode
4. Go to youtube.com, search for video, open video page
5. Verify that refreshing doesn't trigger `navigation_back` or `navigation_outside_youtube` pixels
---
[Software Engineering Expectations](https://app.asana.com/0/59792373528535/19906486582 …
=> Only fire Duck Player navigational pixel for main frame navigations

DuckDuckGo.xcodeproj/project.pbxproj, DuckDuckGo.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved, DuckDuckGo/ContentBlocker/ContentBlocking.swift, DuckDuckGo/Statistics/GeneralPixel.swift, LocalPackages/DataBrokerProtection/Package.swift, LocalPackages/FeatureFlags/Package.swift, LocalPackages/NetworkProtectionMac/Package.swift, LocalPackages/SubscriptionUI/Package.swift
Task/Issue URL: https://app.asana.com/0/1208613456171888/1208801514911204/f
Tech Design URL: https://app.asana.com/0/1208613456171888/1208730499188670/f
CC:
1.
---
=> Adding pixels for tracking content blocking rules fetch/lookup

DuckDuckGo/Autoconsent/AutoconsentUserScript.swift, IntegrationTests/PhishingDetection/PhishingDetectionIntegrationTests.swift, UnitTests/Autoconsent/AutoconsentMessageProtocolTests.swift
Task/Issue URL: https://app.asana.com/0/72649045549333/1208825971888846/f
Tech Design URL: https://app.asana.com/0/1201844467387842/1208738659527990/f
CC:
- Make sure to show the CPM animation when cosmetic filterlist rules match.
- This means that you will see "Cookie Hidden" animation if filterlist cosmetic rule hides something, but might see another one if an active rule matches later.
- This is dependent on [CPM changes](https://github.com/duckduckgo/autoconsent/pull/538), so when testing, please use this branch: `max/autoconsent-filterlist-animation-review`, or the test build in the [Ship Review](https://app.asana.com/0/72649045549333/1208825971888846/f).
Check this to run the Personal Information Removal end to end tests. If updating CCF, or …
=> Trigger the Cookie Hidden animation early for filterlist rules

package-lock.json, package.json
Task/Issue URL: https://app.asana.com/0/1208870472966969/1208870472966969
Autoconsent Release: https://github.com/duckduckgo/autoconsent/releases/tag/v12.1.0
Updates Autoconsent to version [v12.1.0](https://github.com/duckduckgo/autoconsent/releases/tag/v12.1.0).
See release notes [here](https://github.com/duckduckgo/autoconsent/blob/v12.1.0/CHANGELOG.md)
=> Update autoconsent to v12.1.0

DuckDuckGo.xcodeproj/project.pbxproj, DuckDuckGo.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved, LocalPackages/DataBrokerProtection/Package.swift, LocalPackages/FeatureFlags/Package.swift, LocalPackages/NetworkProtectionMac/Package.swift, LocalPackages/SubscriptionUI/Package.swift
Task/Issue URL: https://app.asana.com/0/1206488453854252/1208904081551825/f
**Description**: Bump BSK for missing Freemium RMF attribute
1. Change the RMF debug URL in `RemoteMessageClient` to `https://www.jsonblob.com/api/1313918156242345984`
2. In `RemoteMessagingConfigMatcherProvider` at line 168, pass in `true` for `isCurrentFreemiumPIRUser`
3. Run the app
4. Ensure you see a RMF message on the new tab page with a button that says "freemium"
--- …
=> Add Missing Enum to Freemium RMF Implementation

package-lock.json, package.json
Task/Issue URL: https://app.asana.com/0/1208921167946091/1208921167946091
Autoconsent Release: https://github.com/duckduckgo/autoconsent/releases/tag/v12.2.0
Updates Autoconsent to version [v12.2.0](https://github.com/duckduckgo/autoconsent/releases/tag/v12.2.0).
See release notes [here](https://github.com/duckduckgo/autoconsent/blob/v12.2.0/CHANGELOG.md)
=> Update autoconsent to v12.2.0

DuckDuckGo/BookmarksBar/View/BookmarksBarMenuPopover.swift
Task/Issue URL: https://app.asana.com/0/1201048563534612/1208882942353448/f
- fixes an endless loop
1. Create Folder -> Folder 1 -> Folder 2  in the Bookmarks Bar
2. Right click Folder 2 and choose Edit
3. Validate edit works fine and popovers stays on screen while editing
---
[Pull Request …
=> Fix endless loop when editing nested bookmarks bar item

UnitTests/Sync/SyncPreferencesTests.swift, UnitTests/TabBar/ViewModel/TabLazyLoaderTests.swift
Task/Issue URL: https://app.asana.com/0/1199230911884351/1208926119997580/f
CC:
This is an experimental change to improve some CI reliability, after successfully reproducing failures locally and then applying this fix to resolve them. So far, I haven't seen another failure locally after a half dozen runs, whereas before I could reproduce this almost every time.
--- …
=> Improve tab lazy loading test reliability

DuckDuckGo.xcodeproj/project.pbxproj, UnitTests/TabBar/ViewModel/TabLazyLoaderTests.swift
Task/Issue URL: https://app.asana.com/0/0/1208934054688674/f
This change updates TabLazyLoaderTests to use structured concurrency in place of DispatchQueue.main.async calls.
1. Verify that CI doesn't fail on "Build and run unit tests" step.
---
=> Fix flaky TabLazyLoaderTests

DuckDuckGo.xcodeproj/project.pbxproj, DuckDuckGo.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved, DuckDuckGo/Sync/SyncCredentialsAdapter.swift
Task/Issue URL:
CC:
1. Confirm CI is green
---
=> iOS QuickType support update

IntegrationTests/MaliciousSiteProtection/MaliciousSiteProtectionIntegrationTests.swift, UnitTests/Sync/SyncPreferencesTests.swift
This allows us to still detect failures when the suite doesn't time out.
Task/Issue URL: https://app.asana.com/0/1199230911884351/1208926848453614/f
CC:
This PR updates the malicious site tests to ignore time outs. These tests rely on an outside dependency which is not reliably loading; rather than disable them entirely, let's run them as expected in cases where the timeout doesn't occur.
1. Check that the CI runs do not show any failures related to this test suite
--- …
=> Ignore timeouts in the malicious site test suite

DuckDuckGo/HomePage/Model/HomePageAddressBarModel.swift
Task/Issue URL: https://app.asana.com/0/72649045549333/1208746673107049/f
This change stops assigning new users to experiment, while keeping Search Box visible for users that have previously been enrolled.
Run the following commands to make yourself enrolled into the Search Box experiment:
```
defaults write com.duckduckgo.macos.browser.debug homepage.searchbox.experiment.cohort ntp_search_box_existing_user
defaults write com.duckduckgo.macos.browser.debug homepage.searchbox.experiment.enrollment-date -date "2024-11-10 16:22:28 +0000"
defaults write com.duckduckgo.macos.browser.debug homepage.searchbox.experiment.did-run-enrollment 1
```
Run the app and confirm that you see the search box.
Then call the following to reset the experiment:
``` …
```
=> Stop assigning users to Search Box experiment cohorts

LocalPackages/Utilities/Package.swift
Task/Issue URL: https://app.asana.com/0/1201037661562251/1208943111717449/f
This change fixes UI tests compilation on macOS 13 and 14
Verify that UI tests compile on all macOS versions and that [this Sync E2E tests run](https://github.com/duckduckgo/macos-browser/actions/runs/12251427646) passes.
---
=> Set swift-tools-version for Utilities package to 5.9

clean-app.sh
Task/Issue URL: https://app.asana.com/0/1201037661562251/1208943073994046/f
- Include `~/Library/Group\ Containers/*.com.duckduckgo.macos.browser.app-configuration.debug/*` path to clear by the `./clean-app.sh` script
1. Validate downloaded configs directory is cleared by the script for both DMG and AppStore builds
---
[Technical Design Template](https://app.asana.com/0/59792373528535/1847099713119 …
=> include config dir clearance in clean-app script

DuckDuckGo.xcodeproj/project.pbxproj, DuckDuckGo.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved, LocalPackages/DataBrokerProtection/Package.swift, LocalPackages/FeatureFlags/Package.swift, LocalPackages/NetworkProtectionMac/Package.swift, LocalPackages/NewTabPage/Package.swift, LocalPackages/SubscriptionUI/Package.swift, LocalPackages/SubscriptionUI/Sources/SubscriptionUI/DebugMenu/DebugPurchaseViewController.swift, LocalPackages/WebKitExtensions/Package.swift
Task/Issue URL: https://app.asana.com/0/1208114992212396/1208796999534221/f
Tech Design URL: https://app.asana.com/0/481882893211075/1208773437150501/f
**Description**: Includes the following changes:
* Bumps BSK which includes changes [here]. (https://github.com/duckduckgo/BrowserServicesKit/pull/1120)
* Also forces casts `SubscriptionProduct` type to `Product` type, but only in debug menu code
1. Launch from Xcode
2. Purchase a Privacy Pro Subscription via App Store and Staging
3. Ensure purchase succeeds
**Definition of Done (Internal Only)**:
---
?
--- …
=> Privacy Pro Free Trials - Models and API

DuckDuckGo.xcodeproj/project.pbxproj, DuckDuckGo/Application/AppDelegate.swift, DuckDuckGo/NewTabPage/ContinueSetUpModel+NewTabPage.swift, DuckDuckGo/NewTabPage/NewTabPageActionsManagerExtension.swift, DuckDuckGo/NewTabPage/NewTabPageNextStepsCardsProvider.swift, DuckDuckGo/NewTabPage/NewTabPagePrivacyStatsEventHandler.swift, DuckDuckGo/PrivacyStats/PrivacyStatsDatabase.swift, DuckDuckGo/PrivacyStats/PrivacyStatsErrorHandler.swift, DuckDuckGo/Statistics/GeneralPixel.swift, DuckDuckGo/Statistics/NewTabPagePixel.swift, LocalPackages/NewTabPage/Sources/NewTabPage/NextStepsCards/NewTabPageNextStepsCardsClient.swift, LocalPackages/NewTabPage/Sources/NewTabPage/NextStepsCards/NewTabPageNextStepsCardsProviding.swift, LocalPackages/NewTabPage/Sources/NewTabPage/PrivacyStats/NewTabPagePrivacyStatsClient.swift, LocalPackages/NewTabPage/Sources/NewTabPage/PrivacyStats/NewTabPagePrivacyStatsModel.swift, LocalPackages/NewTabPage/Tests/NewTabPageTests/Mocks/CapturingNewTabPagePrivacyStatsEventHandler.swift, LocalPackages/NewTabPage/Tests/NewTabPageTests/NewTabPageNextStepsCardsClientTests.swift, LocalPackages/NewTabPage/Tests/NewTabPageTests/NewTabPagePrivacyStatsClientTests.swift, LocalPackages/NewTabPage/Tests/NewTabPageTests/NewTabPagePrivacyStatsModelTests.swift, UnitTests/NewTabPage/NewTabPageNextStepsCardsProviderTests.swift
Task/Issue URL: https://app.asana.com/0/69071770703008/1208936504720914/f
**Description:**
This change adds 2 new messages to track actions in the Privacy Stats widget
and implements usage and debug pixels for Privacy Stats.
1. Run the app from Xcode, set internal user state and set htmlNewTabPage feature flag.
2. Filter Xcode console by "PixelKit" subsystem.
3. Visit some websites to have Privacy Stats widget populated.
4. Click "Show More" and then "Show Less" and verify the following output in the console:
```
👾[Daily and Count-Fired] m_mac_new-tab-page_blocked-tracking-attempts_show-more_daily ["appVersion": "1.118.0", "pixelSource": "browser-dmg"]
👾[Daily and Count-Fired] m_mac_new-tab-page_blocked-tracking-attempts_show-more_count ["appVersion": "1.118.0", …
```
=> Add pixels for Privacy Stats on HTML NTP

DuckDuckGo.xcodeproj/project.pbxproj
Task/Issue URL: https://app.asana.com/0/1201037661562251/1208963146868222/f
This is to maintain compatibility with old Xcode versions to run UI tests.
Verify that CI is green, including [this UI tests run](https://github.com/duckduckgo/macos-browser/actions/runs/12291783189).
---
=> Replace NewTabPage tests folder reference with an Xcode file group

DuckDuckGo.xcodeproj/project.pbxproj, DuckDuckGo.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved, LocalPackages/DataBrokerProtection/Package.swift, LocalPackages/FeatureFlags/Package.swift, LocalPackages/NetworkProtectionMac/Package.swift, LocalPackages/NewTabPage/Package.swift, LocalPackages/SubscriptionUI/Package.swift, LocalPackages/WebKitExtensions/Package.swift
Task/Issue URL: https://app.asana.com/0/414709148257752/1208827075841585/f
Add the "locale" param ID to the list of properties submitted in the Privacy Dashboard site breakage form.
To force report broken site form to be shown every time you can change https://github.com/duckduckgo/BrowserServicesKit/blob/b7f7ba99f7c77b576679eee426ddd80320dc74d8/Sources/PrivacyDashboard/ToggleReportingManager.swift#L104 to always return `true`
1. Open some website.
2. Wait until it completes loading.
3. Open Privacy Dashboard
4. Disable the protections
5. When the report broken site prompt is shown select "See what's sent"
6. Ensure the "Primary language and country of your device" string is shown
--- …
=> Add 'locale' to report broken site params

DuckDuckGo.xcodeproj/project.pbxproj, DuckDuckGo.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved, LocalPackages/DataBrokerProtection/Package.swift, LocalPackages/FeatureFlags/Package.swift, LocalPackages/NetworkProtectionMac/Package.swift, LocalPackages/NewTabPage/Package.swift, LocalPackages/SubscriptionUI/Package.swift, LocalPackages/WebKitExtensions/Package.swift
Task/Issue URL: https://app.asana.com/0/414235014887631/1208827075841585/f
`Add 'locale' to report broken site params` was merged in to https://github.com/duckduckgo/macos-browser/tree/release/1.118.0 in a BSK hotfix release. This PR updates BSK to latest to introduce this change on main.
Make sure the app builds without errors.
---
=> Update BSK to latest

DuckDuckGo/HomePage/View/HomePageSettings/BackgroundCategoryView.swift, DuckDuckGo/HomePage/View/HomePageSettings/BackgroundThumbnailView.swift
Task/Issue URL: https://app.asana.com/0/1201621708115095/1208921971523524/f
This change fixes layout of BackgroundCategoryView to correctly align multi-line title labels with other grid items.
1. Set app language to Italian
2. Run the app from Xcode
3. Open Customize panel in NTP
4. Verify that background categories grid is aligned correctly.
---
=> Fix displaying multi-line custom background category names

DuckDuckGo/Statistics/Experiment/PixelExperiment.swift, DuckDuckGo/Tab/Model/Tab.swift
Task/Issue URL: https://app.asana.com/0/0/1208965309086157/f
**Description**: We want to disable the contextual onboarding while leaving the rest of the treatment variant
1. Run ./clean-app.sh debug
2. In MainWindowController in shouldShowOnboarding leave only line 87 and 88
3. Run the app (repeat the above steps until you get the new onboarding)
4. go through the onboarding and at the end check that no contextual dialog is present.
<!—
If this PR isn't ready to be merged for whatever reason it should be marked with the `DO NOT MERGE` label (particularly if it's a draft)
If it's pending Product …
=> disable contextual onboarding

package-lock.json, package.json
Task/Issue URL: https://app.asana.com/0/1208976603817275/1208976603817275
Autoconsent Release: https://github.com/duckduckgo/autoconsent/releases/tag/v12.3.0
Updates Autoconsent to version [v12.3.0](https://github.com/duckduckgo/autoconsent/releases/tag/v12.3.0).
See release notes [here](https://github.com/duckduckgo/autoconsent/blob/v12.3.0/CHANGELOG.md)
=> Update autoconsent to v12.3.0

DuckDuckGo/DataImport/View/FileImportView.swift, DuckDuckGo/Localizable.xcstrings
Task/Issue URL: https://app.asana.com/0/1201462886803403/1208921574824172/f
CC:
Update copy on the passwords data import flow in line with latest Safari updates from macOS 15.2
1. Assuming you can’t easily toggle between macOS versions, feel free to tweak the `if #available(macOS 15.2, *) {` to a version that makes sense for your environment (it won’t affect the test steps which are just copy updates0
2. Set up so that your macOS version and the `if #available` check match
3. Start the Safari import data flow and confirm the copy on the Passwords import prompt matches the final copy from this task description: https://app.asana.com/0/38424471409662/1208966807789111/f
4. Now set up so your macOS version is lower than the`if …
=> Updated Safari import passwords instructions for macOS 15.2

.github/workflows/pir_end_to_end_tests.yml, .github/workflows/sync_end_to_end.yml, .github/workflows/ui_tests.yml
Task/Issue URL: https://app.asana.com/0/1201037661562251/1209021750286613/f
**Description**: We have bumped CI to Xcode 16.2 as per [here](https://github.com/duckduckgo/macos-browser/pull/3677). This PR bumps workflows to address failing PIR and UI tests.
1. Green CI
---
[Pull Request …
=> Bump workflows to Xcode 16.2

package-lock.json, package.json
Task/Issue URL: https://app.asana.com/0/1209022585506298/1209022585506298
Autoconsent Release: https://github.com/duckduckgo/autoconsent/releases/tag/v12.4.0
Updates Autoconsent to version [v12.4.0](https://github.com/duckduckgo/autoconsent/releases/tag/v12.4.0).
See release notes [here](https://github.com/duckduckgo/autoconsent/blob/v12.4.0/CHANGELOG.md)
=> Update autoconsent to v12.4.0

DuckDuckGo/Preferences/View/PreferencesAboutView.swift
Task/Issue URL: https://app.asana.com/0/1201037661562251/1209057693918519/f
CC:
Fixes Preferences About screen not accepting inputs
1. Open the About screen
2. You should be able to interact with the checkboxes, buttons, and links on the screen
---
[Pull Request …
=> Fix frozen Preferences About screen 

DuckDuckGo/Preferences/View/PreferencesAboutView.swift
Task/Issue URL: https://app.asana.com/0/1199230911884351/1209057693918519/f
CC:
Bug fix targeting release branch.
1.
---
=> Fix Preferences About screen doesn't recognize inputs

DuckDuckGo/NavigationBar/View/MoreOptionsMenu.swift, DuckDuckGo/Updates/ReleaseNotesTabExtension.swift, DuckDuckGo/Updates/ReleaseNotesUserScript.swift, DuckDuckGo/Updates/UpdateController.swift, DuckDuckGo/Updates/UpdateNotificationPresenter.swift, DuckDuckGo/Updates/UpdateUserDriver.swift
Task/Issue URL: https://app.asana.com/0/1201048563534612/1209026627874986/f
CC:
Addresses some updater feedback:
- "Install Now" menu item does nothing
- Incorrect Release Notes screen state
Also adds more logging to help track down the edge cases (non-producible on my machine, but some internal users kept running into them) 
1. Download this test build: https://staticcdn.duckduckgo.com/macos-desktop-browser/a81f9679-e41d-404d-81a6-fd4a461d82f7/testbuilds/5ab32a1/duckduckgo-1.120.0.333.dmg
2. Try different scenarios; use this as reference: …
=> Address updater feedback

DuckDuckGo.xcodeproj/project.pbxproj, DuckDuckGo.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved, LocalPackages/DataBrokerProtection/Package.swift, LocalPackages/FeatureFlags/Package.swift, LocalPackages/NetworkProtectionMac/Package.swift, LocalPackages/NewTabPage/Package.swift, LocalPackages/SubscriptionUI/Package.swift, LocalPackages/WebKitExtensions/Package.swift
Task/Issue URL: https://app.asana.com/0/0/1209105499479210/f
This change exposes htmlNewTabPage feature flag in the Privacy Config.
It's not yet handled by the macOS app - this will be updated in a follow-up change.
---
[Pull Request …
=> Add HTML New Tab Page Privacy Config feature for macOS

DuckDuckGo/Tab/Model/Tab.swift
Task/Issue URL: https://app.asana.com/0/0/1209114783599171/f
**Description**: Will limit the onboarding experiment to macOS version from 13 and above. This is only temporary until we merge the new C-S-S version containing the fixed FE app.
1. on MainWindowController make shouldShowOnboarding return true and make a review build
2. launch the app a few times on macOS >= 13 and check you can see both onboarding
3. launch the app a few times on macOS < 13 and check you always see the old onboarding
<!—
If this PR isn't ready to be merged for whatever reason it should be marked with the `DO NOT MERGE` …
=> restrict new onboarding to macOS 13 and above

DuckDuckGo/HomePage/View/HomePageViewController.swift, DuckDuckGo/Statistics/GeneralPixel.swift
Task/Issue URL: https://app.asana.com/0/0/1209119352060519/f
This change adds a pixel that is fired whenever a user activates any history link in the Privacy Feed.
1. Run the app from Xcode and make sure you're using the native NTP
2. Accrue some browsing history
3. Click links in Privacy Feed and verify that `m_mac_privacy_feed_history_link_opened_daily` and `m_mac_privacy_feed_history_link_opened_count` are being fired.
---
[Pull Request …
=> Add privacyFeedHistoryLinkOpened pixel

LocalPackages/DataBrokerProtection/Sources/DataBrokerProtection/UI/UIMapper.swift, LocalPackages/DataBrokerProtection/Tests/DataBrokerProtectionTests/MapperToUITests.swift
Task/Issue URL: https://app.asana.com/0/1203581873609357/1209044506846805/f
CC:
UI doesn't update (stuck at Next scan: XXX). Scans still run behind the scene but the UI doesn't reflect that status. This seems to be related to the way `currentScans` is calculated. The logic was updated when we introduced `scannedBrokers`
1. Run a PIR scan
2. Once it finishes, update the profile by either adding/removing name or changing the DoB
3. UI should show Scan in progress
--- …
=> Fix updating profile not triggering UI updates

package-lock.json, package.json
Task/Issue URL: https://app.asana.com/0/1209123933422266/1209123933422266
Autoconsent Release: https://github.com/duckduckgo/autoconsent/releases/tag/v12.5.0
Updates Autoconsent to version [v12.5.0](https://github.com/duckduckgo/autoconsent/releases/tag/v12.5.0).
See release notes [here](https://github.com/duckduckgo/autoconsent/blob/v12.5.0/CHANGELOG.md)
=> Update autoconsent to v12.5.0

DuckDuckGo/Common/Extensions/WKWebViewExtension.swift
Task/Issue URL: https://app.asana.com/0/1202406491309510/1209123691403049/f
- Fixes crash on assertion on DEBUG build launch without debugger attached by updating the `valueForUndefinedKey:` implementation to match https://github.com/WebKit/WebKit/blob/905c9c9c56c44bdc41639300233ff28b658eec29/Source/WebKit/UIProcess/API/Cocoa/WKWebView.mm#L790
1. Build in DEBUG mode
2. Launch the DEBUG app from Finder
3. Validate the app doesn‘t crash
---
[Pull Request …
=> fix crash on launch in WKWebView.valueForUndefinedKey(serverTrust)

DuckDuckGo.xcodeproj/project.pbxproj, DuckDuckGo.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved, LocalPackages/DataBrokerProtection/Package.swift, LocalPackages/FeatureFlags/Package.swift, LocalPackages/NetworkProtectionMac/Package.swift, LocalPackages/NewTabPage/Package.swift, LocalPackages/SubscriptionUI/Package.swift, LocalPackages/WebKitExtensions/Package.swift
Task/Issue URL: https://app.asana.com/0/1199333091098016/1209143709072898/f
CC:
This PR updates the BSK `Crashes` module to correctly include relevant dependencies.
2. Check that the app builds and doesn't show you a warning about Crashes/Persistence
---
[Pull Request …
=> Add `Persistence` dependency to `Crashes` module

DuckDuckGo/Tab/Navigation/DuckURLSchemeHandler.swift
Task/Issue URL:  https://app.asana.com/0/1204099484721401/1209111326156032/f
CC:
- Fixes issue causing DuckPlayer to render the same (incorrect) video
1. Go to Settings > DuckPlayer, Check “Always open videos in DuckPlayer"
2. Go to Settings > DuckPlayer, UNCheck “Open DuckPlayer videos in a new tab whenever possible”
3. Go to https://www.youtube.com/@mkbhd
4. Click on a video
5. Confirm it opens in Duck Player
6. Hit ‘back'
7. Click another video
8. Confirm it opens in Duck Player (Previously, the old video was opening)  …
=> Fix Duckplayer handler URL

DuckDuckGo/Tab/Model/Tab.swift
Task/Issue URL: https://app.asana.com/0/0/1209153206410271/f
**Description**: Re-enable new onboarding on old mac-OS version after fix is available on C-S-S
1. on MainWindowController make shouldShowOnboarding return true and make a review build
2. launch the app a few times on macOS >= 13 and check you can see both onboarding
3. launch the app a few times on macOS < 13 and check you can see both onboarding
--- …
=> re-enabled new onboarding for old macOS versions

DuckDuckGo.xcodeproj/project.pbxproj, DuckDuckGo.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved, LocalPackages/DataBrokerProtection/Package.swift, LocalPackages/FeatureFlags/Package.swift, LocalPackages/FeatureFlags/Sources/FeatureFlags/FeatureFlag.swift, LocalPackages/NetworkProtectionMac/Package.swift, LocalPackages/NewTabPage/Package.swift, LocalPackages/SubscriptionUI/Package.swift, LocalPackages/WebKitExtensions/Package.swift
Task/Issue URL: https://app.asana.com/0/1203108348835387/1209150117333883/f
iOS PR: https://github.com/duckduckgo/iOS/pull/3808
BSK PR: https://github.com/duckduckgo/BrowserServicesKit/pull/1164
Adds the VPN App Exclusions remote feature-flag with support for overriding locally. 
1. Launch the App
2. Make sure you see a Debug menu Feature Flag Override option for `networkProtectionAppExclusions`.  It should be ON by default as shown here.
---
[Pull Request …
=> Add VPN App Exclusions remote feature-flag

DuckDuckGo.xcodeproj/project.pbxproj, DuckDuckGo.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved, LocalPackages/DataBrokerProtection/Package.swift, LocalPackages/FeatureFlags/Package.swift, LocalPackages/NetworkProtectionMac/Package.swift, LocalPackages/NewTabPage/Package.swift, LocalPackages/SubscriptionUI/Package.swift, LocalPackages/WebKitExtensions/Package.swift
Task/Issue URL: https://app.asana.com/0/72649045549333/1209009315184468/f
Previously, default Privacy Pro links were sent to `/subscriptions/welcome`, and the frontend redirected to `/subscriptions`.
Currently, this will still result in a redirect to `/subscriptions/welcome` for subscribed users—effectively a no-op. After an upcoming frontend release, this will show `/subscriptions` with a link to `/subscriptions/welcome`.
1. TBD
---
=> BSK Bump - Defaults internal Privacy Pro links to /subscriptions

package-lock.json, package.json
Task/Issue URL: https://app.asana.com/0/1209184566247348/1209184566247348
Autoconsent Release: https://github.com/duckduckgo/autoconsent/releases/tag/v12.6.0
Updates Autoconsent to version [v12.6.0](https://github.com/duckduckgo/autoconsent/releases/tag/v12.6.0).
See release notes [here](https://github.com/duckduckgo/autoconsent/blob/v12.6.0/CHANGELOG.md)
=> Update autoconsent to v12.6.0

DuckDuckGo.xcodeproj/xcshareddata/xcschemes/DuckDuckGo Privacy Browser App Store.xcscheme, DuckDuckGo.xcodeproj/xcshareddata/xcschemes/DuckDuckGo Privacy Browser.xcscheme, UITests/StateRestorationTests.swift
Task/Issue URL: https://app.asana.com/0/1202406491309510/1209193663115526/f
- fix failing test due to session state data not getting to record due to force termination
1. Validate `test_tabStateAtRelaunch_shouldContainTwoSitesVisitedInPreviousSession_whenReopenAllWindowsFromLastSessionIsSet` passes
---
=> fix session restoration ui test

DuckDuckGo/NetworkProtection/AppTargets/BothAppTargets/NetworkProtectionTunnelController.swift
Task/Issue URL: https://app.asana.com/0/1207603085593419/1209205827151436/f
The `DataVolumeObserver` is reloading all VPN configurations each second.  This is bad because it forces status updates on all observers each second.
1. Make sure you can start / stop the VPN
2. Make sure you can re-create the VPN configuration after manually removing it from System Settings
3. Make sure the data volume is shown correctly
---
[Pull Request Documentation](https://app.asana.com/0/1202500774821704/1204012835277482 …
=> Fixes an issue with the data volume in the VPN

DuckDuckGo/FileDownload/Model/DownloadListViewModel.swift
Task/Issue URL: https://app.asana.com/0/1201048563534612/1209214065492973/f
CC:
Updates the targeting macOS versions for the error prompt to include all 14.7.x versions.
---
=> Update download error prompt targeted versions

DuckDuckGo/Application/AppDelegate.swift, DuckDuckGo/CrashReports/Model/CrashReporter.swift, DuckDuckGo/Statistics/GeneralPixel.swift
Task/Issue URL: https://app.asana.com/0/414235014887631/1208908529122511/f
CC:
This PR adds a daily crash pixel. This pixel was already triaged in December, but I lost track of it over the break.
1. Go to `CrashReporter.swift` and comment out the `if !DEBUG` line so that the crash reporting check runs when debugging
2. Run the app
3. Now, quit the app and open it outside of Xcode - you should be able to find it in the `Applications/DEBUG` directory
4. Use the debug menu to crash it
5. Finally, launch the app via Xcode so that the app has a crash report to pick up, and check that the …
=> Daily crash pixel

DuckDuckGo-macOS.xcodeproj/project.pbxproj, DuckDuckGo-macOS.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved, LocalPackages/DataBrokerProtection/Package.swift, LocalPackages/FeatureFlags/Package.swift, LocalPackages/HistoryView/Package.swift, LocalPackages/NetworkProtectionMac/Package.swift, LocalPackages/NewTabPage/Package.swift, LocalPackages/SubscriptionUI/Package.swift, LocalPackages/UserScriptActionsManager/Package.swift, LocalPackages/WebKitExtensions/Package.swift
Task/Issue URL: https://app.asana.com/0/1202926619870900/1209014391063056/f
As part of [✓ Send pixels for account removal + decoding issues](https://app.asana.com/0/1199230911884351/1208723035104886/f), pixels were added indicating what the reason for the Sync account being removed from the Keychain was.
However, the pixel `sync_account_removed_reason_not-set-on-key-value-store` is being sent even when there was no account stored in the keychain in the first place. This could be obscuring a problem.
To make this Pixel more useful, we should update it so that it's only sent when there was an account stored in the keychain.
Hard to test the pixel itself as reporting on a broken state, but just do a quick smoke test of Sync on both platforms. …
=> Sync: Fire accountRemoved KV store reason when no account

LocalPackages/FeatureFlags/Sources/FeatureFlags/FeatureFlag.swift
Task/Issue URL: https://app.asana.com/0/1207603085593419/1209262365365751/f
Releases Tips and the TunnelVision fix for macOS
Between tests, please remove the VPN configuration as keeping an existing one might cause `enforceRoutes` not to be properly set.
Also please note you can fake TunnelVision for testing purposes locally using these commands:
- Enable TunnelVision exploit: `sudo route -n add 34.160.111.145 192.168.0.1` (`sudo route -n <ifconfig.me_ip> <local_gateway>`)
- Disable TunnelVision exploit: `sudo route -n delete 34.160.111.145 192.168.0.1`
1. Remove internal user state using the debug menu
2. Remove the VPN configuration from System Settings
3. Enable TunnelVision exploit
4. Start the VPN
5. Open: `ifconfig.me` using the browser and check that the IP is the private one.
6. …
=> Fix an issue that caused VPN Tips and the TunnelVision-fix not to be publicly available

DuckDuckGo/Application/AppDelegate.swift
Task/Issue URL: https://app.asana.com/0/72649045549333/1209268316380789/f
This change updates how we pass OS version in Pixel requests, as agreed in the [Privacy Triage](https://app.asana.com/0/69071770703008/1209176655620013).
1. Update AppDelegate.swift:657 (`PixelKit.setUp`) and set `dryRun` to `false`.
2. Set a breakpoint in AppDelegate.swift:668 (`request.fetch`) and run the app.
3. When stopped at the breakpoint, inspect `request` and verify that the User Agent header only contains OS version without the patch component.
--- …
=> Strip patch component from the OS version in Pixel requests User Agent

DuckDuckGo/Tab/Model/Tab.swift
Task/Issue URL: https://app.asana.com/0/0/1209290104647426/f
This change adds WKTerminationReason code as underlying error code to webkit termination pixel.
1. Go to Tab.swift and add `webContentProcessDidTerminate(with: .exceededCPULimit)` at the end of init method.
2. Launch the app and verify that `m_mac_debug_webkit_did_terminate` pixel was sent with `"ue": "1"`.
--- …
=> Add termination reason as underlying error code for webkit termination pixel

LocalPackages/DataBrokerProtection/Sources/DataBrokerProtection/Model/Actions/Click.swift, LocalPackages/DataBrokerProtection/Sources/DataBrokerProtection/Model/PageElement.swift, LocalPackages/DataBrokerProtection/Tests/DataBrokerProtectionTests/DataBrokerOperationActionTests.swift
Task/Issue URL: https://app.asana.com/0/72649045549333/1209274402556158/f
CC:
Add a “failSilently” directive to click actions to allow them to fail without throwing an error.
1. Run tests
2. Edit an existing broker JSON, changing the selector of a click action to something nonsensical, then run it and see the error pop up.
3. No add `failSilently` to the element where you changed the selector and run it again. This action should not error out.
— …
=> Add the ability to click actions to fail silently

DuckDuckGo/Application/AppDelegate.swift, DuckDuckGo/Statistics/GeneralPixel.swift
Task/Issue URL: https://app.asana.com/0/1204006570077678/1209270803592942/f
CC:
Replace `ml_mac_app-launch_as-default` and `ml_mac_app-launch_as-nondefault` with a new pixel that will have two parameters for ATT (Add to Taskbar/Dock) and SAD (Set As Default).
The new pixel will be fired daily, with a `default_browser` and a `dock` parameter.
1. Run the application
2. Filter the console by the pixel name `m_mac_daily_active_user_d`, check that is being fired
3. Set the debug build as default browser and add it to dock
4. Launchthe app again
5. Both SAD and ATT parameters should be “1”.
— …
=> Implement new launch pixel with ATT and SAD

.github/workflows/macos_pr_task_url.yml
Task/Issue URL: https://app.asana.com/0/1203301625297703/1209311684037783
Verify that this task is properly added to App Board by automation.
---
=> Remove trailing whitespace from task URL in PR Task URL workflow

DuckDuckGo-macOS.xcodeproj/project.pbxproj, DuckDuckGo/NewTabPage/Features/NewTabPageConfigurationErrorHandler.swift, DuckDuckGo/NewTabPage/Features/RecentActivityProvider.swift, DuckDuckGo/NewTabPage/NewTabPageActionsManagerExtension.swift, DuckDuckGo/Statistics/NewTabPagePixel.swift, LocalPackages/NewTabPage/Sources/NewTabPage/Configuration/NewTabPageConfigurationClient.swift, LocalPackages/NewTabPage/Sources/NewTabPage/Configuration/NewTabPageDataModel+Configuration.swift, LocalPackages/NewTabPage/Tests/NewTabPageTests/Mocks/CapturingNewTabPageConfigurationErrorHandler.swift, LocalPackages/NewTabPage/Tests/NewTabPageTests/NewTabPageConfigurationClientTests.swift, UITests/BookmarksAndFavoritesTests.swift, UITests/UI Tests.xctestplan, UnitTests/NewTabPage/RecentActivityProviderTests.swift
Task/Issue URL: https://app.asana.com/0/1201091620985789/1209319157623402
This change adds a pixel for New Tab Page exceptions and also fixes counting blocked trackers
in Recent Activity widget on the NTP.
1. Launch the app and visit a few websites from the same domain.
2. Open NTP and check the number of blocked trackers.
3. Switch back to native NTP (using _Main Menu -> Debug -> Feature Flag Overrides -> htmlNewTabPage_)
4. Verify that the number of blocked trackers reported by Recent Activity widget is the same on native NTP as on HTML NTP. Note that it's OK if different tracker companies icons are shown on the two, as NTP implementation is broken :)
Testing the pixel is quite tricky, and I've tested it, so that you don't have to:
1. Check …
=> Fix counting blocked trackers and add pixel for reporting NTP exceptions

DuckDuckGo/NetworkProtection/AppTargets/BothAppTargets/NetworkProtectionTunnelController.swift
Task/Issue URL: https://app.asana.com/0/1207603085593419/1209318940389812
Hotfixes a VPN issue introduces in 1.124.0 that caused the connection to be lost
1. If you're running a debug build comment out [this line](https://github.com/duckduckgo/macos-browser/blob/8936e03b6df8a945e0e4004f3b5a019d1158226a/DuckDuckGoVPN/VPNAppEventsHandler.swift#L45).  If you're using a release build to test, you're good.
2. Start the VPN.
3. Close DDG
4. Reopen DDG.
5. Make sure the VPN isn't stopped and the proper connection status is reported.
--- …
=> Hotfixes a VPN issue introduces in 1.124.0 that caused the connection to be lost

DuckDuckGo/Tab/Model/Tab.swift
Task/Issue URL: https://app.asana.com/0/69071770703008/1209322185454642
This change introduces a daily pixel for WebKit terminations (alongside
the existing standard pixel reported for every tab crash).
1. Add the following line in Tab.swift line 305 (at the end of the initializer):
```
webContentProcessDidTerminate(with: .exceededCPULimit)
```
2. Run the app and verify in the logs that both `m_mac_debug_webkit_did_terminate` and `m_mac_debug_webkit_did_terminate_daily` pixels were fired.
--- …
=> Add daily pixel for WebKit terminations

DuckDuckGo/HomePage/View/HomePageViewController.swift, DuckDuckGo/NewTabPage/Features/DefaultRecentActivityActionsHandler.swift, DuckDuckGo/Statistics/GeneralPixel.swift, DuckDuckGo/Statistics/NewTabPagePixel.swift
Task/Issue URL: https://app.asana.com/0/72649045549333/1209326060139784
1. Run the app from Xcode and filter logs by PixelKit subsystem
2. Visit a website so that privacy feed on NTP is populated
3. Click any link on the privacy feed.
4. Verify that `m_mac_privacy_feed_history_link_opened_daily` and `m_mac_privacy_feed_history_link_opened_count`  pixels are logged.
---
=> Fire privacyFeedHistoryLinkOpened pixel from HTML NTP

DuckDuckGo-macOS.xcodeproj/project.pbxproj, DuckDuckGo/History/Services/HistoryGroupingProvider.swift, DuckDuckGo/Menus/CleanThisHistoryMenuItem.swift, DuckDuckGo/Menus/HistoryMenu.swift, DuckDuckGo/Menus/MainMenuActions.swift, UnitTests/History/Services/HistoryGroupingProviderTests.swift
Task/Issue URL: https://app.asana.com/0/0/1209328755192084/f
This change updates History Menu to only display one item per URL per day,
which is in line with other mainstream browsers. This change remains behind historyView
feature flag and will only be made available when Full History View is released.
The grouping logic was extracted into HistoryGroupingProvider class where
it's made dependent on the feature flag state. Current behavior remains unchanged,
as evidenced by added unit tests.
1. Run the app from Xcode and burn all data.
2. Visit a url (ideally one that doesn't redirect anywhere else).
3. Duplicate a tab a couple of times.
4. Open _Main Menu -> History_ and verify that your URL is present there a couple of times (equal to the …
=> Deduplicate entries in History Menu

DuckDuckGo-macOS.xcodeproj/project.pbxproj, DuckDuckGo-macOS.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved, DuckDuckGo/Common/Localizables/UserText.swift, DuckDuckGo/Localizable.xcstrings, DuckDuckGo/MaliciousSiteProtection/MaliciousSiteProtectionManager.swift, LocalPackages/DataBrokerProtection/Package.swift, LocalPackages/FeatureFlags/Package.swift, LocalPackages/HistoryView/Package.swift, LocalPackages/NetworkProtectionMac/Package.swift, LocalPackages/NewTabPage/Package.swift, LocalPackages/SubscriptionUI/Package.swift, LocalPackages/UserScriptActionsManager/Package.swift, LocalPackages/WebKitExtensions/Package.swift, UnitTests/MaliciousSiteProtection/Mocks/MaliciousSiteProtectionMocks.swift
Task/Issue URL: https://app.asana.com/0/1206329551987282/1209158005098852/f 
Tech Design URL: https://app.asana.com/0/1206329551987282/1209133564224796/f
Integrate Malicious Site Protection changes as part of the iOS work. 
During iOS Ship Review we changed copy title for settings. I will double check if these changes needs to be integrated in this PR.
- [] Run PIR E2E tests
1. Ensure CI is green
*Before Merging*
--- …
=> Malicious Site Protection - Update BSK Ref

LocalPackages/DataBrokerProtection/Sources/DataBrokerProtection/Resources/JSON/peoplewhiz.com.json
Task/Issue URL: https://app.asana.com/0/1206873150423133/1209329833070078
CC:
Fixes the PeopleWhiz selector which was appending extra text to the name and causing matches to fail.
1. Load into macOS, test in the debugger
---
[Pull Request Documentation](https://app.asana.com/0/1202500774821704/12040 …
=> Fix PeopleWhiz selector

DuckDuckGo/Statistics/Experiment/PixelExperiment.swift, DuckDuckGo/Tab/Model/Tab.swift
Task/Issue URL: https://app.asana.com/0/1204186595873227/1209311973888722
**Description**: Restart onboarding experiment with contextual onboarding
1. Run ./clean-app.sh debug
2. In Tab.swift in shouldShowOnboarding returns comment out everything besides lines 94 and 95
3. Run the app and should get one of the two onboardings
4. Check the m_mac_onboarding_cohort-assigned pixel is sent with the right cohort (oh for the old and og for the new)
5. Check that at the end of the old onboarding there is no contextual onboarding
6. Check that at the end of the new onboarding there is the contextual onboarding
<!—
Tagging …
=> reset experiment

DuckDuckGo-macOS.xcodeproj/project.pbxproj, DuckDuckGo-macOS.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved, LocalPackages/DataBrokerProtection/Package.swift, LocalPackages/FeatureFlags/Package.swift, LocalPackages/HistoryView/Package.swift, LocalPackages/NetworkProtectionMac/Package.swift, LocalPackages/NewTabPage/Package.swift, LocalPackages/SubscriptionUI/Package.swift, LocalPackages/UserScriptActionsManager/Package.swift, LocalPackages/WebKitExtensions/Package.swift
Task/Issue URL: https://app.asana.com/0/0/1209351911435697/f
Update BSK to a version containing C-S-S fix for HTML New Tab Page.
1. Launch the app from Xcode.
2. Open https://deploy-preview-1468--content-scope-scripts.netlify.app
3. Open New Tab Page. Verify that the long domain name is correctly displayed and burn and favorite icons are visible.
---
=> Fix displaying long URLs on HTML NTP Recent Activity feed

DuckDuckGo/ContentBlocker/ContentBlockerRulesLists.swift
Task/Issue URL: https://app.asana.com/0/1204186595873227/1209345938720177
**Description**: Improves concurrency problems where allowlist is modified or deallocated while in use in the contentBlockerRulesLists getter.
This is a quick fix for the release branch, but we should follow up with making allowlist thread safe in BSK
1.
--- …
=> quick fix for allowlist crash

scripts/update_phishing_detection_data.sh
Task/Issue URL: https://app.asana.com/0/1204023833050360/1209337736035708
CC:
- The macOS browser has a weekly GitHub Actions workflow that updates the phishing protection data set
- When migrating workflows to the Apple monorepo, I noticed that this workflow is broken on main and has been for at least three weeks
- The failure reason is jq: parse error: Invalid numeric literal at line 1, column 12 during the Execute Update Script step
- See https://github.com/duckduckgo/apple-monorepo-test/actions/workflows/macos_update_phishing_detection_data.yml for workflow runs
- This is because we recently changed the backend to use gzipped responses by default which curl wasn't respecting.
Check this to run the Personal Information Removal …
=> Update phishing update script to use compressed curl

DuckDuckGo-macOS.xcodeproj/project.pbxproj, DuckDuckGo/Common/Extensions/WKWebViewConfigurationExtensions.swift, DuckDuckGo/MainWindow/MainWindowController.swift, DuckDuckGo/Menus/MainMenu.swift, DuckDuckGo/NavigationBar/View/NavigationBarViewController.swift, DuckDuckGo/PinnedTabs/Model/PinnedTabsManager.swift, DuckDuckGo/Tab/Model/Tab.swift, DuckDuckGo/Tab/View/BrowserTabViewController.swift, DuckDuckGo/Tab/ViewModel/TabViewModel.swift, DuckDuckGo/TabBar/Model/TabCollection.swift, DuckDuckGo/TabBar/ViewModel/TabCollectionViewModel.swift, LocalPackages/BuildToolPlugins/Plugins/InputFilesChecker/InputFilesChecker.swift
Task/Issue URL: https://app.asana.com/0/1201037661562251/1209357281338183
CC: @tomasstrba 
This change removes Web Extensions code from the App Store build.
1. Verify that CI is green.
2. Smoke test tabs management in the App Store build.
---
=> Disable Web Extensions from the App Store build

DuckDuckGo-macOS.xcodeproj/project.pbxproj, DuckDuckGo/Application/AppDelegate.swift, DuckDuckGo/Common/Extensions/ArrayExtension.swift, DuckDuckGo/History/Services/HistoryViewCoordinator.swift, DuckDuckGo/History/Services/HistoryViewDataProvider.swift, DuckDuckGo/History/Services/HistoryViewErrorHandler.swift, DuckDuckGo/History/View/HistoryWebViewModel.swift, DuckDuckGo/Statistics/HistoryViewPixel.swift, DuckDuckGo/Tab/View/BrowserTabViewController.swift, LocalPackages/HistoryView/Sources/HistoryView/ActionsHandling.swift, LocalPackages/HistoryView/Sources/HistoryView/DataClient.swift, LocalPackages/HistoryView/Sources/HistoryView/DataModel.swift, LocalPackages/HistoryView/Tests/HistoryViewTests/DataClientTests.swift, LocalPackages/HistoryView/Tests/HistoryViewTests/Helpers/MessageHelper.swift, LocalPackages/HistoryView/Tests/HistoryViewTests/Mocks/CapturingActionsHandler.swift, LocalPackages/HistoryView/Tests/HistoryViewTests/Mocks/CapturingDataProvider.swift, LocalPackages/HistoryView/Tests/HistoryViewTests/Mocks/CapturingErrorHandler.swift, UnitTests/Common/Extensions/ArrayExtensionTests.swift, UnitTests/History/Services/HistoryViewCoordinatorTests.swift
Task/Issue URL: https://app.asana.com/0/72649045549333/1209365356928711
This change adds missing unit tests, adds event handling to History View (together with 2 pixels) and
fixes reloading history.
1. Verify that CI is green
2. Run the app from Xcode and enable `historyView` feature flag.
3. Populate fake history items (_Main Menu -> Debug -> History -> Add 10 history visits ..._)
4. Enter history (cmd+y or `duck://history`).
5. Select an option from the left-hand side panel.
6. Visit some website
7. Reload history view. Verify that it properly reloaded data (putting the most recently visited website on top).
---
[Software …
=> Add unit tests for History View user script and fix reloading history

DuckDuckGo/SecureVault/View/PasswordManagementViewController.swift
Task/Issue URL: https://app.asana.com/0/1209121419454298/1204477720783181
Fix tabbing between text fields in the password manager by manually recalculating key view loop in `PasswordManagementViewController`. This isn't done automatically [as `MainWindow` disables `autorecalculatesKeyViewLoop`](https://github.com/duckduckgo/macos-browser/blob/ef70ecc9ed957efeefe2d12870f1ad2b4a903a60/DuckDuckGo/MainWindow/MainWindow.swift#L61).
1. Click  _Open application menu_ (⋯)
2. Click _Passwords & Autofill_
3. Click  _Add item_ (+)
4. Select any type of item, e.g. _Password_
5. Focus on a text field, e.g. the …
=> Password manager: Fix tabbing between text fields

DuckDuckGo/NewTabPage/NewTabPageActionsManagerExtension.swift
Task/Issue URL: https://app.asana.com/0/1201048563534612/1209373805889971
This change ensures that if a user never updated NTP favorites expanded state setting, they will see
expanded favorites on NTP.
1. Run the app and import bookmarks. Ensure that you have more than 6 favorites.
2. On New Tab Page, collapse favorites section so that it displays only 6 favorites.
3. Close the app.
4. Delete settings:
```
defaults delete com.duckduckgo.macos.browser.debug new-tab-page.favorites.is-view-expanded # new, migrated setting
defaults delete com.duckduckgo.macos.browser.debug home.page.show.all.favorites # old setting
```
5. Run the app and verify that all favorites are displayed.
--- …
=> Default to expanded favorites NTP section if setting is not present

DuckDuckGo/MainWindow/MainWindowController.swift
Task/Issue URL: https://app.asana.com/0/1204006570077678/1209339803211451
CC:
Make title bar opaque when in full screen mode without tabs
| Before | After |
| ------ | ----- |
1. Open the browser and open Asana
2. Go to the View menu and deselect `Show Tabs and Bookmarks Bar in Full screen`
3. Enter full screen mode
4. Hover over the top
5. The title bar should be opaque
—
[Pull Request …
=> Make title bar opaque when in full screen mode without tabs

DuckDuckGo/FileDownload/Model/DownloadListViewModel.swift
Task/Issue URL: https://app.asana.com/0/1201048563534612/1209364376915316
CC:
It adds macOS 15.0 to the version pool, showing the download error banner.
1. Hardcode the `currentVersion` to `15.0`
2. In `WebKitDownloadTask.tempDownloadFileCreated`, add some code to throw a `NSError` with code `NSFileReadUnknownError`.
3. Then, try to download a file, it should be fail immediately and show the error banner
4. You can play with different hardcoded macOS versions to check if the banner is being shown.
— …
=> Fix targeted versions for error banner downloads

DuckDuckGo-macOS.xcodeproj/project.pbxproj, DuckDuckGo-macOS.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved, LocalPackages/DataBrokerProtection/Package.swift, LocalPackages/DataBrokerProtectionShared/Package.swift, LocalPackages/FeatureFlags/Package.swift, LocalPackages/HistoryView/Package.swift, LocalPackages/NetworkProtectionMac/Package.swift, LocalPackages/NewTabPage/Package.swift, LocalPackages/SubscriptionUI/Package.swift, LocalPackages/UserScriptActionsManager/Package.swift, LocalPackages/WebKitExtensions/Package.swift
Task/Issue URL: https://app.asana.com/0/72649045549333/1209396115816169
This change bumps C-S-S to a version that includes new APIs for macOS History View
Verify that CI is green
---
=> Update C-S-S to 7.18.0

DuckDuckGo/NewTabPage/NewTabPageWebViewModel.swift
Task/Issue URL: https://app.asana.com/0/1201899738287924/1209398104352347
This change brings back the NTP pixel used for tracking Next Steps cards performance.
1. Update MainWindowControler.swift line 83 to `return true`
2. Clean app data and launch the app from Xcode
3. Go through onboarding and verify in the logs that `m_mac_new-tab-opened_initial` pixel was fired.
--- …
=> Fire NTP initial pixel from HTML New Tab Page

DuckDuckGo-macOS.xcodeproj/project.pbxproj, DuckDuckGo/Common/Extensions/NSPasteboardExtension.swift, UnitTests/Common/NSPasteboardExtensionTests.swift
Task/Issue URL: https://app.asana.com/0/1201048563534612/1209391769658842
This PR fixes an issue where URLs copied from SharePoint wouldn't paste correctly into the address bar. Pasting the URL elsewhere worked fine.
Solution:
The issue is addressed by checking if the copied string results in a URL with a valid scheme in NSPasteboardExtension `var url:URL?`
**Steps to test this PR**: 
1. go to https://duckduckgo-my.sharepoint.com/
2. copy any document URL.
3. open a new tab.
4. paste that URL.
---
[Software …
=> Fix Address bar URL copied from SharePoints 

.github/workflows/macos_bump_internal_release.yml, .github/workflows/macos_pir_end_to_end_tests.yml, .github/workflows/macos_sync_end_to_end.yml, .github/workflows/macos_ui_tests.yml, .github/workflows/macos_update_phishing_detection_data.yml
Task/Issue URL: https://app.asana.com/0/72649045549333/1209393516054365
CC:
This PR disables all cron workflow triggers except for stale PRs, since that one isn't important in this context. The goal here is to disable cron triggers after the monorepo migration, avoiding noise in Asana etc.
This PR is not to be merged until Feb 17 (most likely I will merge it on my Feb 16 evening).
1. Check that no cron jobs are remaining (except for stale PRs which can stay enabled)
--- …
=> Disable most cron workflows
