DuckDuckGo.xcodeproj/project.pbxproj, DuckDuckGo.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved, LocalPackages/DataBrokerProtection/Package.swift, LocalPackages/NetworkProtectionMac/Package.swift, LocalPackages/SubscriptionUI/Package.swift
Task/Issue URL: https://app.asana.com/0/0/1208179338963311/f
Add support for DuckPlayer onboarding on C-S-S
1. Do smoke test validating if Duck Player works on macOS. This shouldn't change anything in the current version
=> Update C-S-S for DuckPlayer onboarding

DuckDuckGo/Bookmarks/Services/BookmarksContextMenu.swift, DuckDuckGo/Bookmarks/View/AddBookmarkPopoverView.swift, DuckDuckGo/Bookmarks/View/BookmarkListViewController.swift, DuckDuckGo/Bookmarks/View/Dialog/AddEditBookmarkDialogView.swift, DuckDuckGo/Bookmarks/View/Dialog/AddEditBookmarkView.swift, DuckDuckGo/BookmarksBar/View/BookmarksBarMenuPopover.swift, DuckDuckGo/Tab/TabExtensions/DuckPlayerTabExtension.swift, DuckDuckGo/Tab/View/BrowserTabViewController.swift
Task/Issue URL: https://app.asana.com/0/1201048563534612/1208204239267609/f
https://app.asana.com/0/1201048563534612/1208160187803231/f
CC:
- Fix "New Folder" button not working in Bookmarks Popover
- Fix bookmarks popover not closed when dragging a bookmark out of it
- Fix Esc key not closing "New Bookmark" dialog
- Fix couple warnings
1. Validate New Folder button works in the Bookmarks Popover
2. Drag a bookmark from the Bookmarks Popover over a Bookmarks Bar folder, validate the popover is closed
3. Click "Add new bookmark", hit Esc key, validate the dialog is closed
4. Add a bookmark, click the "bookmark" button in the address bar, validate Esc key doesn‘t delete the bookmark
--- …
=> Fix bookmarks bar issues

DuckDuckGo/Assets.xcassets/Colors/SystemGray90.colorset/Contents.json, DuckDuckGo/Common/Localizables/UserText.swift, DuckDuckGo/Localizable.xcstrings, DuckDuckGo/YoutubePlayer/Onboarding/DuckPlayerOnboardingModal/DuckPlayerOnboardingModalView.swift, DuckDuckGo/YoutubePlayer/TabModal/TabModal.swift
Task/Issue URL: https://app.asana.com/0/1204167627774280/1208188855592767/f
* Change font style
* Update copy
1. Reset Duck Player onboarding under the debug menu
2. Open youtube.com
3. Check if we're using the [new copy](https://app.asana.com/0/0/1208186144681969/1208191913577718/f) for the modal 
4. Check if the font for the body text has a thinner weight and more spacing
=> UI Ship review feedback for Duck Player onboarding

DuckDuckGo/Tab/ViewModel/TabViewModel.swift
Task/Issue URL: https://app.asana.com/0/414709148257752/1208060693227754/f
- Update address bar URL when page displays a dialog
1. Go through the test steps described in the tasks
2. Validate spoofing tests pass: https://privacy-test-pages.glitch.me/security/address-bar-spoofing/index.html
---
=> Fix wrong URL displayed for auth dialog

DuckDuckGo/Common/Extensions/WKPDFHUDViewWrapper.swift, DuckDuckGo/Tab/View/WebView.swift
Task/Issue URL: https://app.asana.com/0/276630244458377/1208206662726272/f
- Fix zoom in/out using `Cmd`+`+`/`Cmd`+`-` shortcuts
1. Open a PDF, validate `Cmd`+`+`/`Cmd`+`-` shortcuts work, 
2. Validate `…` menu -> Zoom In/Out/Actual size controls work
3. Validate context menu -> Zoom In/Out/Actual size controls work
4. Open a website, validate `Cmd`+`+`/`Cmd`+`-` shortcuts
---
[Pull Request Documentation](https://app.asana.com/0/1202500774821704/1204012835277 …
=> Zoom PDF controls

DuckDuckGo.xcodeproj/project.pbxproj, DuckDuckGo.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved, LocalPackages/DataBrokerProtection/Package.swift, LocalPackages/NetworkProtectionMac/Package.swift, LocalPackages/SubscriptionUI/Package.swift
Task/Issue URL: https://app.asana.com/0/1199230911884351/1208202488078684/f
CC:
1.
---
=> Bump BSK with C-S-S to 6.14.0

.github/actions/asana-log-message/action.yml, .github/workflows/hotfix.yml, .github/workflows/publish_dmg_release.yml, Gemfile.lock, fastlane/Pluginfile
Task/Issue URL: https://app.asana.com/0/1201392122292466/1208137627434488/f
1. See, that https://app.asana.com/0/1201392122292466/1208233977568863/f has been commented by dax, with two types of messages (verbatim and through template).
=> Add AsanaAddComment action

DuckDuckGo.xcodeproj/project.pbxproj, DuckDuckGo/Application/AppDelegate.swift, DuckDuckGo/DBP/DataBrokerProtectionManager.swift, DuckDuckGo/Freemium/FreemiumDebugMenu.swift, DuckDuckGo/Freemium/PIR/FreemiumDBPFirstProfileSavedNotifier.swift, DuckDuckGo/Freemium/PIR/FreemiumPIRScanResultPolling.swift, LocalPackages/DataBrokerProtection/Sources/DataBrokerProtection/Database/DataBrokerProtectionDataManager.swift, LocalPackages/DataBrokerProtection/Sources/DataBrokerProtection/Database/DataBrokerProtectionDatabase.swift, LocalPackages/DataBrokerProtection/Sources/DataBrokerProtection/Model/AttemptInformation.swift, LocalPackages/DataBrokerProtection/Sources/DataBrokerProtection/Model/BrokerJobData.swift, LocalPackages/DataBrokerProtection/Sources/DataBrokerProtection/Model/DataBroker.swift, LocalPackages/DataBrokerProtection/Sources/DataBrokerProtection/Model/ExtractedProfile.swift, LocalPackages/DataBrokerProtection/Sources/DataBrokerProtection/UI/UIMapper.swift, LocalPackages/DataBrokerProtection/Tests/DataBrokerProtectionTests/DataBrokerProtectionDataManagingTests.swift, LocalPackages/DataBrokerProtection/Tests/DataBrokerProtectionTests/Mocks.swift, LocalPackages/Freemium/Sources/Freemium/FreemiumPIRUserStateManager.swift, LocalPackages/Freemium/Tests/FreemiumTests/FreemiumPIRUserStateManagerTests.swift, UnitTests/Freemium/PIR/FreemiumDBPFirstProfileSavedNotifierTests.swift, UnitTests/Freemium/PIR/FreemiumPIRScanResultPollingTests.swift, UnitTests/RemoteMessaging/RemoteMessagingClientTests.swift
Task/Issue URL: https://app.asana.com/0/1201621853593513/1208052452067293/f
Tech Design URL: https://app.asana.com/0/481882893211075/1208179957462572/f
**Description**: This PR implements the Freemium PIR scan observation and polling as described in the related [tech design](https://app.asana.com/0/481882893211075/1208179957462572/f). Changes include:
1. Implement a new `FreemiumPIRScanResultPolling` type to observe for profile save events and poll for results
2. Add a new `DBPProfileSavedNotifier` protocol and concrete `FreemiumDBPFirstProfileSavedNotifier` type to handle logic of deciding to post the profile saved notification
3. Adding a new `matchesFoundCount()` method to `DataBrokerProtectionDataManaging`
4. Adding debug menu commands to reset the related freemium state
5. Adding …
=> Freemium PIR: Post-Scan Engagement Observation & Result Polling

DuckDuckGo/Menus/MainMenu.swift
Task/Issue URL: https://app.asana.com/0/1201037661562251/1208244056763849/f
Autofil logs debug menu restored
=> Autofil logging debug menu restored

.github/workflows/publish_dmg_release.yml
Task/Issue URL: https://app.asana.com/0/1201392122292466/1208137627434494/f
Remove wrong parameter in asana_add_comment action
=> Remove wrong parameter in asana_add_comment action

DuckDuckGo.xcodeproj/project.pbxproj, DuckDuckGo.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved, LocalPackages/DataBrokerProtection/Package.swift, LocalPackages/NetworkProtectionMac/Package.swift, LocalPackages/SubscriptionUI/Package.swift, UnitTests/FileDownload/Helpers/WKDownloadMock.swift
Task/Issue URL: https://app.asana.com/0/1201037661562251/1208260669474950/f
CC:
1.Unit tests should pass
---
=> Fix WKDownloadMock mock

DuckDuckGo.xcodeproj/project.pbxproj, DuckDuckGo.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved, LocalPackages/DataBrokerProtection/Package.swift, LocalPackages/NetworkProtectionMac/Package.swift, LocalPackages/SubscriptionUI/Package.swift
Task/Issue URL: https://app.asana.com/0/1206329551987282/1208084960726981
Update Onboarding Gradients
**SCENARIO 1 - Light Mode**
Perform a search and make the contextual dialog appear and check if it is as specified in [Figma](https://www.figma.com/design/s9cFusskywDt9NFNFuqRcG/Onboarding---Highlights?node-id=7344-15539&t=0tJcPn48LDHfoXjz-1).
**SCENARIO 2 - Dark Mode**
Run the onboarding flow and check that the gradient is the one specified in [Figma](https://www.figma.com/design/s9cFusskywDt9NFNFuqRcG/Onboarding---Highlights?node-id=7405-72449&t=0tJcPn48LDHfoXjz-1).
Repeat the test for light and dark mode.
--- …
=> Update Onboarding gradients

DuckDuckGo/TabBar/View/TabBarViewItem.swift
Task/Issue URL: https://app.asana.com/0/1201048563534612/1208269789955149/f
Latest changes in MouseOverView broke the presentation logic of tab previews. This PR adjusts the logic to fix issues
1. Open multiple tabs.
2.	Move the mouse cursor across the tab bar, ensuring that the correct previews are shown for each tab.
3.	Verify that the tab preview remains visible as long as the mouse cursor is over the tab, without any random hiding.
---
[Pull Request …
=> Tab previews presentation implementation adjusted for the latest MouseOverView logic

DuckDuckGo.xcodeproj/project.pbxproj, DuckDuckGo.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved, LocalPackages/DataBrokerProtection/Package.swift, LocalPackages/NetworkProtectionMac/Package.swift, LocalPackages/SubscriptionUI/Package.swift
Task/Issue URL: https://app.asana.com/0/414235014887631/1208294274484279/f
Update BSK with feature flag for SKAN
No other changes
1. If CI is green, everything is good :)
=> BSK - Add feature flag for SKAN API

DuckDuckGo.xcodeproj/xcshareddata/xcschemes/DuckDuckGo Privacy Browser App Store.xcscheme, DuckDuckGo.xcodeproj/xcshareddata/xcschemes/DuckDuckGo Privacy Browser.xcscheme
Task/Issue URL: https://app.asana.com/0/1201037661562251/1208315478587525/f
These tests are failing because of a typo in the remote config. Let's disable them until the remote config is fixed.
1. Verify that CI is green
---
=> Disable PhishingDetectionIntegrationTests

Gemfile.lock, fastlane/Pluginfile
Task/Issue URL: https://app.asana.com/0/1201037661562251/1208315478516996/f
Verify that the 3 latest comments in [this Asana task](https://app.asana.com/0/1201621708115095/1208180217596769/f) look good.
---
=> Update fastlane plugin to 0.10.0

LocalPackages/DataBrokerProtection/Sources/DataBrokerProtection/Resources/JSON/spokeo.com.json
Task/Issue URL: https://app.asana.com/0/1199230911884351/1208317109476158/f
CC:
1.
---
=> Update Spokeo JSON

DuckDuckGo/Localizable.xcstrings
Task/Issue URL: https://app.asana.com/0/1208273769335188/1208258497786924/f
CC:
Translations for sync promotion
1. Review the sync promotion cards on the passwords & bookmarks screens to confirm all copy is translated
---
=> Sync promotion translations

UnitTests/Subscription/SubscriptionPagesUseSubscriptionFeatureTests.swift
Task/Issue URL: https://app.asana.com/0/1200019156869587/1207743313459997/f
Enhance test for restoring during purchase
1. Run unit tests
---
=> Enhance test for restoring during purchase

DuckDuckGo/PrivacyDashboard/View/PrivacyDashboardViewController.swift, DuckDuckGo/Statistics/GeneralPixel.swift
Task/Issue URL: https://app.asana.com/0/1207340338530322/1208315182484001/f
CC:
Fixes the names of toggle pixels
1. Toggle protections and check the pixel thats fired
---
=> Fix pixel names

DuckDuckGo/Preferences/Model/PreferencesSection.swift
Task/Issue URL: https://app.asana.com/0/1148564399326804/1208314251851763/f
Adding [origin attribution](https://app.asana.com/0/1206716555947156/1206716715679835) to all the links to the landing pages in our apps.
1. Go to Settings -> DuckDuckGo on Other Platforms
2. Make sure the URL contains the origin attribution (https://duckduckgo.com/app?origin=funnel_app_macos)
---
[Pull Request Documentation](https://app.asana.com/0/1202500774821704/1204012835277482/f …
=> Origin added to internal links

DuckDuckGo/Localizable.xcstrings
Task/Issue URL: https://app.asana.com/0/1199230911884351/1208341864628591/f
Localizations for https://app.asana.com/0/1199230911884351/1208316169332403
1. Switch to another language and step through the screens from [here](https://www.figma.com/design/wAWx1a0mAooj6sDCmoTFbS/Password-Manager-security?node-id=192-10952&node-type=frame&t=ZmmHbkxMmNCrEAWa-0) to check they've been translated
---
[Pull Request …
=> Localize autofill security concern mitigation copy

LocalPackages/DataBrokerProtection/Sources/DataBrokerProtection/Scheduler/DataBrokerProtectionQueueManager.swift, LocalPackages/DataBrokerProtection/Tests/DataBrokerProtectionTests/Mocks.swift
Task/Issue URL: https://app.asana.com/0/1201037661562251/1208378563410288/f
CC:
Very minor to fix an odd build quirk in the QueueManager
1. Check the tests run and PIR still works, otherwise nothing to really test directly
---
=> Fix PIR not building on xcode 16

DuckDuckGo/Localizable.xcstrings, LocalPackages/SwiftUIExtensions/Sources/SwiftUIExtensions/TiledImageView.swift
Task/Issue URL: https://app.asana.com/0/1201037661562251/1208387556646887/f
CC:
Fix performance issue with gradient wallpaper
1. See video examples on https://app.asana.com/0/1201037661562251/1208387556646887/f for how to reproduce
2. Basically, add a gradient wallpaper then switch back/forth between tabs with web content
3. Check if you're seeing a performance impact when switching tabs
=> Fix performance issue with gradient wallpaper

DuckDuckGo/Localizable.xcstrings, IntegrationTests/DataImport/CSVImporterIntegrationTests.swift
Task/Issue URL: https://app.asana.com/0/1203822806345703/1207759292115039/f
1. Just make sure CI is green
---
=> Re-enable csv import integration tests

DuckDuckGo.xcodeproj/project.pbxproj, DuckDuckGo.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved, LocalPackages/DataBrokerProtection/Package.swift, LocalPackages/NetworkProtectionMac/Package.swift, LocalPackages/SubscriptionUI/Package.swift
Task/Issue URL: https://app.asana.com/0/414235014887631/1208399924957022/f
- Bumps BSK which includes C.S.S 6.17.0
1. No macOS changes included.
=> Bump BSK to 6.17.0

DuckDuckGo.xcodeproj/project.pbxproj, DuckDuckGo.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved, LocalPackages/DataBrokerProtection/Package.swift, LocalPackages/NetworkProtectionMac/Package.swift, LocalPackages/SubscriptionUI/Package.swift
Task/Issue URL: https://app.asana.com/0/72649045549333/1207836782368194/f
Tech Design URL: https://app.asana.com/0/72649045549333/1207836782368196/f
Corresponding BSK PR: https://github.com/duckduckgo/BrowserServicesKit/pull/1006
Corresponding iOS PR: https://github.com/duckduckgo/iOS/pull/3396
CC:
This PR bumps the BSK pin to pull in the changes from https://github.com/duckduckgo/content-scope-scripts/pull/1026. This feature is not active on desktop platforms, so no changes to be tested from this PR.
--- …
=> Bump BSK to pull in C-S-S 6.19.0

DuckDuckGo.xcodeproj/project.pbxproj, DuckDuckGo.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved, LocalPackages/DataBrokerProtection/Package.swift, LocalPackages/NetworkProtectionMac/Package.swift, LocalPackages/SubscriptionUI/Package.swift
Task/Issue URL: https://app.asana.com/0/1201048563534612/1208413716679959/f
CC:
Bump BSK to include performance fix for suggestions.
1. See https://github.com/duckduckgo/BrowserServicesKit/pull/1008
---
=> fix suggestions performance

DuckDuckGo.xcodeproj/project.pbxproj, DuckDuckGo/BookmarksBar/View/BookmarksBar.storyboard, DuckDuckGo/BookmarksBar/View/BookmarksBarCenterAlignedLayout.swift, DuckDuckGo/BookmarksBar/View/BookmarksBarMenuFactory.swift, DuckDuckGo/BookmarksBar/View/BookmarksBarViewController.swift, DuckDuckGo/Common/Localizables/UserText.swift, DuckDuckGo/Common/Utilities/UserDefaultsWrapper.swift, DuckDuckGo/Localizable.xcstrings, DuckDuckGo/Preferences/Model/AppearancePreferences.swift, DuckDuckGo/Preferences/View/PreferencesAppearanceView.swift, UnitTests/Preferences/AppearancePreferencesTests.swift, UnitTests/Sync/Mocks/MockAppearancePreferencesPersistor.swift
Task/Issue URL: https://app.asana.com/0/0/1208400892922361/f
CC:
- Adds a setting to left-align or center-align the bookmarks bar.
- The setting is shown if the bookmarks is set to be visible. If the bookmarks bar is set to ’Nevert show’ the alignment options will not be visible
https://github.com/user-attachments/assets/81f84dbb-38a0-4b66-8e9b-1d0e9d8163b1
1. Play with the bookmarks alignment setting like the demo, and make sure the alignment is correct.
--- …
=> Add setting for left and center aligning the bookmarks bar

.github/workflows/build_notarized.yml
Task/Issue URL: https://app.asana.com/0/1203301625297703/1208389158142099/f
This change updates review builds workflow to upload DMGs and debug symbols to the CDN S3 bucket
rather than directly to Asana. This is to deal with the 100MB file upload limit in Asana
Verify that [this workflow](https://github.com/duckduckgo/macos-browser/actions/runs/11064723410) uploaded a DMG and dSYMs to S3, posted a comment to [this Asana task](https://app.asana.com/0/0/1208408171489248/f) (the first comment is broken and coming from another workflow run, but the two next comments are correct) and produced "Build Artifacts" step summary with links to artifacts.
--- …
=> Upload review builds DMGs to S3

UITests/UI Tests.xctestplan
Task/Issue URL: https://app.asana.com/0/1201037661562251/1208490757591885/f
**Description**: Temp disable of failing tests. Will assign task to owner to fix and re-enable
1. Green CI
---
=> macOS Maintenance - Disable failing tests

DuckDuckGo/Common/Localizables/UserText+NetworkProtection.swift
Task/Issue URL: https://app.asana.com/0/414235014887631/1207701941801991/f
CC:
Update copy as per the Ship Review.
1. CI passes
---
=> Update unified feedback form copy

DuckDuckGo/RemoteMessaging/RemoteMessagingClient.swift
Task/Issue URL: https://app.asana.com/0/1205237866452338/1208377696019992/f
This is to fix a randomly failing unit test.
1. Verify that CI is green.
2. Update RMF config URL in RemoteMessagingClient.swift to https://www.jsonblob.com/api/1261360708536098816
3. Run the app, open New Tab Page and verify that you get a remote message.
4. Dismiss the message and restart the app or use Main Menu -> Debug -> Remote Messaging Framework -> Refresh Config.
5. Verify that you're keep getting further remote messages from the config.
---
[Technical …
=> Check for RMF store existence inside the Task that triggers fetching

DuckDuckGo/Freemium/DBP/FreemiumDBPScanResultPolling.swift, DuckDuckGo/Freemium/Debug/FreemiumDebugMenu.swift, LocalPackages/DataBrokerProtection/Sources/DataBrokerProtection/UI/DataBrokerProtectionWebUIURLSettings.swift
Task/Issue URL: https://app.asana.com/0/0/1208499724576829/f
**Description**: PR which makes some changes to further enable testing of Freemium PIR
1. N/A, Green CI
---
=> Add Debug Menu To Enable Testing and Lower Periodic Result Check

DuckDuckGo.xcodeproj/project.pbxproj, DuckDuckGo/Bookmarks/Model/BookmarkManager.swift, DuckDuckGo/Bookmarks/Model/BookmarkUrlExtension.swift, DuckDuckGo/Bookmarks/ViewModel/AddEditBookmarkDialogViewModel.swift, DuckDuckGo/NavigationBar/View/AddressBarButtonsViewController.swift, UnitTests/Bookmarks/Model/BookmarkUrlExtensionTests.swift, UnitTests/Bookmarks/Model/LocalBookmarkManagerTests.swift, UnitTests/HomePage/Mocks/MockBookmarkManager.swift
Task/Issue URL: https://app.asana.com/0/1207340338530322/1205619096931465/f
The address bar bookmark icon now indicates that a URL is bookmarked, even if its variants such as different HTTP/HTTPS schemes or trailing slashes are bookmarked.
1. Go to Bookmarks -> Manage Bookmarks
2. Click on New Bookmark
3. Add a bookmark with the following URL: `http://duckDUCKgo.com` (Observe there is HTTP scheme, no trailing slash and some characters are not lowercased)
4. Visit https://duckduckgo.com
5. Make sure the address bar bookmark button indicates the URL is bookmarked
6. Verify you can modify or remove the bookmark from the popup activated from the address bar bookmark button
Optional: Repeat the test while using the new tab page for adding a favorite. …
=> Url variants for bookmark icon

DuckDuckGo.xcodeproj/xcshareddata/xcschemes/DuckDuckGo Privacy Browser App Store.xcscheme, DuckDuckGo.xcodeproj/xcshareddata/xcschemes/DuckDuckGo Privacy Browser.xcscheme
Task/Issue URL: https://app.asana.com/0/1201037661562251/1208312632112873/f
Tech Design URL: N/A
CC:
The Phishing Detection Integration Tests were failing due to a typo on the backend. This typo has now been resolved and the tests are passing again so they can be re-introduced.
1. Check the backend test data is valid:
2. `curl https://duckduckgo.com/api/protection/matches\?hashPrefix\=e4753 | jq '.matches[].regex'`
3. `"https?:\\/\\/privacy-test-pages.site\\/security\\/badware\\/phishing\\.html"` should be in the returned list
4. Run PhishingDetectionIntegrationTests
5. Ensure CI goes green
--- …
=> Reintroduce PhishingDetectionIntegrationTests

DuckDuckGo.xcodeproj/project.pbxproj, DuckDuckGo/Freemium/DBP/Experiment/FreemiumDBPPixelExperimentManaging.swift, DuckDuckGo/Freemium/DBP/FreemiumDBPPromotionViewCoordinating.swift, DuckDuckGo/Freemium/DBP/FreemiumDBPScanResultPolling.swift, DuckDuckGo/Freemium/Debug/FreemiumDebugMenu.swift, DuckDuckGo/NavigationBar/View/MoreOptionsMenu.swift, DuckDuckGo/Tab/UserScripts/Subscription/SubscriptionPagesUseSubscriptionFeature.swift, DuckDuckGo/Tab/UserScripts/UserScripts.swift, LocalPackages/DataBrokerProtection/Sources/DataBrokerProtection/Pixels/FreemiumDBPExperimentPixel.swift, LocalPackages/DataBrokerProtection/Sources/DataBrokerProtection/Scheduler/DataBrokerProtectionAgentManager.swift, LocalPackages/DataBrokerProtection/Sources/DataBrokerProtection/UserNotifications/DataBrokerProtectionUserNotificationService.swift, LocalPackages/DataBrokerProtection/Tests/DataBrokerProtectionTests/DataBrokerProtectionAgentManagerTests.swift, LocalPackages/DataBrokerProtection/Tests/DataBrokerProtectionTests/Mocks.swift, LocalPackages/Freemium/Sources/Freemium/FreemiumDBPUserStateManager.swift, LocalPackages/Freemium/Tests/FreemiumTests/FreemiumDBPUserStateManagerTests.swift, UnitTests/Freemium/DBP/Experiment/FreemiumDBPPixelExperimentManagingTests.swift, UnitTests/Freemium/DBP/FreemiumDBPPromotionViewCoordinatingTests.swift, UnitTests/Freemium/DBP/FreemiumDBPScanResultPollingTests.swift, UnitTests/Menus/MoreOptionsMenuTests.swift, UnitTests/RemoteMessaging/RemoteMessagingClientTests.swift, UnitTests/Subscription/SubscriptionPagesUseSubscriptionFeatureTests.swift, UnitTests/Subscription/SubscriptionPagesUseSubscriptionFeatureTestsForStripe.swift
Task/Issue URL: https://app.asana.com/0/72649045549333/1208317449103070/f
**Description**: This PR makes the following changes:
1. Adds experiment pixels and fires them at designated points
2. Prevents regular PIR Reporting  pixels from firing
3. Changes how we store timestamps for Freemium (just Date objects instead of String)
1. Green CI for New and Updated Tests
—
=> Add Freemium PIR Experiment Pixels

DuckDuckGo/Onboarding/ContextualOnboarding/ContextualOnboardingStateMachine.swift
Task/Issue URL: https://app.asana.com/0/1201048563534612/1208547799518177/f
**Description**: Fix a memory leak (will add test later on)
1. Open a video
2. Close tab
3. Check no audio can be heard
<!—
If this PR isn't ready to be merged for whatever reason it should be marked with the `DO NOT MERGE` label (particularly if it's a draft)
If it's pending Product Review/PFR, please add the `Pending Product Review` label.
If at any point it isn't actively being worked on/ready for review/otherwise moving forward (besides the above PR/PFR exception) strongly consider closing it (or not opening it in the first place). If you decide not to close it, make sure it's labelled to make it clear the PRs state and comment with more information.
—> …
=> fix memory leak

DuckDuckGo.xcodeproj/project.pbxproj, DuckDuckGo/PhishingDetection/PhishingDetection.swift, DuckDuckGo/Preferences/View/PreferencesGeneralView.swift, LocalPackages/DataBrokerProtection/Package.swift, LocalPackages/NetworkProtectionMac/Package.swift, LocalPackages/SubscriptionUI/Package.swift
Task/Issue URL: https://app.asana.com/0/72649045549333/1208270234071171/f
Tech Design URL: n/a
CC:
In [✓ Phishing Detection Pixels](https://app.asana.com/0/0/1207699541075655/f) we defined several pixels to include, and one of them did not make it into the initial release: 
- macos.phishing-detection.feature-toggled:
- Parameters:
- newState - on/off, indicating whether the user turned it on or off
- Condition
- triggers when a user disables the feature from the settings page
- Reasoning
- the aim is to use this as a "do-no-harm" KPI, to determine how many users are actively choosing to disable/enable phishing protection
1. Point BSK to tespach/phish-det-settings-event
2. Build the browser
3. Filter by `m_mac_phishing_detection_setting-toggled` …
=> Add Events Firing for Phishing Detection Settings

DuckDuckGo.xcodeproj/project.pbxproj, DuckDuckGo.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved, LocalPackages/DataBrokerProtection/Package.swift, LocalPackages/NetworkProtectionMac/Package.swift, LocalPackages/SubscriptionUI/Package.swift
Task/Issue URL: https://app.asana.com/0/1200437802575119/1208550540369943/f
CC:
Update BSK to fix content blocker reporting.
1. Run app, browse web, ensure content blocking is reported correctly.
=> bump bsk for content blocker rules fix

DuckDuckGo/Tab/Model/Tab+UIDelegate.swift, DuckDuckGo/Tab/Model/Tab.swift, DuckDuckGo/Tab/View/WebView.swift
Task/Issue URL: https://app.asana.com/0/1202406491309510/1204636589139724/f
- Add support for "Open link in new window" from Inspector
1. Right click a link, choose Inspect
2. Right click the link URL in the Inspector, choose Open link in new window, validate new window is open
---
=> Inspector: open link in new window

.github/workflows/build_hotfix_release.yml
Task/Issue URL:  https://app.asana.com/0/0/1208234424227123/f
CC: @ayoy 
- Targets appstore for hotfix releases (as default is now testflight)
1. 
---
=> Update destination for hotfix release

LocalPackages/DataBrokerProtection/Sources/DataBrokerProtection/UI/DBPUICommunicationLayer.swift
Task/Issue URL: https://app.asana.com/0/1206488453854252/1208494224217327/f
**Description**: Used on the FE side, but not strictly necessary (
**Test Prerequisites**
1. Set yourself as an internal user via Debug menu → Set Internal User State
2. Disable/Signout of Privacy Pro via Settings menu → PP →  Remove from this device
4. Select Debug menu → Freemium -> Enroll into Experiment
1. Relaunch the browser
2. Open Freemium PIR via the banner on the new tab page
3. Ensure the Freemium PIR landing page is displayed (e.g “Find out which sites are selling your info”)
—
[Software Engineering Expectations](https://app.asana.com/0/59792373528535/1990648658 …
=> Freemium PIR: Bump DBP Native <> FE API Version to 7

DuckDuckGo.xcodeproj/project.pbxproj, DuckDuckGo.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved, DuckDuckGo/LoginItems/LoginItemsManager.swift, DuckDuckGo/NetworkProtection/AppTargets/BothAppTargets/NetworkProtectionTunnelController.swift, DuckDuckGo/NetworkProtection/NetworkExtensionTargets/NetworkExtensionTargets/MacPacketTunnelProvider.swift, DuckDuckGo/NetworkProtection/NetworkExtensionTargets/NetworkExtensionTargets/NetworkProtectionTokenStore+SubscriptionTokenKeychainStorage.swift, DuckDuckGoNotifications/DuckDuckGoNotificationsAppDelegate.swift, DuckDuckGoVPN/DuckDuckGoVPNAppDelegate.swift, LocalPackages/DataBrokerProtection/Package.swift, LocalPackages/NetworkProtectionMac/Package.swift, LocalPackages/SubscriptionUI/Package.swift
Task/Issue URL: https://app.asana.com/0/1205842942115003/1208598980823867/f
CC: @diegoreymendez @samsymons 
Some VPN logs level was incorrectly changed during the logging refactoring, this PR reverts it to the original value
=> VPN logs level set as default instead of debug.

DuckDuckGoVPN/DuckDuckGoVPNDebug.entitlements
Task/Issue URL: https://app.asana.com/0/0/1208616989582090/f
Adds app configuration group access to debug VPN menu app.
Note: I'm confused as to why this wasn't causing any apparent trouble.
1. Please clean and rebuild to test this.
2. [Hypothetical] Ensure you see no alerts about our app trying to modify other apps.
---
=> Adds app configuration group access to debug VPN menu app

DuckDuckGo/DBP/DataBrokerProtectionFeatureGatekeeper.swift, DuckDuckGo/DBP/DataBrokerProtectionPixelsHandler.swift, LocalPackages/DataBrokerProtection/Sources/DataBrokerProtection/Pixels/DataBrokerProtectionPixels.swift
Task/Issue URL: https://app.asana.com/0/1203581873609357/1207850832493111/f
CC:
V simple, removes a couple of pixels that fired a lot and one user in particular has not been happy about
1. Check PIR still works
---
=> Remove noisy PIR pixels

DuckDuckGo/Common/Localizables/UserText.swift, DuckDuckGo/Localizable.xcstrings
Task/Issue URL: https://app.asana.com/0/72649045549333/1208641833599433/f
This has been ship reviewed but translations didn't get into the main branch on time.
---
=> Update home page settings popover message

DuckDuckGo.xcodeproj/project.pbxproj, DuckDuckGo.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved, LocalPackages/DataBrokerProtection/Package.swift, LocalPackages/NetworkProtectionMac/Package.swift, LocalPackages/SubscriptionUI/Package.swift
Task/Issue URL: https://app.asana.com/0/1208660715919854/1208660715919854
Autofill Release: https://github.com/duckduckgo/duckduckgo-autofill/releases/tag/15.1.0
BSK PR: https://github.com/duckduckgo/BrowserServicesKit/pull/1044
Updates Autofill to version [15.1.0](https://github.com/duckduckgo/duckduckgo-autofill/releases/tag/15.1.0).
* [Form] expand username re-categorization to phone by @dbajpeyi in https://github.com/duckduckgo/duckduckgo-autofill/pull/691
* [Matching] Add 'search' for forceUnknown by @dbajpeyi in https://github.com/duckduckgo/duckduckgo-autofill/pull/692
* [Release automation] Update asana usage by @dbajpeyi in https://github.com/duckduckgo/duckduckgo-autofill/pull/693
**Full Changelog**: https://github.com/duckduckgo/duckduckgo-autofill/compare/15.0.0...15.1.0
This …
=> Update BSK with autofill 15.1.0

SyncE2EUITests/CriticalPathsTests.swift
Task/Issue URL: https://app.asana.com/0/1201037661562251/1208665937532326/f
Revert bookmark title to "Privacy, simplified".
Verify that [this workflow](https://github.com/duckduckgo/macos-browser/actions/runs/11612877947) is green
---
=> Fix Sync E2E tests

DuckDuckGo.xcodeproj/project.pbxproj, DuckDuckGo.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved, LocalPackages/DataBrokerProtection/Package.swift, LocalPackages/NetworkProtectionMac/Package.swift, LocalPackages/SubscriptionUI/Package.swift
Task/Issue URL: https://app.asana.com/0/1206329551987282/1208577512136709
Add the Add to Dock Promo view to the final dialog of the onboarding flow on iOS.
1. Ensure the project compiles and unit tests pass.
---
=> Add to Dock - Update BSK version

DuckDuckGo.xcodeproj/xcshareddata/xcschemes/DuckDuckGo Privacy Browser App Store.xcscheme
Task/Issue URL: https://app.asana.com/0/1199230911884351/1208639128403740/f
- disable flaky test
1.
---
=> disable testWhenSnapshotIsRestored_ThenRenderingIsSkippedAfterLoading

DuckDuckGo/Assets.xcassets/Information-Remover-128.imageset/Contents.json, DuckDuckGo/Assets.xcassets/Information-Remover-128.imageset/Information-Remover-128.pdf, DuckDuckGo/Common/Localizables/UserText.swift, DuckDuckGo/Freemium/DBP/Extensions/PromotionView+FreemiumDBP.swift, DuckDuckGo/HomePage/Model/PromotionViewModel.swift, DuckDuckGo/HomePage/View/PromotionView.swift, DuckDuckGo/Localizable.xcstrings, UnitTests/Freemium/DBP/FreemiumDBPPromotionViewCoordinatorTests.swift
Task/Issue URL: https://app.asana.com/0/1206488453854252/1208677018043704/f
**Description**: Updates the Freemium PIR new tab page promotion banner as follows:
1. Changes the icon
2. Adds a title
3. Changes the description text and color
4. Adds optional bold text to the promotion description text
Note: Targeting release branch as I want these changes to be available publicly next week
**Test Prerequisites**
1. Set yourself as an internal user via Debug menu → Set Internal User State
2. Disable/Signout of Privacy Pro via Settings menu → PP → Remove from this device
3. Select Debug menu → Freemium -> Reset all Freemium State
4. Select Debug menu → Freemium -> Enroll into Experiment
1. Relaunch the browser
2. Ensure you see the promotion on the new tab page and …
=> Freemium PIR: Ship Review Changes - Updated New Tab Banner UI

DuckDuckGo.xcodeproj/project.pbxproj, DuckDuckGo.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved, LocalPackages/DataBrokerProtection/Package.swift, LocalPackages/NetworkProtectionMac/Package.swift, LocalPackages/SubscriptionUI/Package.swift
Task/Issue URL: https://app.asana.com/0/1201048563534612/1208699974934565/f
This update provides new API for macOS New Tab Page rework. Current production version remains unchanged.
---
=> Update C-S-S to 6.29.0

DuckDuckGo/Localizable.xcstrings
Task/Issue URL: https://app.asana.com/0/1204167627774280/1208541947375319/f
Translations for AI Chat copy changes 
1. Check if CI is green
=> Translations for AI Chat copy changes 

DuckDuckGo/HomePage/Model/NewTabPageSearchBoxExperiment.swift
Task/Issue URL: https://app.asana.com/0/1201037661562251/1208734291836545/f
CC:
Avoid showing the NTP Search Box when running UI Tests.
---
=> Do not run NTP Search Box experiment

DuckDuckGo.xcodeproj/project.pbxproj, DuckDuckGo/InfoPlist.xcstrings, DuckDuckGo/Localizable.xcstrings
Task/Issue URL: https://app.asana.com/0/38424471409662/1208755378695455/f
CC:
Add missing translations to new permissions strings
1. Open different permissions (camera and location) in different languages
2. Check that they are correctly translated
—
=> Add missing translations to new permissions strings

DuckDuckGo.xcodeproj/project.pbxproj, DuckDuckGo.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved, LocalPackages/DataBrokerProtection/Package.swift, LocalPackages/FeatureFlags/Package.swift, LocalPackages/NetworkProtectionMac/Package.swift, LocalPackages/SubscriptionUI/Package.swift
Task/Issue URL: https://app.asana.com/0/1207603085593419/1208194658564979/f
CC:
This PR updates BSK with some auth token logic updates that were written for iOS.
1. Smoke test the VPN - this change mainly affects iOS
---
=> VPN auth token logic update

.github/workflows/pir_end_to_end_tests.yml
Task/Issue URL: https://app.asana.com/0/1199230911884351/1208793631611370/f
CC:
This PR updates the runner image used by the PIR tests.
The PIR tests are currently using Xcode 14, which will no longer work due to GRDB being built with a newer SDK.
1. Check that the PIR E2E test run associated with this PR has succeeded
--- …
=> Update PIR test runner

DuckDuckGo.xcodeproj/project.pbxproj, DuckDuckGo.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved, LocalPackages/DataBrokerProtection/Package.swift, LocalPackages/FeatureFlags/Package.swift, LocalPackages/NetworkProtectionMac/Package.swift, LocalPackages/SubscriptionUI/Package.swift
Task/Issue URL: https://app.asana.com/0/414235014887631/1208817367615044/f
This bumps BSK dependency to the latest version including 211.0.0-1 hotfix.
---
=> Bump BSK to 211.1.1

DuckDuckGo.xcodeproj/xcshareddata/xcschemes/DBPE2ETests.xcscheme, LocalPackages/DataBrokerProtection/Sources/DataBrokerProtection/Resources/JSON/fakebroker.com.json
Task/Issue URL: https://app.asana.com/0/1201037661562251/1208813795849623/f
CC:
Test failed due to invalid JSON.
1. E2E test passes
---
=> Fix failing E2E test due to invalid JSON

DuckDuckGo.xcodeproj/project.pbxproj, DuckDuckGo.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved, DuckDuckGo/Application/AppDelegate.swift, LocalPackages/DataBrokerProtection/Package.swift, LocalPackages/FeatureFlags/Package.swift, LocalPackages/NetworkProtectionMac/Package.swift, LocalPackages/SubscriptionUI/Package.swift
Task/Issue URL: https://app.asana.com/0/414709148257752/1208829922317861/f
CC:
This PR updates macOS to include a breaking change related to the subscription hotfix.
1. Check that the subscription feature works
---
[Pull Request Documentation](https://app.asana.com/0/1202500774821704/120401283527748 …
=> Update macOS branch with subscription hotfix changes

DuckDuckGo.xcodeproj/project.pbxproj, DuckDuckGo.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved, DuckDuckGo/MaliciousSiteProtection/MaliciousSiteProtectionManager.swift
Task/Issue URL: https://app.asana.com/0/481882893211075/1208033567421351/f
BSK PR: https://github.com/duckduckgo/BrowserServicesKit/pull/1092
- Refactor APIClient to use Networking.APIRequestV2; implement generic request/response (BSK)
1. Validate Phishing Protection change sets and Match API calls work as before
---
[Technical Design Template](https://app.asana.com/0/59792373528535/184709971311943 …
=> Malware protection 2: API Client refactoring

DuckDuckGo.xcodeproj/project.pbxproj, DuckDuckGo.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved, LocalPackages/DataBrokerProtection/Package.swift, LocalPackages/FeatureFlags/Package.swift, LocalPackages/NetworkProtectionMac/Package.swift, LocalPackages/SubscriptionUI/Package.swift
Task/Issue URL: https://app.asana.com/0/1204167627774280/1208839072951136/f
CC:
No changes, just BSK update with new feature flags
1. CI should be green
=> BSK update

DuckDuckGo/RemoteMessaging/RemoteMessagingClient.swift
Task/Issue URL: https://app.asana.com/0/0/1208873568477091/f
1. Run the app from Xcode and verify that you're not seeing any remote message.
---
=> Revert to empty RMF config for debug builds

DuckDuckGo.xcodeproj/project.pbxproj, DuckDuckGo.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved, LocalPackages/DataBrokerProtection/Package.swift, LocalPackages/FeatureFlags/Package.swift, LocalPackages/NetworkProtectionMac/Package.swift, LocalPackages/SubscriptionUI/Package.swift
Task/Issue URL: https://app.asana.com/0/414235014887631/1208767141940869/f
**Description**: Bump BSK
1. Green CI
---
=> Bump BSK (due to iOS-only Feature Flag Changes)

DBPE2ETests/DBPEndToEndTests.swift
Task/Issue URL: https://app.asana.com/0/1201037661562251/1208878913064411/f
CC:
**Description**: Update PrivacyConfigurationMock
1. Test should compile
---
=> fix mock in E2EDBP tests

DuckDuckGo.xcodeproj/project.pbxproj
Task/Issue URL: https://app.asana.com/0/1199230911884351/1208888889589895/f
CC:
This PR fixes `loc_export.sh`.
1. Check out this branch and run `./scripts/loc_export.sh`, and verify that you get a valid `xliff` file at the end with no errors in the script
---
[Pull Request …
=> [Release PR] Fix `loc_export.sh`

LocalPackages/DataBrokerProtection/Sources/DataBrokerProtection/Model/DataBroker.swift
Task/Issue URL: https://app.asana.com/0/0/1208895860990675/f
CC:
This fixes an error with JSON decoding preventing PIR to save profile.
1. Test PIR on a fresh install
2. Test PIR on macOS 1.115.0 upgrading to this version
---
[Pull Request …
=> Hotfix for schedulingConfig decoding issue

DuckDuckGo.xcodeproj/project.pbxproj, DuckDuckGo.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved, LocalPackages/DataBrokerProtection/Package.swift, LocalPackages/FeatureFlags/Package.swift, LocalPackages/NetworkProtectionMac/Package.swift, LocalPackages/SubscriptionUI/Package.swift
Task/Issue URL: https://app.asana.com/0/414709148257752/1208887772407026/f
BSK bump after merging in the hotfix changes from 211.1.3-2.
---
=> Update BSK to latest including the hotfix merge

DuckDuckGo.xcodeproj/project.pbxproj, DuckDuckGo.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved, LocalPackages/DataBrokerProtection/Package.swift, LocalPackages/FeatureFlags/Package.swift, LocalPackages/NetworkProtectionMac/Package.swift, LocalPackages/SubscriptionUI/Package.swift
Task/Issue URL: https://app.asana.com/0/414709148257752/1208887772407026/f
BSK bump after merging in the hotfix changes from 211.1.3-2.
---
=> Update BSK to a version including latest hotfix changes

DuckDuckGo.xcodeproj/project.pbxproj, DuckDuckGo.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved, DuckDuckGo/HomePage/Model/HomePageContinueSetUpModel.swift, LocalPackages/DataBrokerProtection/Package.swift, LocalPackages/FeatureFlags/Package.swift, LocalPackages/NetworkProtectionMac/Package.swift, LocalPackages/SubscriptionUI/Package.swift
Task/Issue URL: https://app.asana.com/0/72649045549333/1208905776162821/f
CC:
**Description**: Used Fake Test feature to generate a cohort and do and A/A test run of the New experiment framework. We want to make sure cohort is assigned and pixels are fired as expected.
1. If the configuration is not live yet please use https://www.jsonblob.com/api/jsonBlob/1314517780330110976 as config link
2. Run the app
3. Check 👾[Unique By Name And Parameters-Fired] experiment_enroll_experimentTestAA_treatment_mac ["pixelSource": "phone", "enrollmentDate": "2024-12-06”] is sent (with either treatment or control in …
=> add fake experiment

DuckDuckGo.xcodeproj/project.pbxproj, DuckDuckGo.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved, LocalPackages/DataBrokerProtection/Package.swift, LocalPackages/FeatureFlags/Package.swift, LocalPackages/NetworkProtectionMac/Package.swift, LocalPackages/SubscriptionUI/Package.swift
Task/Issue URL: https://app.asana.com/0/1207619243206445/1208908529122506/f
CC:
This PR updates the macOS app to pull in the BSK app version matching changes added in https://github.com/duckduckgo/BrowserServicesKit/pull/1118.
1. See [BSK PR](https://github.com/duckduckgo/BrowserServicesKit/pull/1118)
--- …
=> Update RMF version matching to ignore build number

DuckDuckGo.xcodeproj/project.pbxproj, DuckDuckGo.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved, LocalPackages/DataBrokerProtection/Package.swift, LocalPackages/FeatureFlags/Package.swift, LocalPackages/NetworkProtectionMac/Package.swift, LocalPackages/NewTabPage/Package.swift, LocalPackages/SubscriptionUI/Package.swift, LocalPackages/WebKitExtensions/Package.swift
Task/Issue URL: https://app.asana.com/0/1204186595873227/1208964427775425/f
**Description**: Update BSK dependency
1. Tests pass
---
=> point to bsk branch

DuckDuckGo/Localizable.xcstrings, LocalPackages/SubscriptionUI/Sources/SubscriptionUI/Preferences/PreferencesSubscriptionModel.swift, LocalPackages/SubscriptionUI/Sources/SubscriptionUI/Preferences/PreferencesSubscriptionView.swift, LocalPackages/SubscriptionUI/Sources/SubscriptionUI/Resources/Localizable.xcstrings, LocalPackages/SubscriptionUI/Sources/SubscriptionUI/UserText.swift
Task/Issue URL: https://app.asana.com/0/1142021229838617/1209014429605257/f
Following https://app.asana.com/0/1142021229838617/1208961863805375/f:
- Update the Privacy Pro settings to include link to Privacy Policy.
- Restore right alignment fro buttons on subscription dialogs.
- Verify footer of Privacy Pro settings when subscription is not active
- Verify footer of Privacy Pro settings when subscription is active
- Verify button placement on "Remove From This Device" dialog
--- …
=> Update to Privacy Pro settings footer

.github/workflows/build_appstore.yml
=> Bump macOS runner While is Blocking Release

.github/workflows/build_appstore.yml
=> Bump runner

DuckDuckGo.xcodeproj/xcshareddata/xcschemes/DuckDuckGo Privacy Browser App Store.xcscheme, DuckDuckGo.xcodeproj/xcshareddata/xcschemes/DuckDuckGo Privacy Browser.xcscheme
Task/Issue URL: https://app.asana.com/0/1199230911884351/1209093806295277/f
CC:
This PR disables the malicious site tests temporarily, to be re-enabled later this week.
---
=> Disable malicious site tests temporarily

DuckDuckGo.xcodeproj/project.pbxproj, DuckDuckGo.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved, LocalPackages/DataBrokerProtection/Package.swift, LocalPackages/FeatureFlags/Package.swift, LocalPackages/NetworkProtectionMac/Package.swift, LocalPackages/NewTabPage/Package.swift, LocalPackages/SubscriptionUI/Package.swift, LocalPackages/WebKitExtensions/Package.swift
Task/Issue URL: https://app.asana.com/0/1201141132935289/1209097550105016/f
CC:
1. Open the Privacy Dashboard, observe it no longer has a white flicker
---
=> dashboard: fixing dashboard flicker

DuckDuckGo.xcodeproj/project.pbxproj, DuckDuckGo.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved, LocalPackages/DataBrokerProtection/Package.swift, LocalPackages/FeatureFlags/Package.swift, LocalPackages/NetworkProtectionMac/Package.swift, LocalPackages/NewTabPage/Package.swift, LocalPackages/SubscriptionUI/Package.swift, LocalPackages/WebKitExtensions/Package.swift
Task/Issue URL: https://app.asana.com/0/0/1209096872344395/f
This change updates C-S-S to the version containing latest fixes to HTML New Tab Page.
The production code isn't affected. This is a major bump of the C-S-S but it's transparent
to native apps (extension-specific change).
---
=> Update C-S-S to 7.1.0

DuckDuckGo.xcodeproj/xcshareddata/xcschemes/DuckDuckGo Privacy Browser App Store.xcscheme, DuckDuckGo.xcodeproj/xcshareddata/xcschemes/DuckDuckGo Privacy Browser.xcscheme
Task/Issue URL: https://app.asana.com/0/1199230911884351/1209093806295277/f
CC:
This PR re-enables malicious site tests.
---
=> Re-enable malicious site integration tests

DuckDuckGo/DBP/DataBrokerProtectionDebugMenu.swift, DuckDuckGo/DBP/DataBrokerProtectionFeatureGatekeeper.swift, DuckDuckGoDBPBackgroundAgent/DuckDuckGoDBPBackgroundAgentAppDelegate.swift, LocalPackages/DataBrokerProtection/Sources/DataBrokerProtection/CCF/DataBrokerProtectionFeature.swift, LocalPackages/DataBrokerProtection/Sources/DataBrokerProtection/CCF/DataBrokerProtectionUtils.swift, LocalPackages/DataBrokerProtection/Sources/DataBrokerProtection/CCF/WebViewHandler.swift, LocalPackages/DataBrokerProtection/Sources/DataBrokerProtection/Database/DataBrokerProtectionDataManager.swift, LocalPackages/DataBrokerProtection/Sources/DataBrokerProtection/DebugUI/DataBrokerRunCustomJSONViewModel.swift, LocalPackages/DataBrokerProtection/Sources/DataBrokerProtection/Operations/DataBrokerJobRunner.swift, LocalPackages/DataBrokerProtection/Sources/DataBrokerProtection/Operations/DataBrokerOperation.swift, LocalPackages/DataBrokerProtection/Sources/DataBrokerProtection/Operations/DataBrokerProfileQueryOperationManager.swift, LocalPackages/DataBrokerProtection/Sources/DataBrokerProtection/Operations/DataBrokerProtectionBrokerUpdater.swift, LocalPackages/DataBrokerProtection/Sources/DataBrokerProtection/Operations/OperationPreferredDateUpdater.swift, LocalPackages/DataBrokerProtection/Sources/DataBrokerProtection/Pixels/DataBrokerProtectionEngagementPixels.swift, LocalPackages/DataBrokerProtection/Sources/DataBrokerProtection/Scheduler/DataBrokerProtectionAgentManager.swift, LocalPackages/DataBrokerProtection/Sources/DataBrokerProtection/Scheduler/DataBrokerProtectionBackgroundActivityScheduler.swift, LocalPackages/DataBrokerProtection/Sources/DataBrokerProtection/Storage/DataBrokerProtectionKeyStoreProvider.swift, LocalPackages/DataBrokerProtection/Sources/DataBrokerProtection/UI/DBPUICommunicationLayer.swift, LocalPackages/DataBrokerProtection/Sources/DataBrokerProtection/UI/UIMapper.swift, LocalPackages/DataBrokerProtection/Sources/DataBrokerProtection/UserNotifications/DataBrokerProtectionUserNotificationService.swift, LocalPackages/DataBrokerProtection/Sources/DataBrokerProtection/Utils/DataBrokerProtectionAgentStopper.swift, LocalPackages/DataBrokerProtection/Sources/DataBrokerProtection/Utils/DataBrokerProtectionSleepObserver.swift
Task/Issue URL: https://app.asana.com/0/1205842942115003/1208612332501635/f
All `.debug` logs replaced with default `.log` in:
- The DBP folder in the main app
- The DataBrokerProtection local package
- The DBPBackgroundAgent
=> All DBP logs reverted to the default level instead of debug.

DuckDuckGo.xcodeproj/project.pbxproj, DuckDuckGo.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved, LocalPackages/DataBrokerProtection/Package.swift, LocalPackages/FeatureFlags/Package.swift, LocalPackages/NetworkProtectionMac/Package.swift, LocalPackages/NewTabPage/Package.swift, LocalPackages/SubscriptionUI/Package.swift, LocalPackages/WebKitExtensions/Package.swift
Task/Issue URL: https://app.asana.com/0/72649045549333/1209115970418978/f
This change includes fixes to HTML New Tab Page UI.
---
=> Update C-S-S to 7.4.0

DuckDuckGo.xcodeproj/project.pbxproj, DuckDuckGo.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved, LocalPackages/DataBrokerProtection/Package.swift, LocalPackages/FeatureFlags/Package.swift, LocalPackages/NetworkProtectionMac/Package.swift, LocalPackages/NewTabPage/Package.swift, LocalPackages/SubscriptionUI/Package.swift, LocalPackages/WebKitExtensions/Package.swift
Task/Issue URL: https://app.asana.com/0/1204167627774280/1209108545833453/f
CC:
Update BSK with AI Chat deeplink feature flag
1. Validate if tests are green
=> Update BSK with AI Chat deeplink feature flag

LocalPackages/DataBrokerProtection/Sources/DataBrokerProtection/Resources/JSON/backgroundcheck.run.json, LocalPackages/DataBrokerProtection/Sources/DataBrokerProtection/Resources/JSON/clubset.com.json, LocalPackages/DataBrokerProtection/Sources/DataBrokerProtection/Resources/JSON/councilon.com.json, LocalPackages/DataBrokerProtection/Sources/DataBrokerProtection/Resources/JSON/curadvisor.com.json, LocalPackages/DataBrokerProtection/Sources/DataBrokerProtection/Resources/JSON/kwold.com.json, LocalPackages/DataBrokerProtection/Sources/DataBrokerProtection/Resources/JSON/newenglandfacts.com.json, LocalPackages/DataBrokerProtection/Sources/DataBrokerProtection/Resources/JSON/people-background-check.com.json, LocalPackages/DataBrokerProtection/Sources/DataBrokerProtection/Resources/JSON/vericora.com.json, LocalPackages/DataBrokerProtection/Sources/DataBrokerProtection/Resources/JSON/veriforia.com.json, LocalPackages/DataBrokerProtection/Sources/DataBrokerProtection/Resources/JSON/virtory.com.json, LocalPackages/DataBrokerProtection/Sources/DataBrokerProtection/Resources/JSON/wellnut.com.json
Task/Issue URL: https://app.asana.com/0/608920331025329/1209014062691302/f
CC:
1.
---
=> Convert Verecor child sites to be parent sites

DuckDuckGo/HomePage/Model/HomePageAddressBarModel.swift
Task/Issue URL: https://app.asana.com/0/1201048563534612/1209158272007943/f
- fix circular reference in AddressBarModel causing video not stopping after closing a window
1. Open Settings
2. Open a video
3. Close the window, validate video stops playing
---
=> fix circular reference in AddressBarModel

DuckDuckGo/NetworkProtection/AppTargets/BothAppTargets/NetworkProtectionNavBarPopoverManager.swift, DuckDuckGo/Preferences/Model/VPNPreferencesModel.swift, DuckDuckGoVPN/DuckDuckGoVPNAppDelegate.swift, LocalPackages/NetworkProtectionMac/Package.swift, LocalPackages/NetworkProtectionMac/Sources/NetworkProtectionProxy/Controller/TransparentProxyController.swift, LocalPackages/NetworkProtectionMac/Sources/NetworkProtectionProxy/IPC/TransparentProxyAppMessageHandler.swift, LocalPackages/NetworkProtectionMac/Sources/NetworkProtectionProxy/Provider/TransparentProxyProvider.swift, LocalPackages/NetworkProtectionMac/Sources/NetworkProtectionProxy/Settings/TransparentProxySettings.swift, LocalPackages/NetworkProtectionMac/Sources/NetworkProtectionProxy/Settings/UserDefaultsExtensions/UserDefaults+vpnProxyFeatureAvailable.swift, LocalPackages/NetworkProtectionMac/Sources/NetworkProtectionUI/Menu/StatusBarMenu.swift, LocalPackages/NetworkProtectionMac/Sources/NetworkProtectionUI/Views/StatusView/NetworkProtectionStatusViewModel.swift, LocalPackages/NetworkProtectionMac/Sources/NetworkProtectionUI/Views/TipViews/Model/VPNTipsModel.swift, LocalPackages/NetworkProtectionMac/Sources/NetworkProtectionUI/Views/TunnelControllerView/TunnelControllerView.swift, LocalPackages/NetworkProtectionMac/Sources/NetworkProtectionUI/Views/TunnelControllerView/TunnelControllerViewModel.swift, LocalPackages/NetworkProtectionMac/Tests/NetworkProtectionUITests/TunnelControllerViewModelTests.swift
Task/Issue URL: https://app.asana.com/0/1207603085593419/1209168347582143/f
We're temporarily disabling domain exclusions from App Store builds.
We'll migrate this to a remote feature flag next week, but doing that later as it requires 4 PRs (vs 1 for this approach).
1. Run the App Store build
2. Go to Debug > TipKit > Reset TipKit
3. Re-run the App Store build
4. Go to VPN Settings and make sure there's nothing about website exclusions
5. Start the VPN
6. Open a website and make sure there's nothing about website exclusions in the VPN settings screen
7. Dismiss the geoswitching tip, and make sure you don't see any tip about domain exclusions
8. Turn OFF the VPN and back ON
9. Make sure you see the autoconnect tip in the VPN status view.
1. Run the sparkle build
2. Go to Debug > TipKit > …
=> Disables domain exclusions in App Store builds

DuckDuckGo.xcodeproj/project.pbxproj, DuckDuckGo.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved, LocalPackages/DataBrokerProtection/Package.swift, LocalPackages/FeatureFlags/Package.swift, LocalPackages/NetworkProtectionMac/Package.swift, LocalPackages/NewTabPage/Package.swift, LocalPackages/SubscriptionUI/Package.swift, LocalPackages/WebKitExtensions/Package.swift
Task/Issue URL: https://app.asana.com/0/1206226850447395/1209192796290067/f
CC:
Updates BSK version only. No changes to macOS app.
1. Make sure app builds and tests pass.
---
=> Add WebView state restoration privacy feature

IntegrationTests/Configurations/ConfigurationManagerIntegrationTests.swift
Task/Issue URL: https://app.asana.com/0/0/1209188876122811/f
**Description**: Fix Flaky test. The initial etag can be nil
1. CI is green
---
=> fix flaky test

DuckDuckGo/Updates/UpdateController.swift
Task/Issue URL: https://app.asana.com/0/1201037661562251/1209076015967731/f
CC:
Fixes an issue where Check for Update button does nothing.
1. Download and install https://staticcdn.duckduckgo.com/macos-desktop-browser/duckduckgo-1.112.0.296.dmg (last build prior to the custom UI refactoring)
2. Launch the app and quit it before automatic update finishes
3. Download and install https://staticcdn.duckduckgo.com/macos-desktop-browser/duckduckgo-1.122.0.346.dmg
4. Launch the app and try to manually check for updates. Expect the button to do nothing.
5. Download and install …
=> Fix SUAutomaticallyUpdate issue

DuckDuckGo-macOS.xcodeproj/project.pbxproj, DuckDuckGo-macOS.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved, LocalPackages/DataBrokerProtection/Package.swift, LocalPackages/FeatureFlags/Package.swift, LocalPackages/HistoryView/Package.swift, LocalPackages/NetworkProtectionMac/Package.swift, LocalPackages/NewTabPage/Package.swift, LocalPackages/SubscriptionUI/Package.swift, LocalPackages/UserScriptActionsManager/Package.swift, LocalPackages/WebKitExtensions/Package.swift
Task/Issue URL: https://app.asana.com/0/0/1209119248168429/f
**Description**: No functional change to macOS
1. Green CI
**Definition of Done (Internal Only)**:
---
=> Mobile Free Trials: BSK Bump on macOS, No Functional Change

DuckDuckGo-macOS.xcodeproj/xcshareddata/xcschemes/DuckDuckGo Privacy Browser.xcscheme
Task/Issue URL: https://app.asana.com/0/1201037661562251/1209237178820494/f
CC: @Bunn @tomasstrba 
Disable a failing integration test
1.
---
=> Disable CPM filterlist test

DuckDuckGo-macOS.xcodeproj/project.pbxproj, DuckDuckGo-macOS.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
Task/Issue URL: https://app.asana.com/0/1206329551987282/1209242004458518/f
Update BSK Ref to version where clientSideHit pixel parameter is optional
1. Ensure CI is green
---
=> Malicious Site Protection - Optional clientSideHit parameter

DuckDuckGo-macOS.xcodeproj/project.pbxproj, DuckDuckGo-macOS.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved, LocalPackages/DataBrokerProtection/Package.swift, LocalPackages/FeatureFlags/Package.swift, LocalPackages/HistoryView/Package.swift, LocalPackages/NetworkProtectionMac/Package.swift, LocalPackages/NewTabPage/Package.swift, LocalPackages/SubscriptionUI/Package.swift, LocalPackages/UserScriptActionsManager/Package.swift, LocalPackages/WebKitExtensions/Package.swift
Task/Issue URL: https://app.asana.com/0/0/1209294882371818/f
Update translations for New Tab Page on macOS.
---
=> Update C-S-S to 7.15.0

DuckDuckGo-macOS.xcodeproj/xcshareddata/xcschemes/macOS Browser App Store.xcscheme, DuckDuckGo-macOS.xcodeproj/xcshareddata/xcschemes/macOS Browser.xcscheme, IntegrationTests/Configurations/ConfigurationManagerIntegrationTests.swift
Task/Issue URL: https://app.asana.com/0/1199333091098016/1209334737154919
CC:
This PR disables a failing integration test.
---
=> Disable failing integration test

DuckDuckGo-macOS.xcodeproj/project.pbxproj, DuckDuckGo-macOS.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved, LocalPackages/DataBrokerProtection/Package.swift, LocalPackages/DataBrokerProtectionShared/Package.swift, LocalPackages/FeatureFlags/Package.swift, LocalPackages/HistoryView/Package.swift, LocalPackages/NetworkProtectionMac/Package.swift, LocalPackages/NewTabPage/Package.swift, LocalPackages/SubscriptionUI/Package.swift, LocalPackages/UserScriptActionsManager/Package.swift, LocalPackages/WebKitExtensions/Package.swift
Task/Issue URL: https://app.asana.com/0/414235014887631/1209351911435697
Update BSK to a version containing C-S-S fix for HTML New Tab Page.
Verify that CI is green (the actual fix is tested in #3848).
---
=> Bump BSK to the newest version

DuckDuckGo-macOS.xcodeproj/project.pbxproj, DuckDuckGo-macOS.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved, LocalPackages/DataBrokerProtection/Package.swift, LocalPackages/DataBrokerProtectionShared/Package.swift, LocalPackages/FeatureFlags/Package.swift, LocalPackages/HistoryView/Package.swift, LocalPackages/NetworkProtectionMac/Package.swift, LocalPackages/NewTabPage/Package.swift, LocalPackages/SubscriptionUI/Package.swift, LocalPackages/UserScriptActionsManager/Package.swift, LocalPackages/WebKitExtensions/Package.swift
Task/Issue URL: https://app.asana.com/0/1206488453854252/1209235370800483
**Description**: BSK Bump (No macOS Functional Changes)
1. Green CI
---
=> Privacy Pro Free Trials - BSK Bump (No macOS Functional Changes)

LocalPackages/DataBrokerProtection/Sources/DataBrokerProtection/Resources/JSON/peoplewhiz.com.json
Task/Issue URL: https://app.asana.com/0/1199230911884351/1209363504477900
CC:
The PeopleWhiz JSON version wasn’t bumped in #3839, doing that here.
1.
---
=> Bump PeopleWhiz version

DuckDuckGo-macOS.xcodeproj/project.pbxproj
Task/Issue URL: https://app.asana.com/0/1201037661562251/1209394902147446
This change replaces buildable folders with file groups to maintain compatibility with Xcode 14 and Xcode 13.
---
=> Fix project file compatibility with older Xcode versions
